import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createPageDraftSession,pageDraftKey} from '../lib/bloomops/page-drafts.mjs';
const initial={title:'Guide',body:'<p>One</p>',revision:1};
function session(c,options={}){const s=createPageDraftSession({initial,delay:100000,...options});c.after(()=>s.dispose());return s;}
test('edits during a pending save serialize against its returned revision',async c=>{let release;const gate=new Promise(r=>release=r),calls=[];const s=session(c,{save:async value=>{calls.push(value);if(calls.length===1)await gate;return {ok:true,revision:value.expectedRevision+1};}});s.edit({body:'Two'});const done=s.flush();s.edit({title:'New title',body:'Three'});assert.equal(calls.length,1);release();await done;assert.deepEqual(calls.map(x=>[x.body,x.expectedRevision]),[['Two',1],['Three',2]]);assert.equal(s.snapshot().dirty,false);assert.equal(s.snapshot().draft.title,'New title');});
test('network failure keeps draft, avoids retry loops and retries explicitly',async c=>{let fail=true,calls=0;const persisted=[];const s=session(c,{persist:d=>persisted.push(d),save:async v=>{calls++;if(fail)throw Error();return {ok:true,revision:v.expectedRevision+1};}});s.edit({body:'Recover me'});await s.flush();assert.equal(s.snapshot().error.kind,'network');s.edit({body:'Still here'});await s.flush();assert.equal(calls,1);assert.equal(persisted.at(-1).body,'Still here');fail=false;await s.retry();assert.equal(s.snapshot().dirty,false);});
test('conflict never retries or silently overwrites a newer version',async c=>{let calls=0;const s=session(c,{save:async()=>{calls++;return {ok:false,reason:'conflict',error:'Changed'};}});s.edit({body:'My draft'});await s.flush();await s.retry();assert.equal(calls,1);assert.equal(s.snapshot().draft.body,'My draft');s.useSaved({title:'Other title',body:'Their version',revision:3});assert.equal(s.snapshot().draft.body,'Their version');assert.equal(s.snapshot().dirty,false);});
test('same-tab recovery restores same revision and flags conflicting revisions',async c=>{const a=session(c),b=session(c);assert.ok(a.restore({title:'Recovered',body:'draft',revision:1}));assert.equal(a.snapshot().error,null);b.useSaved({...initial,revision:2});b.restore({title:'Recovered',body:'draft',revision:1});assert.equal(b.snapshot().error.kind,'conflict');assert.equal(b.snapshot().draft.body,'draft');});
test('recovery keys isolate user, workspace and page',()=>{const a=pageDraftKey('u','w','p');for(const args of [['other','w','p'],['u','other','p'],['u','w','other']])assert.notEqual(a,pageDraftKey(...args));});
test('disposing a pending request cannot clear a newer editor recovery copy',async c=>{let release,clears=0;const gate=new Promise(r=>release=r),s=session(c,{clear:()=>clears++,save:async()=>{await gate;return {ok:true,revision:2};}});s.edit({body:'Pending'});const done=s.flush();s.dispose();release();await done;assert.equal(clears,0);});
test('invalid title can be corrected and saved; malformed acknowledgements retain draft',async c=>{let bad=true;const s=session(c,{save:async v=>bad?{ok:false,reason:'invalid'}:{ok:true,revision:v.expectedRevision+1}});s.edit({title:''});await s.flush();bad=false;s.edit({title:'Fixed'});await s.flush();assert.equal(s.snapshot().dirty,false);const b=session(c,{save:async()=>({ok:true,revision:99})});b.edit({body:'Local'});await b.flush();assert.equal(b.snapshot().error.kind,'network');assert.equal(b.snapshot().dirty,true);});
