import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createClientDraftStore, clientDraftValue, emptyClientFields, CLIENT_DRAFT_TTL } from '../lib/bloomops/client-draft-store.mjs';
import { DRAFT_CONTEXT_KEY, CLIENT_DRAFT_PREFIX, changeDraftContext } from '../lib/bloomops/draft-context.mjs';
const scope={userId:'user',workspaceId:'workspace'},clock=Date.parse('2026-09-14T12:00:00Z');
function storage(){const values={};return new Proxy({getItem:k=>values[k]??null,setItem:(k,v)=>{values[k]=String(v);},removeItem:k=>{delete values[k];}},{ownKeys:()=>Object.keys(values),getOwnPropertyDescriptor:(_,k)=>Object.hasOwn(values,k)?{enumerable:true,configurable:true}:undefined});}
const draft=()=>({requestId:crypto.randomUUID(),fields:{...emptyClientFields(),name:'Incomplete',contactEmail:'bad@',website:'https://'},pending:null});
const store=(s,id=crypto.randomUUID(),at=clock,context=scope)=>createClientDraftStore(s,context,id,()=>at);
test('independent copies preserve raw incomplete values and exact attempted input in original scope',()=>{const s=storage(),a=store(s),b=store(s),input=draft();input.pending={...input.fields,name:'Original sent name'};a.write(input);b.write({...draft(),fields:{...input.fields,name:'Other tab'}});assert.equal(a.list().length,2);assert.deepEqual(a.snapshot(a.own).value.pending,input.pending);assert.equal(a.snapshot(a.own).value.requestId,input.requestId);assert.equal(a.snapshot(a.own).value.fields.contactEmail,'bad@');for(const patch of [{userId:'other'},{workspaceId:'other'}]){const foreign=store(s,crypto.randomUUID(),clock,{...scope,...patch});assert.deepEqual(foreign.list(),[]);assert.equal(foreign.snapshot(a.own),null);assert.equal(foreign.remove(a.own),false);}});
test('ten-copy bound never retires a source unless replacement was stored, and CAS protects a newer writer',()=>{const s=storage(),writers=Array.from({length:10},()=>store(s));for(const w of writers)w.write(draft());const next=store(s),source=next.snapshot(writers[0].own);assert.throws(()=>next.write(source.value),/Ten client recovery/);assert.ok(next.snapshot(writers[0].own));writers[0].write(draft());assert.equal(next.remove(writers[0].own,source.raw),false);assert.equal(next.list().length,10);});
test('expiry purges only this original workspace without extending old copies',()=>{const s=storage(),a=store(s),b=store(s,crypto.randomUUID(),clock,{...scope,workspaceId:'other'});a.write(draft());b.write(draft());const later=store(s,crypto.randomUUID(),clock+CLIENT_DRAFT_TTL+1);assert.deepEqual(later.list(),[]);assert.equal(s.getItem(a.own),null);assert.ok(s.getItem(b.own));});
test('malformed, oversized encoded and wrong-scope copies are refused',()=>{const s=storage(),a=store(s);a.write(draft());const {value}=a.snapshot(a.own);for(const patch of [{userId:'foreign'},{requestId:'invalid'},{pending:{}},{fields:{...value.fields,extra:'field'}},{fields:{...value.fields,name:'x'.repeat(4097)}},{updatedAt:clock+60001}])assert.equal(clientDraftValue({...value,...patch},scope,clock),null);s.setItem(a.own,JSON.stringify({...value,extra:'花'.repeat(90000)}));assert.equal(a.snapshot(a.own),null);});
test('quota errors retain source and mounted caller data',()=>{const s=storage(),a=store(s),input=draft();a.write(input);const original=s.getItem(a.own),next=store(s);s.setItem=()=>{throw Error('quota');};assert.throws(()=>next.write(input),/quota/);assert.equal(s.getItem(a.own),original);assert.equal(input.fields.name,'Incomplete');});
test('blank fields with a pending attempt remain recoverable; deliberate retirement clears only own copy',()=>{const s=storage(),a=store(s),b=store(s),input=draft();input.pending={...input.fields};input.fields=emptyClientFields();a.write(input);b.write(draft());assert.ok(a.snapshot(a.own));a.write(null);assert.equal(s.getItem(a.own),null);assert.ok(s.getItem(b.own));});
test('disposed writers and changed epochs cannot rewrite or remove retained input',()=>{const s=storage(),a=store(s);a.write(draft());const raw=s.getItem(a.own);s.setItem(DRAFT_CONTEXT_KEY,'changed');assert.equal(a.write(draft()),false);assert.equal(a.remove(a.own),false);assert.equal(s.getItem(a.own),raw);const b=store(s);b.dispose();assert.equal(b.write(draft()),false);});
test('explicit logout clears client copies across scopes and prevents disposed-copy resurrection',()=>{const s=storage(),a=store(s),b=store(s,crypto.randomUUID(),clock,{...scope,workspaceId:'other'});a.write(draft());b.write(draft());const saved={window:globalThis.window,localStorage:globalThis.localStorage,sessionStorage:globalThis.sessionStorage,dispatchEvent:globalThis.dispatchEvent,BroadcastChannel:globalThis.BroadcastChannel,CustomEvent:globalThis.CustomEvent};try{globalThis.window={dispatchEvent:()=>{}};globalThis.localStorage=s;globalThis.sessionStorage=storage();globalThis.dispatchEvent=()=>{};globalThis.BroadcastChannel=class{postMessage(){}close(){}};globalThis.CustomEvent=class{};changeDraftContext({logout:true});assert.equal(Object.keys(s).filter(k=>k.startsWith(CLIENT_DRAFT_PREFIX)).length,0);assert.equal(a.write(draft()),false);}finally{Object.assign(globalThis,saved);}});
