import {test} from 'node:test';
import assert from 'node:assert/strict';
import {sourceFixture} from './_prospect-source-fixture.mjs';
import {run,one,all} from './_bloomops-db.mjs';
import {saveProspectSender} from '../lib/bloomops/prospect-outreach.mjs';
import {getProspectGoogle,beginProspectGoogle,finishProspectGoogle,disconnectProspectGoogle} from '../lib/bloomops/prospect-google.mjs';
import {googleConfiguration,GOOGLE_SCOPES,digest,sealGoogle,openGoogle} from '../lib/bloomops/prospect-google-provider.mjs';
const env={BLOOMOPS_ENV:'development',BLOOMOPS_APP_URL:'http://localhost:8787',BLOOMOPS_GOOGLE_CONNECT_ENABLED:'true',BLOOMOPS_GOOGLE_CLIENT_ID:'synthetic.apps.googleusercontent.com',BLOOMOPS_GOOGLE_CLIENT_SECRET:'synthetic-client-secret',BLOOMOPS_GOOGLE_TOKEN_KEY:'12'.repeat(32)};
const input={workspaceId:'fresh',senderRevision:1,expectedRevision:0};
const body=data=>new Response(JSON.stringify(data),{headers:{'content-type':'application/json'}});
function provider(t,patch={}){return async(url,opts)=>{t.calls.push({url,opts});if(url.endsWith('/token'))return body({access_token:'synthetic-access',refresh_token:'synthetic-refresh',expires_in:3600,token_type:'Bearer',scope:GOOGLE_SCOPES.join(' '),...patch.token});if(url.endsWith('/profile'))return body({emailAddress:'ary@bloomwired.io',...patch.profile});if(url.endsWith('/sendAs'))return body({sendAs:[{sendAsEmail:'hello@bloomwired.io',verificationStatus:'accepted'}],...patch.aliases});throw new Error('Unexpected provider URL');};}
async function setup(c){const t=await sourceFixture(c);t.sessionId='local-session';t.calls=[];run(t.raw,"INSERT INTO session(id,user_id,token,expires_at,created_at,updated_at) VALUES(?,?,?,?,?,?)",t.sessionId,'owner','synthetic-session-token',Date.now()+86400000,Date.now(),Date.now());assert.ok((await saveProspectSender(t.db,t.actor,{workspaceId:'fresh',expectedRevision:0,fields:{provider:'google_workspace',email:'hello@bloomwired.io',displayName:'Ary'}})).saved);return t;}
async function start(t,patch={}){const r=await beginProspectGoogle(t.db,t.actor,env,t.sessionId,{...input,...patch});assert.ok(r.url,JSON.stringify(r));return {state:new URL(r.url).searchParams.get('state'),code:'synthetic-code',url:r.url};}
const finish=(t,a,opts={})=>finishProspectGoogle(t.db,t.actor,env,t.sessionId,a,{fetcher:provider(t),...opts});
const saved=t=>JSON.stringify(['prospect_google_connections','activity_events','gmail_accounts','send_events'].map(table=>all(t.raw,'SELECT * FROM '+table+' ORDER BY rowid')));
test('failed provider verification logs only a fixed code and preserves generic UI and single-use rejection',async c=>{
 const t=await setup(c),a=await start(t),before=saved(t),warnings=[];
 c.mock.method(console,'warn',(...args)=>warnings.push(args));
 const result=await finish(t,a,{fetcher:async()=>{throw new Error('PRIVATE provider credentials and response');}});
 assert.deepEqual(warnings,[['Bloomsi Google verification failed:','token_request_transport']]);
 assert.deepEqual(result,{unavailable:true,error:'Google connection could not be verified. Check the account and permissions, then try again.'});
 assert.equal(saved(t),before);assert.ok((await finish(t,a)).conflict);assert.equal(warnings.length,1);
});
test('Google configuration is dedicated, explicit and origin-safe; legacy secrets cannot activate it',()=>{assert.ok(googleConfiguration(env));for(const patch of [{BLOOMOPS_GOOGLE_CONNECT_ENABLED:undefined},{BLOOMOPS_GOOGLE_TOKEN_KEY:''},{BLOOMOPS_GOOGLE_CLIENT_ID:''},{BLOOMOPS_GOOGLE_CLIENT_SECRET:''},{BLOOMOPS_APP_URL:'https://user:pass@example.com/'},{BLOOMOPS_APP_URL:'https://example.com/callback'},{BLOOMOPS_APP_URL:'http://example.com/'},{BLOOMOPS_APP_URL:'https://example.com/?x=1'},{BLOOMOPS_ENV:'staging'}])assert.equal(googleConfiguration({...env,...patch}),null);assert.equal(googleConfiguration({GOOGLE_CLIENT_ID:'legacy',GOOGLE_CLIENT_SECRET:'legacy',LTB_SESSION_SECRET:'legacy'}),null);});
test('token boxes reject plaintext, tampering, another workspace, purpose and key',async()=>{const config=googleConfiguration(env),box=await sealGoogle(config,'fresh:tokens','secret');assert.equal(await openGoogle(config,'fresh:tokens',box),'secret');for(const context of ['source:tokens','fresh:attempt:x'])assert.equal(await openGoogle(config,context,box),null);assert.equal(await openGoogle(config,'fresh:tokens','plaintext'),null);assert.equal(await openGoogle({...config,key:'34'.repeat(32)},'fresh:tokens',box),null);assert.equal(await openGoogle(config,'fresh:tokens',box.slice(0,-4)+'AAAA'),null);});
test('OAuth start stores only a hashed session-bound nonce and encrypted PKCE verifier',async c=>{const t=await setup(c),a=await start(t),url=new URL(a.url),row=one(t.raw,'SELECT * FROM prospect_google_attempts');assert.equal(row.state_hash,await digest(a.state));assert.equal(row.session_hash,await digest(t.sessionId));assert.equal(url.searchParams.get('code_challenge_method'),'S256');assert.equal(url.searchParams.get('redirect_uri'),'http://localhost:8787/api/bloomops/prospecting/google/callback');assert.equal(url.searchParams.has('client_secret'),false);assert.equal(t.calls.length,0);assert.equal(JSON.stringify(row).includes(t.sessionId),false);assert.ok(row.verifier_box.startsWith('v1.'));});
test('accepted alias consent creates one encrypted connection/event without touching legacy or sends',async c=>{const t=await setup(c),a=await start(t);assert.deepEqual(await finish(t,a),{connected:true});const r=await getProspectGoogle(t.db,t.actor,env),row=one(t.raw,'SELECT * FROM prospect_google_connections');assert.equal(r.connected,true);assert.equal(r.accountEmail,'ary@bloomwired.io');assert.equal(JSON.stringify(r).includes('synthetic'),false);assert.ok(!JSON.stringify(row).includes('synthetic-access'));assert.equal(JSON.parse(await openGoogle(googleConfiguration(env),'fresh:tokens',row.token_box)).refreshToken,'synthetic-refresh');assert.equal(one(t.raw,'SELECT count(*) n FROM gmail_accounts').n,0);assert.equal(one(t.raw,'SELECT count(*) n FROM send_events').n,0);assert.deepEqual(t.calls.map(c=>c.url),['https://oauth2.googleapis.com/token','https://gmail.googleapis.com/gmail/v1/users/me/profile','https://gmail.googleapis.com/gmail/v1/users/me/settings/sendAs']);assert.equal(one(t.raw,"SELECT count(*) n FROM activity_events WHERE event_type='PROSPECT_GOOGLE_CONNECTED'").n,1);});
test('missing configuration and denied roles/workspaces make no nonce or provider call',async c=>{const t=await setup(c);assert.ok((await beginProspectGoogle(t.db,t.actor,{},t.sessionId,input)).unavailable);for(const actor of [null,{...t.actor,role:'client'},{...t.actor,role:'project_manager'},{...t.actor,workspaceId:'source',membershipId:'src'}]){assert.equal(await getProspectGoogle(t.db,actor,env),null);const result=await beginProspectGoogle(t.db,actor,env,t.sessionId,{...input,workspaceId:actor?.workspaceId||'fresh'});assert.equal(result,null);}assert.equal(one(t.raw,'SELECT count(*) n FROM prospect_google_attempts').n,0);});
test('wrong session, actor, sender revision, expiry and revoked membership reject callback before provider calls',async c=>{for(const kind of ['session','actor','sender','expiry','revoked','stamp','session-deleted']){const t=await setup(c),a=await start(t);let actor=t.actor,session=t.sessionId;if(kind==='session')session='other';if(kind==='actor')actor={...actor,userId:'stranger'};if(kind==='sender')run(t.raw,'UPDATE prospect_senders SET revision=revision+1');if(kind==='expiry')run(t.raw,"UPDATE prospect_google_attempts SET expires_at='2000-01-01T00:00:00.000Z'");if(kind==='revoked')run(t.raw,"UPDATE workspace_memberships SET status='suspended' WHERE id='dest'");if(kind==='stamp')run(t.raw,"UPDATE workspace_memberships SET updated_at='different' WHERE id='dest'");if(kind==='session-deleted')run(t.raw,'DELETE FROM session WHERE id=?',session);const before=saved(t),r=await finishProspectGoogle(t.db,actor,env,session,a,{fetcher:provider(t)});assert.ok(!r?.connected,kind);assert.equal(t.calls.length,0);assert.equal(saved(t),before);}});
test('replayed and concurrent same-state callbacks exchange exactly once',async c=>{const t=await setup(c),a=await start(t),results=await Promise.all([finish(t,a),finish(t,a)]);assert.equal(results.filter(r=>r.connected).length,1);assert.equal(t.calls.length,3);const before=saved(t);assert.ok((await finish(t,a)).conflict);assert.equal(t.calls.length,3);assert.equal(saved(t),before);});
test('concurrent distinct consent attempts cannot overwrite the winning connection',async c=>{const t=await setup(c),a=await start(t),b=await start(t);const results=await Promise.all([finish(t,a),finish(t,b)]);assert.equal(results.filter(r=>r.connected).length,1);assert.equal(one(t.raw,'SELECT revision FROM prospect_google_connections').revision,1);assert.equal(one(t.raw,"SELECT count(*) n FROM activity_events WHERE event_type='PROSPECT_GOOGLE_CONNECTED'").n,1);});
test('declined/partial consent, absent refresh, wrong or pending alias never attaches tokens',async c=>{for(const patch of [{token:{scope:GOOGLE_SCOPES[0]}},{token:{refresh_token:null}},{token:{token_type:'unknown'}},{token:{expires_in:Infinity}},{profile:{emailAddress:'invalid'}},{aliases:{sendAs:[{sendAsEmail:'other@example.com',verificationStatus:'accepted'}]}},{aliases:{sendAs:[{sendAsEmail:'hello@bloomwired.io',verificationStatus:'pending'}]}}]){const t=await setup(c),a=await start(t),before=saved(t);assert.ok((await finish(t,a,{fetcher:provider(t,patch)})).unavailable);assert.equal(saved(t),before);assert.ok((await finish(t,a)).conflict);}const t=await setup(c),a=await start(t);assert.ok((await finish(t,{...a,error:'access_denied'})).cancelled);assert.equal(t.calls.length,0);assert.ok((await finish(t,a)).conflict);});
test('provider failures are bounded and return no response text or secret',async c=>{for(const fetcher of [async()=>new Response('private secret',{status:500}),async()=>body({padding:'x'.repeat(70000)}),async()=>{throw new Error('private secret')}]){const t=await setup(c),r=await finish(t,await start(t),{fetcher});assert.ok(r.unavailable);assert.equal(JSON.stringify(r).includes('private secret'),false);assert.equal(one(t.raw,'SELECT count(*) n FROM prospect_google_connections').n,0);}});
test('revocation, session deletion, sender edit or disconnect during provider work blocks final write',async c=>{for(const kind of ['membership','session','sender','connection']){const t=await setup(c);if(kind==='connection')await finish(t,await start(t));const a=await start(t,kind==='connection'?{expectedRevision:1}:{}),normal=provider(t);let changed=false;const fetcher=async(u,o)=>{const result=await normal(u,o);if(!changed){changed=true;if(kind==='membership')run(t.raw,"UPDATE workspace_memberships SET status='suspended' WHERE id='dest'");if(kind==='session')run(t.raw,'DELETE FROM session');if(kind==='sender')run(t.raw,'UPDATE prospect_senders SET revision=revision+1');if(kind==='connection')await disconnectProspectGoogle(t.db,t.actor,{workspaceId:'fresh',expectedRevision:1});}return result;};const r=await finish(t,a,{fetcher});assert.ok(r.conflict,kind);assert.equal(one(t.raw,"SELECT count(*) n FROM activity_events WHERE event_type='PROSPECT_GOOGLE_CONNECTED'").n,kind==='connection'?1:0);}});
test('activity failure rolls back connection but leaves nonce consumed for safe retry behavior',async c=>{const t=await setup(c),a=await start(t),before=saved(t);t.raw.exec("CREATE TRIGGER fail_google BEFORE INSERT ON activity_events WHEN NEW.event_type='PROSPECT_GOOGLE_CONNECTED' BEGIN SELECT RAISE(ABORT,'fixture'); END;");await assert.rejects(()=>finish(t,a));assert.equal(saved(t),before);assert.ok(one(t.raw,'SELECT consumed_at FROM prospect_google_attempts').consumed_at);assert.ok((await finish(t,a)).conflict);});
test('connection status invalidates after sender address or authorizer changes; name-only edit stays connected',async c=>{const t=await setup(c);await finish(t,await start(t));run(t.raw,"UPDATE prospect_senders SET display_name='Different',revision=revision+1");assert.equal((await getProspectGoogle(t.db,t.actor,env)).connected,true);run(t.raw,"UPDATE prospect_senders SET email='different@example.com',revision=revision+1");assert.equal((await getProspectGoogle(t.db,t.actor,env)).connected,false);run(t.raw,"UPDATE prospect_senders SET email='hello@bloomwired.io',revision=revision+1");run(t.raw,"UPDATE workspace_memberships SET updated_at='new-stamp' WHERE id='dest'");assert.equal((await getProspectGoogle(t.db,t.actor,env)).connected,false);});
test('local disconnect clears grant, invalidates outstanding callbacks and is revision guarded',async c=>{const t=await setup(c);await finish(t,await start(t));const a=await start(t,{expectedRevision:1});assert.ok((await disconnectProspectGoogle(t.db,t.actor,{workspaceId:'fresh',expectedRevision:1})).disconnected);assert.equal(one(t.raw,'SELECT token_box FROM prospect_google_connections').token_box,null);assert.equal((await getProspectGoogle(t.db,t.actor,env)).connected,false);assert.ok((await finish(t,a)).conflict);const before=saved(t);assert.ok((await disconnectProspectGoogle(t.db,t.actor,{workspaceId:'fresh',expectedRevision:1})).conflict);assert.equal(saved(t),before);});
test('nonce creation has bounded outstanding requests and live session checks',async c=>{const t=await setup(c);for(let i=0;i<5;i++)await start(t);assert.ok((await beginProspectGoogle(t.db,t.actor,env,t.sessionId,input)).conflict);assert.equal(one(t.raw,'SELECT count(*) n FROM prospect_google_attempts').n,5);run(t.raw,'DELETE FROM session');assert.ok((await beginProspectGoogle(t.db,t.actor,env,t.sessionId,input)).conflict);assert.deepEqual(all(t.raw,'PRAGMA foreign_key_check'),[]);});

test('missing or rotated token key never reports a usable connection',async c=>{const t=await setup(c);await finish(t,await start(t));assert.equal((await getProspectGoogle(t.db,t.actor,{})).connected,false);assert.equal((await getProspectGoogle(t.db,t.actor,{...env,BLOOMOPS_GOOGLE_TOKEN_KEY:'34'.repeat(32)})).connected,false);assert.equal((await getProspectGoogle(t.db,t.actor,env)).connected,true);});

// Google verificationStatus applies only to custom From aliases. The primary
// address must independently match the authenticated mailbox profile.
test('primary address without custom-alias status connects only when mailbox identity agrees',async c=>{
 const t=await setup(c),a=await start(t);
 const fetcher=provider(t,{profile:{emailAddress:'Hello@Bloomwired.io'},aliases:{sendAs:[{sendAsEmail:'HELLO@bloomwired.io',isPrimary:true}]}});
 assert.deepEqual(await finish(t,a,{fetcher}),{connected:true});
 assert.equal((await getProspectGoogle(t.db,t.actor,env)).accountEmail,'hello@bloomwired.io');
 assert.equal(one(t.raw,"SELECT count(*) n FROM activity_events WHERE event_type='PROSPECT_GOOGLE_CONNECTED'").n,1);
});
test('mismatched primary identity and unverified custom aliases cannot attach a grant',async c=>{
 for(const alias of [
  {sendAsEmail:'hello@bloomwired.io',isPrimary:true},
  {sendAsEmail:'hello@bloomwired.io',isPrimary:true,verificationStatus:'accepted'},
  {sendAsEmail:'other@bloomwired.io',isPrimary:true},
  {sendAsEmail:'hello@bloomwired.io',isPrimary:false},
  {sendAsEmail:'hello@bloomwired.io',isPrimary:false,verificationStatus:'pending'}
 ]){const t=await setup(c),a=await start(t),before=saved(t);
  assert.ok((await finish(t,a,{fetcher:provider(t,{aliases:{sendAs:[alias]}})})).unavailable);
  assert.equal(saved(t),before);
 }
});
