import {test} from 'node:test';
import assert from 'node:assert/strict';
import {fixture} from './_prospect-conversion-fixture.mjs';
import {run,all} from './_bloomops-db.mjs';
import {saveServiceOffering} from '../lib/bloomops/service-offerings.mjs';
import {previewMultiHandoff} from '../lib/bloomops/prospect-multi-handoff.mjs';
import {convertProspect,getProspectConversion} from '../lib/bloomops/prospect-conversions.mjs';
async function setup(c){const t=await fixture(c),custom=await saveServiceOffering(t.db,t.actor,{workspaceId:'w',userId:t.actor.userId,requestId:crypto.randomUUID(),name:'Synthetic custom offering'});assert.ok(custom.ok);t.input={workspaceId:'w',mode:'new',clientId:null,services:[{serviceTypeId:'w-service',packageName:'Core',scopeNotes:'Synthetic first scope'},{serviceTypeId:custom.offering.id,packageName:'Custom',scopeNotes:'Synthetic second scope'}]};t.command=async(input=t.input)=>{const view=await previewMultiHandoff(t.db,t.actor,t.id,input);assert.ok(view.ok,JSON.stringify(view));return {...input,requestId:crypto.randomUUID(),reviewHash:view.conversionReview.hash,confirmed:true};};return t;}
const rows=(t,table)=>all(t.raw,'SELECT * FROM '+table);
test('two purchased services commit one client/contact/receipt with separate immutable scope',async c=>{const t=await setup(c),before=rows(t,'bloomops_clients').length,command=await t.command(),result=await convertProspect(t.db,t.actor,t.id,command);assert.ok(result.ok,JSON.stringify(result));assert.equal(result.receipt.services.length,2);assert.equal(rows(t,'bloomops_clients').length,before+1);assert.equal(rows(t,'client_contacts').filter(r=>r.client_id===result.receipt.clientId).length,1);assert.equal(rows(t,'service_engagements').length,2);assert.equal(rows(t,'prospect_conversions').length,1);assert.equal(rows(t,'prospect_conversion_services').length,2);assert.deepEqual(new Set(result.receipt.services.map(r=>r.scopeNotes)),new Set(['Synthetic first scope','Synthetic second scope']));const again=await convertProspect(t.db,t.actor,t.id,{...command,services:[...command.services].reverse()});assert.ok(again.ok);assert.equal(again.receipt.id,result.receipt.id);assert.equal(rows(t,'service_engagements').length,2);assert.throws(()=>run(t.raw,"UPDATE prospect_conversion_services SET scope_notes='changed'"),/immutable/);assert.throws(()=>run(t.raw,'DELETE FROM prospect_conversion_services'),/permanent/);assert.equal((await getProspectConversion(t.db,t.actor,t.id)).receipt.services.length,2);});
test('one invalid or changed selection leaves no partially converted client',async c=>{const t=await setup(c),command=await t.command(),before=rows(t,'bloomops_clients').length;for(const services of [[...command.services,{serviceTypeId:'foreign-service',scopeNotes:'Invalid'}],[command.services[0],command.services[0]],[{...command.services[0],scopeNotes:'Changed'},command.services[1]]])assert.equal((await convertProspect(t.db,t.actor,t.id,{...command,services})).ok,false);assert.equal(rows(t,'bloomops_clients').length,before);assert.equal(rows(t,'service_engagements').length,0);assert.equal(rows(t,'prospect_conversions').length,0);});
for(const table of ['bloomops_clients','client_contacts','service_engagements','prospect_conversions'])test('zero-row '+table+' write rolls back the complete multiple-service handoff',async c=>{const t=await setup(c),command=await t.command(),before=rows(t,'bloomops_clients');run(t.raw,'CREATE TRIGGER skip_source BEFORE INSERT ON '+table+' BEGIN SELECT RAISE(IGNORE); END');const result=await convertProspect(t.db,t.actor,t.id,command);assert.equal(result.ok,false);assert.deepEqual(rows(t,'bloomops_clients'),before);assert.equal(rows(t,'service_engagements').length,0);assert.equal(rows(t,'prospect_conversion_services').length,0);});
test('revocation after preview denies all multi-service writes',async c=>{const t=await setup(c),command=await t.command(),before=rows(t,'bloomops_clients');run(t.raw,"UPDATE workspace_memberships SET status='suspended' WHERE id='m'");assert.equal((await convertProspect(t.db,t.actor,t.id,command)).ok,false);assert.deepEqual(rows(t,'bloomops_clients'),before);assert.equal(rows(t,'prospect_conversions').length,0);});

test('receipt revocation between parent and service reads returns no private data',async c=>{
 const t=await setup(c),saved=await convertProspect(t.db,t.actor,t.id,await t.command());assert.ok(saved.ok);
 const original=t.d1.prepare.bind(t.d1);let intercepted=false;
 t.d1.prepare=sql=>{const wrap=statement=>new Proxy(statement,{get(target,key){if(key==='bind')return(...args)=>wrap(target.bind(...args));if(key==='raw')return async(...args)=>{const result=await target.raw(...args);if(!intercepted&&/from "prospect_conversions"/.test(sql)){intercepted=true;run(t.raw,"UPDATE workspace_memberships SET status='suspended' WHERE id='m'");}return result;};return target[key];}});return wrap(original(sql));};
 assert.deepEqual(await getProspectConversion(t.db,t.actor,t.id),{ok:false,reason:'not_found'});assert.equal(intercepted,true);
});
