import {test} from 'node:test';
import assert from 'node:assert/strict';
import {fixture} from './_prospect-conversion-fixture.mjs';
import {run,all} from './_bloomops-db.mjs';
import {saveServiceOffering} from '../lib/bloomops/service-offerings.mjs';
const command=t=>({workspaceId:t.actor.workspaceId,userId:t.actor.userId,requestId:crypto.randomUUID(),name:'Synthetic website care'});
test('custom offering is reusable, idempotent and can be renamed with a current version',async c=>{const t=await fixture(c),input=command(t),a=await saveServiceOffering(t.db,t.actor,input),b=await saveServiceOffering(t.db,t.actor,input);assert.ok(a.ok);assert.equal(b.offering.id,a.offering.id);assert.equal(all(t.raw,'SELECT * FROM service_engagements').length,0);const edit={workspaceId:input.workspaceId,userId:input.userId,id:a.offering.id,expectedUpdatedAt:a.offering.updatedAt,name:'Synthetic website maintenance'};const changed=await saveServiceOffering(t.db,t.actor,edit);assert.ok(changed.ok);assert.equal(changed.offering.name,edit.name);assert.equal((await saveServiceOffering(t.db,t.actor,{...edit,name:'Stale'})).reason,'conflict');assert.equal(all(t.raw,'SELECT * FROM service_types WHERE id=?',a.offering.id).length,1);});
test('custom offering rejects foreign scopes, non administrators and revoked authority',async c=>{const t=await fixture(c),input=command(t);for(const actor of [{...t.actor,role:'team_member'},{...t.actor,role:'project_manager'},{...t.actor,workspaceId:'foreign'}])assert.equal((await saveServiceOffering(t.db,actor,input)).ok,false);assert.equal((await saveServiceOffering(t.db,t.actor,{...input,userId:'someone-else'})).ok,false);run(t.raw,"UPDATE workspace_memberships SET status='suspended' WHERE id='m'");assert.equal((await saveServiceOffering(t.db,t.actor,input)).ok,false);assert.equal(all(t.raw,"SELECT * FROM service_types WHERE slug LIKE 'custom-%'").length,0);});
test('invalid names and changed creation intent create no extra catalogue records',async c=>{const t=await fixture(c),input=command(t);for(const name of ['', 'x'.repeat(121),'bad\nname'])assert.equal((await saveServiceOffering(t.db,t.actor,{...input,name})).ok,false);assert.ok((await saveServiceOffering(t.db,t.actor,input)).ok);assert.equal((await saveServiceOffering(t.db,t.actor,{...input,name:'Other intent'})).reason,'conflict');assert.equal(all(t.raw,"SELECT * FROM service_types WHERE slug LIKE 'custom-%'").length,1);});
