import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mailboxFixture} from './_prospect-mailbox-fixture.mjs';
import {run,one,all} from './_bloomops-db.mjs';
import {activateProspectFollowups,getProspectFollowups,runProspectFollowup,reconcileProspectFollowup,runScheduledProspectFollowup} from '../lib/bloomops/prospect-followups.mjs';
import {getProspectResults} from '../lib/bloomops/prospect-results.mjs';
import {recoverProspectMailbox,checkpointProspectMailbox} from '../lib/bloomops/prospect-mailbox.mjs';
import {getProspectMailboxReview,saveProspectHistoricalCoverage} from '../lib/bloomops/prospect-mailbox-review.mjs';
import {previewProspectSchedule} from '../lib/bloomops/prospect-schedule.mjs';
import {prospectAutomationOverview} from '../lib/bloomops/prospect-overview.mjs';

const rfc=t=>one(t.raw,'SELECT rfc_message_id id FROM prospect_delivery_identities').id;
async function fixture(c,fieldOverrides={}){
 const t=await mailboxFixture(c,{fieldOverrides});const receipt=one(t.raw,'SELECT * FROM prospect_deliveries');t.deliveryId=receipt.id;
 Object.assign(t.env,{BLOOMOPS_GOOGLE_RECOVERY_ENABLED:'true',BLOOMOPS_GOOGLE_CHECKPOINT_ENABLED:'true',BLOOMOPS_HISTORICAL_COVERAGE_ENABLED:'true'});
 const command=async()=>({workspaceId:'fresh',accountEmail:'hello@example.test',expectedRevision:t.mailstate()?.revision||0,connectionRevision:1,senderRevision:1,reviewed:true}),fetcher=async url=>{const u=new URL(url);if(u.pathname.endsWith('/profile'))return Response.json({emailAddress:'hello@example.test',historyId:'100'});if(u.pathname.endsWith('/messages'))return Response.json({messages:[]});if(u.pathname.endsWith('/history'))return Response.json({historyId:'101'});throw Error('unexpected metadata request');};
 assert.ok((await recoverProspectMailbox(t.db,t.actor,t.env,t.session,await command(),{fetcher})).checked);const source=one(t.raw,"SELECT id FROM prospect_discovery_runs WHERE kind='recovery'").id;
 assert.ok((await checkpointProspectMailbox(t.db,t.actor,t.env,t.session,{...await command(),sourceRunId:source},{fetcher:async()=>{throw Error('provider forbidden')}})).checked);const review=await getProspectMailboxReview(t.db,t.actor,t.env),requestId=crypto.randomUUID();
 assert.ok((await saveProspectHistoricalCoverage(t.db,t.actor,t.env,t.session,{workspaceId:'fresh',selection:review.historical.selection,requestId,expectedRevision:review.expectedRevision,connectionRevision:1,senderRevision:1,reviewed:true})).ok);
 t.env={...t.env,BLOOMOPS_GOOGLE_REPLY_CHECK_ENABLED:'true',BLOOMOPS_GOOGLE_REPLY_DELIVERY_ID:receipt.id,BLOOMOPS_GOOGLE_FOLLOWUP_ENABLED:'true',BLOOMOPS_GOOGLE_FOLLOWUP_WORKSPACE_ID:'fresh',BLOOMOPS_GOOGLE_FOLLOWUP_ACCOUNT_EMAIL:'hello@example.test'};
 t.input={workspaceId:'fresh',prospectId:t.id,deliveryId:receipt.id,reviewed:true};return t;
}
const anchor=t=>{const receipt=one(t.raw,'SELECT * FROM prospect_deliveries');return {id:'sent-message',threadId:'sent-thread',labelIds:['SENT'],internalDate:String(Date.parse(receipt.accepted_at)),payload:{headers:[{name:'Message-ID',value:rfc(t)},{name:'From',value:'"Ary, Bloomwired" <hello@example.test>'},{name:'To',value:t.fields.recipient},{name:'Subject',value:t.fields.subject}]}};};
const provider=(t,{reply=false,uncertain=false}={})=>{let sends=0,reads=0;return {get sends(){return sends;},get reads(){return reads;},fetcher:async(url,init)=>{const u=new URL(url);if(u.pathname.endsWith('/messages/send')){sends++;if(uncertain)return new Response(null,{status:503});const body=JSON.parse(init.body),mime=Buffer.from(body.raw,'base64url').toString();assert.equal(body.threadId,'sent-thread');assert.ok(mime.includes('In-Reply-To: '+rfc(t)));assert.ok(mime.includes(t.fields.followUp2));return Response.json({id:'followup-'+sends,threadId:'sent-thread'});}reads++;const messages=[anchor(t)];if(reply)messages.push({id:'reply',threadId:'sent-thread',labelIds:['INBOX'],internalDate:String(Date.now()+1000),payload:{headers:[{name:'Message-ID',value:'<reply@example.test>'},{name:'From',value:'Person <inbox@example.test>'},{name:'To',value:'hello@example.test'},{name:'In-Reply-To',value:rfc(t)}]}});return Response.json({id:'sent-thread',messages});}};};
const activate=async t=>activateProspectFollowups(t.db,t.actor,t.session,{...t.input,reviewed:true},new Date());
const due=t=>new Date(Date.parse(one(t.raw,"SELECT scheduled_at FROM prospect_followup_attempts WHERE state='scheduled' ORDER BY message_number LIMIT 1").scheduled_at)+60000);

test('activation is duplicate-safe, uses the approved three-message ceiling and persists recipient-local business-day dates',async c=>{const t=await fixture(c),result=await Promise.all([activate(t),activate(t)]);assert.ok(result.every(x=>x.activated));assert.equal(result[0].sequenceId,result[1].sequenceId);const sequence=one(t.raw,'SELECT * FROM prospect_followup_sequences'),plan=previewProspectSchedule(t.fields.timeZone,one(t.raw,'SELECT accepted_at FROM prospect_deliveries').accepted_at);assert.equal(sequence.total_messages,3);assert.equal(sequence.second_scheduled_at,plan.messages[1].at);assert.equal(sequence.third_scheduled_at,plan.messages[2].at);assert.deepEqual(all(t.raw,'SELECT message_number,state FROM prospect_followup_attempts ORDER BY message_number').map(x=>({...x})),[{message_number:2,state:'scheduled'},{message_number:3,state:'scheduled'}]);const status={sender:{email:'hello@example.test'},connection:{configured:true,hasStoredGrant:true}};const inactive=await prospectAutomationOverview(t.db,t.actor,{...t.env,BLOOMOPS_GOOGLE_FOLLOWUP_ENABLED:'false'},status),running=await prospectAutomationOverview(t.db,t.actor,t.env,status);assert.equal(inactive.state,'inactive');assert.equal(inactive.counts.running,1);assert.equal(running.state,'running');});

test('shorter approved sequences do not invent missing messages',async c=>{for(const [patch,total,attempts,state] of [[{followUp3:null},2,1,'running'],[{followUp2:null,followUp3:null},1,0,'complete']]){const t=await fixture(c,patch);assert.ok((await activate(t)).activated);assert.equal(one(t.raw,'SELECT total_messages n,state FROM prospect_followup_sequences').n,total);assert.equal(one(t.raw,'SELECT state FROM prospect_followup_sequences').state,state);assert.equal(one(t.raw,'SELECT count(*) n FROM prospect_followup_attempts').n,attempts);}});

test('a recorded permanent stop prevents sequence activation',async c=>{const t=await fixture(c);run(t.raw,"UPDATE prospect_reply_states SET revision=revision+1,hold_state='stopped',stop_reason='opt_out',stop_note='Synthetic opt-out',stopped_by_membership_id='dest',stopped_at='2026-09-17T00:00:00.000Z',updated_at='2026-09-17T00:00:00.000Z'");const view=await getProspectFollowups(t.db,t.actor,t.env,t.id);assert.equal(view.canActivate,false);assert.equal(view.reason,'A recorded stop prevents further outreach.');assert.equal((await activate(t)).conflict,true);assert.equal(one(t.raw,'SELECT count(*) n FROM prospect_followup_sequences').n,0);});

test('disabled execution makes zero provider calls and no delivery mutation',async c=>{const t=await fixture(c);await activate(t);const p=provider(t),before=JSON.stringify(all(t.raw,'SELECT * FROM prospect_followup_sequences UNION ALL SELECT * FROM prospect_followup_sequences'));delete t.env.BLOOMOPS_GOOGLE_FOLLOWUP_ENABLED;const row=one(t.raw,'SELECT id FROM prospect_followup_sequences'),result=await runProspectFollowup(t.db,t.actor,t.env,t.session,{workspaceId:'fresh',prospectId:t.id,sequenceId:row.id},{fetcher:p.fetcher,clock:()=>new Date('2026-09-17T17:00:00.000Z')});assert.ok(result.unavailable);assert.equal(p.sends+p.reads,0);assert.equal(JSON.stringify(all(t.raw,'SELECT * FROM prospect_followup_sequences UNION ALL SELECT * FROM prospect_followup_sequences')),before);assert.equal(one(t.raw,"SELECT count(*) n FROM prospect_followup_attempts WHERE state!='scheduled'").n,0);});

test('the dormant scheduler is disabled by default and a configured local tick processes one due sequence',async c=>{const t=await fixture(c);await activate(t);const p=provider(t),before=JSON.stringify(all(t.raw,'SELECT * FROM prospect_followup_attempts'));assert.deepEqual(await runScheduledProspectFollowup(t.db,t.env,{fetcher:p.fetcher,clock:()=>due(t)}),{disabled:true});assert.equal(p.reads+p.sends,0);assert.equal(JSON.stringify(all(t.raw,'SELECT * FROM prospect_followup_attempts')),before);t.env.BLOOMOPS_GOOGLE_FOLLOWUP_SCHEDULER_ENABLED='true';t.env.BLOOMOPS_GOOGLE_FOLLOWUP_SESSION_ID=t.session;const result=await runScheduledProspectFollowup(t.db,t.env,{fetcher:p.fetcher,clock:()=>due(t)});assert.ok(result.accepted);assert.equal(p.reads,1);assert.equal(p.sends,1);});

test('a post-claim crash is reconciled by the scheduler without another send',async c=>{const t=await fixture(c);await activate(t);const attempt=one(t.raw,"SELECT * FROM prospect_followup_attempts WHERE message_number=2");run(t.raw,"UPDATE prospect_followup_attempts SET state='submitting',attempted_at=?,account_email='hello@example.test',updated_at=? WHERE id=?",attempt.scheduled_at,attempt.scheduled_at,attempt.id);t.env.BLOOMOPS_GOOGLE_FOLLOWUP_SCHEDULER_ENABLED='true';t.env.BLOOMOPS_GOOGLE_FOLLOWUP_SESSION_ID=t.session;let sends=0,reads=0;const found=async(url)=>{const u=new URL(url);if(u.pathname.endsWith('/messages/send')){sends++;throw Error('must not send');}reads++;if(u.searchParams.has('q'))return Response.json({messages:[{id:'crash-recovered',threadId:'sent-thread'}]});return Response.json({id:'crash-recovered',threadId:'sent-thread',labelIds:['SENT'],payload:{headers:[{name:'Message-ID',value:attempt.message_id},{name:'From',value:'Ary, Bloomwired <hello@example.test>'},{name:'To',value:t.fields.recipient},{name:'In-Reply-To',value:rfc(t)},{name:'References',value:rfc(t)}]}});};const recovered=await runScheduledProspectFollowup(t.db,t.env,{fetcher:found,clock:()=>due(t)});assert.ok(recovered.accepted);assert.equal(sends,0);assert.equal(reads,2);assert.equal(one(t.raw,'SELECT state FROM prospect_followup_attempts WHERE id=?',attempt.id).state,'accepted');assert.equal(one(t.raw,'SELECT next_message FROM prospect_followup_sequences').next_message,3);});

test('a crash receipt with no exact provider match becomes durably uncertain and is not polled or resent blindly',async c=>{const t=await fixture(c);await activate(t);const attempt=one(t.raw,"SELECT * FROM prospect_followup_attempts WHERE message_number=2");run(t.raw,"UPDATE prospect_followup_attempts SET state='submitting',attempted_at=?,account_email='hello@example.test',updated_at=? WHERE id=?",attempt.scheduled_at,attempt.scheduled_at,attempt.id);t.env.BLOOMOPS_GOOGLE_FOLLOWUP_SCHEDULER_ENABLED='true';t.env.BLOOMOPS_GOOGLE_FOLLOWUP_SESSION_ID=t.session;let requests=0;const missing=async()=>{requests++;return Response.json({messages:[]});};const first=await runScheduledProspectFollowup(t.db,t.env,{fetcher:missing,clock:()=>due(t)});assert.deepEqual(first,{checked:true,accepted:false});assert.equal(requests,1);assert.equal(one(t.raw,'SELECT state FROM prospect_followup_attempts WHERE id=?',attempt.id).state,'uncertain');assert.deepEqual({...one(t.raw,'SELECT state,last_reason FROM prospect_followup_sequences')},{state:'failed',last_reason:'provider_outcome_uncertain'});assert.deepEqual(await runScheduledProspectFollowup(t.db,t.env,{fetcher:missing,clock:()=>due(t)}),{processed:false});assert.equal(requests,1);});

test('manual receipt recovery records a raced reply or conversion without reopening outreach',async c=>{for(const state of ['held','stopped']){const t=await fixture(c);await activate(t);const attempt=one(t.raw,"SELECT * FROM prospect_followup_attempts WHERE message_number=2"),sequence=one(t.raw,'SELECT id FROM prospect_followup_sequences');run(t.raw,"UPDATE prospect_followup_attempts SET state='submitting',attempted_at=?,account_email='hello@example.test',updated_at=? WHERE id=?",attempt.scheduled_at,attempt.scheduled_at,attempt.id);run(t.raw,"UPDATE prospect_followup_sequences SET state=?,last_reason=?,updated_at=? WHERE id=?",state,state==='held'?'reply_recorded':'converted',attempt.scheduled_at,sequence.id);let sends=0;const found=async(url)=>{const u=new URL(url);if(u.pathname.endsWith('/messages/send')){sends++;throw Error('must not send');}if(u.searchParams.has('q'))return Response.json({messages:[{id:'race-'+state,threadId:'sent-thread'}]});return Response.json({id:'race-'+state,threadId:'sent-thread',labelIds:['SENT'],payload:{headers:[{name:'Message-ID',value:attempt.message_id},{name:'From',value:'Ary, Bloomwired <hello@example.test>'},{name:'To',value:t.fields.recipient},{name:'In-Reply-To',value:rfc(t)},{name:'References',value:rfc(t)}]}});};const result=await reconcileProspectFollowup(t.db,t.actor,t.env,t.session,{workspaceId:'fresh',prospectId:t.id,sequenceId:sequence.id},{fetcher:found,clock:()=>due(t)});assert.ok(result.accepted);assert.equal(sends,0);assert.equal(one(t.raw,'SELECT state FROM prospect_followup_attempts WHERE id=?',attempt.id).state,'accepted');assert.equal(one(t.raw,'SELECT state FROM prospect_followup_sequences').state,state);}});

test('a fresh complete metadata check sends exact approved content once in the original thread and Results counts provider acceptance',async c=>{const t=await fixture(c);await activate(t);const sequence=one(t.raw,'SELECT id FROM prospect_followup_sequences'),p=provider(t),input={workspaceId:'fresh',prospectId:t.id,sequenceId:sequence.id},now=due(t);const out=await Promise.all([runProspectFollowup(t.db,t.actor,t.env,t.session,input,{fetcher:p.fetcher,clock:()=>now}),runProspectFollowup(t.db,t.actor,t.env,t.session,input,{fetcher:p.fetcher,clock:()=>now})]);assert.equal(out.filter(x=>x.accepted).length,1,JSON.stringify({out,reply:one(t.raw,'SELECT * FROM prospect_reply_states'),sequence:one(t.raw,'SELECT * FROM prospect_followup_sequences'),attempt:one(t.raw,'SELECT * FROM prospect_followup_attempts WHERE message_number=2'),reads:p.reads,sends:p.sends}));assert.equal(p.reads,1);assert.equal(p.sends,1);assert.equal(one(t.raw,'SELECT state FROM prospect_followup_attempts WHERE message_number=2').state,'accepted');assert.equal(one(t.raw,'SELECT next_message FROM prospect_followup_sequences').next_message,3);const results=await getProspectResults(t.db,t.actor,{now:new Date(now.getTime()+60000)});assert.equal(results.peopleContacted,1);assert.equal(results.emailsSent,2);});

test('the approved third message completes the sequence without exceeding three total cold emails',async c=>{const t=await fixture(c);await activate(t);const sequence=one(t.raw,'SELECT id FROM prospect_followup_sequences'),p=provider(t),input={workspaceId:'fresh',prospectId:t.id,sequenceId:sequence.id};let now=due(t);assert.ok((await runProspectFollowup(t.db,t.actor,t.env,t.session,input,{fetcher:p.fetcher,clock:()=>now})).accepted);now=due(t);const result=await runProspectFollowup(t.db,t.actor,t.env,t.session,input,{fetcher:p.fetcher,clock:()=>now});assert.equal(result.state,'complete');assert.equal(p.reads,2);assert.equal(p.sends,2);assert.equal(one(t.raw,'SELECT state FROM prospect_followup_sequences').state,'complete');assert.equal(one(t.raw,"SELECT count(*) n FROM prospect_followup_attempts WHERE state='accepted'").n,2);const totals=await getProspectResults(t.db,t.actor,{now:new Date(now.getTime()+60000)});assert.equal(totals.emailsSent,3);});

test('a recorded reply holds execution without provider send and reply handling cannot resume it',async c=>{const t=await fixture(c);await activate(t);const sequence=one(t.raw,'SELECT id FROM prospect_followup_sequences'),p=provider(t,{reply:true}),input={workspaceId:'fresh',prospectId:t.id,sequenceId:sequence.id},now=due(t);const result=await runProspectFollowup(t.db,t.actor,t.env,t.session,input,{fetcher:p.fetcher,clock:()=>now});assert.equal(result.state,'held');assert.equal(p.sends,0);assert.equal(one(t.raw,'SELECT last_reason FROM prospect_followup_sequences').last_reason,'reply_recorded');run(t.raw,"INSERT INTO activity_events(id,workspace_id,event_type,subject_type,subject_id,actor_membership_id,actor_user_id,metadata_json,occurred_at,created_at) VALUES('handled','fresh','PROSPECT_REPLY_RESOLVED','prospect',?,'dest','owner','{\"note\":\"Reviewed\"}',?,?)",t.id,now.toISOString(),now.toISOString());assert.equal((await runProspectFollowup(t.db,t.actor,t.env,t.session,input,{fetcher:p.fetcher,clock:()=>new Date(now.getTime()+60000)})).conflict,true);assert.equal(p.sends,0);});

test('incomplete required metadata holds the sequence without sending',async c=>{const t=await fixture(c);await activate(t);const sequence=one(t.raw,'SELECT id FROM prospect_followup_sequences'),now=due(t);let reads=0,sends=0;const fetcher=async(url)=>{if(new URL(url).pathname.endsWith('/messages/send')){sends++;return Response.json({id:'must-not-send'});}reads++;return Response.json({id:'sent-thread',messages:[{...anchor(t),payload:{headers:[]}}]});};const result=await runProspectFollowup(t.db,t.actor,t.env,t.session,{workspaceId:'fresh',prospectId:t.id,sequenceId:sequence.id},{fetcher,clock:()=>now});assert.equal(result.state,'held');assert.equal(reads,1);assert.equal(sends,0);assert.notEqual(one(t.raw,'SELECT last_reason FROM prospect_followup_sequences').last_reason,null);assert.equal(one(t.raw,'SELECT state FROM prospect_followup_attempts WHERE message_number=2').state,'scheduled');});

test('conversion permanently stops a scheduled sequence without changing its evidence',async c=>{const t=await fixture(c);await activate(t);run(t.raw,"INSERT INTO bloomops_clients(id,workspace_id,name,slug) VALUES('client','fresh','Converted client','converted-client')");run(t.raw,"INSERT INTO service_types(id,workspace_id,name,slug) VALUES('service','fresh','Synthetic service','synthetic-service')");run(t.raw,"INSERT INTO service_engagements(id,workspace_id,client_id,service_type_id,scope_notes) VALUES('engagement','fresh','client','service','Synthetic scope')");run(t.raw,"INSERT INTO prospect_conversions(id,workspace_id,prospect_id,request_id,request_hash,profile_revision,review_hash,client_id,client_name,service_engagement_id,service_type_id,service_name,scope_notes,recipient_emails_json,converted_by_membership_id) VALUES('conversion','fresh',?,'request',?,2,?,'client','Converted client','engagement','service','Synthetic service','Synthetic scope',?,'dest')",t.id,'a'.repeat(64),'b'.repeat(64),JSON.stringify([t.fields.recipient]));const sequence=one(t.raw,'SELECT state,last_reason FROM prospect_followup_sequences');assert.equal(sequence.state,'stopped');assert.equal(sequence.last_reason,'converted');assert.deepEqual(all(t.raw,'SELECT message_number,state FROM prospect_followup_attempts ORDER BY message_number').map(row=>({...row})),[{message_number:2,state:'scheduled'},{message_number:3,state:'scheduled'}]);});

test('ambiguous provider outcome locks the attempt and exact reconciliation records acceptance without resending',async c=>{const t=await fixture(c);await activate(t);const sequence=one(t.raw,'SELECT id FROM prospect_followup_sequences'),p=provider(t,{uncertain:true}),input={workspaceId:'fresh',prospectId:t.id,sequenceId:sequence.id},now=due(t);const result=await runProspectFollowup(t.db,t.actor,t.env,t.session,input,{fetcher:p.fetcher,clock:()=>now});assert.equal(result.state,'failed');assert.equal(p.sends,1);const attempt=one(t.raw,'SELECT * FROM prospect_followup_attempts WHERE message_number=2'),reconcile=async url=>{const u=new URL(url);if(u.searchParams.has('q'))return Response.json({messages:[{id:'recovered',threadId:'sent-thread'}]});return Response.json({id:'recovered',threadId:'sent-thread',labelIds:['SENT'],payload:{headers:[{name:'Message-ID',value:attempt.message_id},{name:'From',value:'Ary, Bloomwired <hello@example.test>'},{name:'To',value:t.fields.recipient},{name:'In-Reply-To',value:rfc(t)},{name:'References',value:rfc(t)}]}});};assert.ok((await reconcileProspectFollowup(t.db,t.actor,t.env,t.session,input,{fetcher:reconcile,clock:()=>new Date(now.getTime()+60000)})).accepted);assert.equal(one(t.raw,'SELECT state FROM prospect_followup_attempts WHERE message_number=2').state,'accepted');assert.equal(one(t.raw,'SELECT state FROM prospect_followup_sequences').state,'running');});

test('reconciling an uncertain final message completes without resending',async c=>{const t=await fixture(c,{followUp3:null});await activate(t);const sequence=one(t.raw,'SELECT id FROM prospect_followup_sequences'),p=provider(t,{uncertain:true}),input={workspaceId:'fresh',prospectId:t.id,sequenceId:sequence.id},now=due(t);assert.equal((await runProspectFollowup(t.db,t.actor,t.env,t.session,input,{fetcher:p.fetcher,clock:()=>now})).state,'failed');const attempt=one(t.raw,'SELECT * FROM prospect_followup_attempts WHERE message_number=2'),reconcile=async url=>new URL(url).searchParams.has('q')?Response.json({messages:[{id:'recovered-final',threadId:'sent-thread'}]}):Response.json({id:'recovered-final',threadId:'sent-thread',labelIds:['SENT'],payload:{headers:[{name:'Message-ID',value:attempt.message_id},{name:'From',value:'Ary, Bloomwired <hello@example.test>'},{name:'To',value:t.fields.recipient},{name:'In-Reply-To',value:rfc(t)},{name:'References',value:rfc(t)}]}});const result=await reconcileProspectFollowup(t.db,t.actor,t.env,t.session,input,{fetcher:reconcile,clock:()=>new Date(now.getTime()+60000)});assert.ok(result.accepted);assert.equal(p.sends,1);assert.equal(one(t.raw,'SELECT state FROM prospect_followup_sequences').state,'complete');});

test('a conversion can strengthen a held or failed sequence to a permanent stop',async c=>{for(const state of ['held','failed']){const t=await fixture(c);await activate(t);run(t.raw,"UPDATE prospect_followup_sequences SET state=?,last_reason='synthetic',updated_at='2026-09-17T00:00:00.000Z'",state);run(t.raw,"INSERT INTO bloomops_clients(id,workspace_id,name,slug) VALUES(?,?,?,?)",'client-'+state,'fresh','Converted client',state+'-client');run(t.raw,"INSERT INTO service_types(id,workspace_id,name,slug) VALUES(?,?,?,?)",'service-'+state,'fresh','Synthetic service',state+'-service');run(t.raw,"INSERT INTO service_engagements(id,workspace_id,client_id,service_type_id,scope_notes) VALUES(?,?,?,?,?)",'engagement-'+state,'fresh','client-'+state,'service-'+state,'Synthetic scope');run(t.raw,"INSERT INTO prospect_conversions(id,workspace_id,prospect_id,request_id,request_hash,profile_revision,review_hash,client_id,client_name,service_engagement_id,service_type_id,service_name,scope_notes,recipient_emails_json,converted_by_membership_id) VALUES(?,'fresh',?,?,?,2,?,?,?, ?,?,'Synthetic service','Synthetic scope',?,'dest')",'conversion-'+state,t.id,'request-'+state,'a'.repeat(64),'b'.repeat(64),'client-'+state,'Converted client','engagement-'+state,'service-'+state,JSON.stringify([t.fields.recipient]));assert.deepEqual({...one(t.raw,'SELECT state,last_reason FROM prospect_followup_sequences')},{state:'stopped',last_reason:'converted'});}});

test('recorded stops, changed approval and revoked authority prevent sends',async c=>{for(const mutation of ["UPDATE prospect_reply_states SET revision=revision+1,hold_state='stopped',stop_reason='declined',stop_note='No',stopped_by_membership_id='dest',stopped_at='2026-09-17T00:00:00.000Z',updated_at='2026-09-17T00:00:00.000Z'","UPDATE prospect_outreach_drafts SET revision=revision+1","UPDATE workspace_memberships SET status='suspended' WHERE id='dest'"]){const t=await fixture(c);await activate(t);run(t.raw,mutation);const p=provider(t),sequence=one(t.raw,'SELECT id FROM prospect_followup_sequences'),now=due(t);const result=await runProspectFollowup(t.db,t.actor,t.env,t.session,{workspaceId:'fresh',prospectId:t.id,sequenceId:sequence.id},{fetcher:p.fetcher,clock:()=>now});assert.equal(p.sends,0);assert.ok(result?.state||result===null||result?.conflict||result?.waiting);}});
