import {test} from 'node:test';
import assert from 'node:assert/strict';
import {testDb,run,all} from './_bloomops-db.mjs';
import {createProspect} from '../lib/bloomops/prospects.mjs';
import {getConversionOptions,previewProspectConversion} from '../lib/bloomops/prospect-conversion-preview.mjs';
import {onboardingDefaultStatements} from '../lib/bloomops/onboarding-defaults.mjs';
async function fixture(c){const t=testDb();c.after(()=>t.raw.close());for(const id of ['w','foreign'])run(t.raw,"INSERT INTO workspaces(id,name,slug,purpose) VALUES(?,?,?,'prospecting')",id,id,id);run(t.raw,"INSERT INTO user(id,name,email) VALUES('owner','Owner','owner@example.test')");run(t.raw,"INSERT INTO workspace_memberships(id,workspace_id,user_id,role,status) VALUES('m','w','owner','owner','active')");t.actor={workspaceId:'w',membershipId:'m',userId:'owner',role:'owner',status:'active',scope:{kind:'workspace'}};const made=await createProspect(t.db,{actor:t.actor,input:{workspaceId:'w',requestId:crypto.randomUUID(),fields:{businessName:'Cedar House',personName:'Maya Reed',publicEmail:'maya@example.test'}}});assert.ok(made.ok);t.id=made.prospectId;
 for(const ws of ['w','foreign']){run(t.raw,'INSERT INTO service_types(id,workspace_id,name,slug) VALUES(?,?,?,?)',ws+'-service',ws,'Kajabi','kajabi');run(t.raw,'INSERT INTO bloomops_clients(id,workspace_id,name,slug) VALUES(?,?,?,?)',ws+'-client',ws,'Cedar client',ws+'-client');}
 run(t.raw,"INSERT INTO client_contacts(id,workspace_id,client_id,name,email,is_primary) VALUES('primary','w','w-client','Existing Person','existing@example.test',1)");for(const q of onboardingDefaultStatements({workspaceSlug:'w'}))run(t.raw,q);
 t.input={workspaceId:'w',mode:'new',serviceTypeId:'w-service',packageName:'Course launch',scopeNotes:'Refresh the course page and onboarding flow.'};t.preview=(patch={},actor=t.actor)=>previewProspectConversion(t.db,actor,t.id,{...t.input,...patch});t.options=(q={},actor=t.actor)=>getConversionOptions(t.db,actor,t.id,q);t.snapshot=()=>all(t.raw,"SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'").map(({name})=>[name,all(t.raw,'SELECT * FROM "'+name+'"')]);return t;}
test('new-client preview compiles canonical templates without changing any table',async c=>{const t=await fixture(c),before=t.snapshot(),result=await t.preview();assert.ok(result.ok);assert.equal(result.previewOnly,true);assert.equal(result.client.id,null);assert.equal(result.client.name,'Cedar House');assert.equal(result.contact.email,'maya@example.test');assert.equal(result.onboarding.status,'compiled');assert.ok(result.onboarding.steps>3);assert.deepEqual(result.issues,[]);assert.doesNotMatch(JSON.stringify(result),/definitionJson|preview-service|preview-client|token|invitationId/);assert.deepEqual(t.snapshot(),before);});
test('existing-client contact is authoritative and an open service is identified without copying scope',async c=>{const t=await fixture(c);run(t.raw,"INSERT INTO service_engagements(id,workspace_id,client_id,service_type_id,scope_notes) VALUES('eng','w','w-client','w-service','Existing scope')");const before=t.snapshot(),result=await t.preview({mode:'existing',clientId:'w-client'});assert.ok(result.ok);assert.equal(result.contact.name,'Existing Person');assert.equal(result.contact.email,'existing@example.test');assert.equal(result.service.existing,true);assert.equal(result.service.scopeNotes,t.input.scopeNotes);assert.deepEqual(t.snapshot(),before);});
test('client and service options are current-workspace only and paginated before display',async c=>{const t=await fixture(c);for(let i=0;i<23;i++){run(t.raw,'INSERT INTO bloomops_clients(id,workspace_id,name,slug) VALUES(?,?,?,?)','client-'+i,'w','Additional '+i,'client-'+i);run(t.raw,'INSERT INTO service_types(id,workspace_id,name,slug) VALUES(?,?,?,?)','type-'+i,'w','Additional '+i,'type-'+i);}const a=await t.options(),b=await t.options({clientPage:'2',servicePage:'2'});assert.equal(a.clients.length,20);assert.equal(a.services.length,20);assert.ok(a.moreClients&&a.moreServices);assert.equal(b.clients.length,4);assert.equal(b.services.length,4);assert.equal(new Set([...a.clients,...b.clients].map(x=>x.id)).size,24);assert.doesNotMatch(JSON.stringify(a),/foreign/);assert.equal((await t.options({clientQuery:'Cedar'})).clients.length,1);assert.equal((await t.options({clientQuery:'%',serviceQuery:'_'})).clients.length,0);});
for(const role of ['project_manager','team_member','client'])test(role+' cannot inspect handoff data',async c=>{const t=await fixture(c);run(t.raw,'UPDATE workspace_memberships SET role=? WHERE id=?',role,'m');const actor={...t.actor,role};assert.equal((await t.options({},actor)).reason,'not_found');assert.equal((await t.preview({},actor)).reason,'not_found');});
for(const change of ["UPDATE workspace_memberships SET status='suspended' WHERE id='m'","UPDATE workspace_memberships SET role='team_member' WHERE id='m'","UPDATE workspaces SET status='archived' WHERE id='w'"])test('stale actor denied: '+change,async c=>{const t=await fixture(c);run(t.raw,change);assert.equal((await t.options()).reason,'not_found');assert.equal((await t.preview()).reason,'not_found');});
test('foreign client/service and missing prospect are indistinguishable',async c=>{const t=await fixture(c);for(const patch of [{mode:'existing',clientId:'foreign-client'},{mode:'existing',clientId:'missing'},{serviceTypeId:'foreign-service'},{serviceTypeId:'missing'}])assert.equal((await t.preview(patch)).reason,'not_found');assert.equal((await getConversionOptions(t.db,t.actor,crypto.randomUUID())).reason,'not_found');});
test('strict inputs reject hidden commands, ambiguous selection and oversized fields',async c=>{const t=await fixture(c);for(const q of [{send:true},{clientPage:0},{servicePage:'1.5'},{clientQuery:'x'.repeat(121)},{serviceQuery:[]}])assert.equal((await t.options(q)).reason,'invalid');for(const patch of [{workspaceId:'foreign'},{mode:''},{mode:'new',clientId:'w-client'},{mode:'existing'},{serviceTypeId:[]},{scopeNotes:''},{scopeNotes:'x'.repeat(2001)},{packageName:'x'.repeat(121)},{scopeNotes:{}},{sendInvitation:true},{activate:true}])assert.equal((await t.preview(patch)).reason,'invalid');});
test('missing contact and missing publication are clearly unresolved',async c=>{const t=await fixture(c);run(t.raw,"UPDATE client_contacts SET email=NULL WHERE id='primary'");run(t.raw,"UPDATE templates SET active=0 WHERE slug='kajabi'");const result=await t.preview({mode:'existing',clientId:'w-client'});assert.equal(result.onboarding.status,'missing_template');assert.deepEqual(result.issues.map(x=>x.code).sort(),['contact_email','template_missing']);});
test('inactive services are never selectable even by a saved ID',async c=>{const t=await fixture(c);run(t.raw,"UPDATE service_types SET active=0 WHERE id='w-service'");assert.equal((await t.options()).services.length,0);assert.equal((await t.preview()).reason,'not_found');});
test('existing lifecycle and open onboarding cannot masquerade as a new activation',async c=>{const t=await fixture(c);run(t.raw,"UPDATE bloomops_clients SET relationship_status='active' WHERE id='w-client'");run(t.raw,"INSERT INTO onboarding_instances(id,workspace_id,client_id,status) VALUES('started','w','w-client','not_started')");const result=await t.preview({mode:'existing',clientId:'w-client'});assert.equal(result.onboarding.status,'not_checked');assert.deepEqual(result.issues.map(x=>x.code).sort(),['client_lifecycle','onboarding_exists']);});
test('custom service truthfully previews common-only onboarding',async c=>{const t=await fixture(c);run(t.raw,"INSERT INTO service_types(id,workspace_id,name,slug) VALUES('custom','w','Custom service','custom')");const result=await t.preview({serviceTypeId:'custom'});assert.equal(result.service.serviceSpecific,false);assert.deepEqual(result.onboarding.categories,['common']);assert.equal(result.onboarding.steps,3);});
test('revocation while reading templates discards the entire preview',async c=>{const t=await fixture(c),select=t.db.select.bind(t.db);let count=0;t.db.select=(...args)=>{if(++count===4)run(t.raw,"UPDATE workspace_memberships SET status='suspended' WHERE id='m'");return select(...args);};assert.equal((await t.preview()).reason,'not_found');});
test('revocation while searching discards the options and prospect',async c=>{const t=await fixture(c),select=t.db.select.bind(t.db);let count=0;t.db.select=(...args)=>{if(++count===3)run(t.raw,"UPDATE workspace_memberships SET status='suspended' WHERE id='m'");return select(...args);};assert.equal((await t.options()).reason,'not_found');});
test('a prospect edit during preparation makes the preview conflict',async c=>{const t=await fixture(c),select=t.db.select.bind(t.db);let count=0;t.db.select=(...args)=>{if(++count===3)run(t.raw,'UPDATE bloomops_prospects SET revision=revision+1,business_name=? WHERE id=?','Changed name',t.id);return select(...args);};assert.equal((await t.preview()).reason,'conflict');});
test('invalid published content is not presented as a usable onboarding plan',async c=>{const t=await fixture(c);run(t.raw,"UPDATE template_versions SET status='retired' WHERE template_id IN (SELECT id FROM templates WHERE workspace_id='w' AND slug='kajabi')");run(t.raw,"INSERT INTO template_versions(workspace_id,template_id,version_number,status,definition_json,definition_hash,published_at) SELECT 'w',id,2,'published','{}',?,CURRENT_TIMESTAMP FROM templates WHERE workspace_id='w' AND slug='kajabi'",'0'.repeat(64));const result=await t.preview();assert.equal(result.onboarding.status,'unavailable');assert.ok(result.issues.some(x=>x.code==='template_invalid'));});
test('overlong prospect identity fields remain unresolved instead of silently truncating',async c=>{const t=await fixture(c);run(t.raw,'UPDATE bloomops_prospects SET revision=revision+1,business_name=?,person_name=? WHERE id=?','N'.repeat(121),'P'.repeat(121),t.id);const result=await t.preview();assert.ok(result.issues.some(x=>x.code==='client_name'));assert.ok(result.issues.some(x=>x.code==='contact_name'));});
for(const at of [1,2])for(const mutation of ["UPDATE workspace_memberships SET status='suspended' WHERE id='m'","UPDATE workspace_memberships SET role='team_member' WHERE id='m'"])test('template source SQL returns no rows after revocation at read '+at+': '+mutation,async c=>{const t=await fixture(c),prepare=t.d1.prepare.bind(t.d1),counts=[];let reads=0;t.d1.prepare=sql=>{const statement=prepare(sql);if(!/from "template_versions"/i.test(sql))return statement;const wrap=stmt=>({...stmt,bind:(...values)=>wrap(stmt.bind(...values)),raw:async()=>{if(++reads===at)run(t.raw,mutation);const rows=await stmt.raw();counts.push(rows.length);return rows;}});return wrap(statement);};assert.equal((await t.preview()).reason,'not_found');assert.equal(counts.length,2);assert.deepEqual(counts.slice(0,at-1),Array(at-1).fill(1));assert.deepEqual(counts.slice(at-1),Array(3-at).fill(0));});
test('duplicate names retain unique canonical references in choices and the selected preview',async c=>{const t=await fixture(c);run(t.raw,"INSERT INTO bloomops_clients(id,workspace_id,name,slug) VALUES('second-client','w','Cedar client','cedar-second')");run(t.raw,"INSERT INTO service_types(id,workspace_id,name,slug) VALUES('second-service','w','Kajabi','kajabi-second')");const options=await t.options();assert.equal(options.clients.length,2);assert.equal(options.services.length,2);assert.equal(new Set(options.clients.map(x=>x.slug)).size,2);assert.equal(new Set(options.services.map(x=>x.slug)).size,2);assert.ok(options.clients.every(x=>x.name==='Cedar client'));assert.ok(options.services.every(x=>x.name==='Kajabi'));const result=await t.preview({mode:'existing',clientId:'second-client',serviceTypeId:'second-service'});assert.equal(result.client.slug,'cedar-second');assert.equal(result.service.slug,'kajabi-second');});
