import {test} from 'node:test';
import assert from 'node:assert/strict';
import {deliveryMime,submitGoogleIntroduction,findGoogleIntroduction} from '../lib/bloomops/prospect-delivery-provider.mjs';
const id='12345678-1234-1234-1234-123456789abc',receipt={id,messageId:'<bloomsi-'+id+'@bloomsi.invalid>'};
const snapshot={sender:{provider:'google_workspace',email:'hello@example.test',displayName:'Ary, Bloomwired'},draft:{recipient:'inbox@example.test',timeZone:'Europe/London',subject:'A clear introduction',intro:'A long sentence — café 🌷 & <script> safely appears as text.\n\nSecond paragraph.',followUp2:'Second',followUp3:'Third'}};
test('stable MIME identity, single recipient, Unicode QP and plain/escaped HTML use reviewed intro only',()=>{const mime=deliveryMime(receipt,snapshot);assert.equal(mime,deliveryMime(receipt,snapshot));assert.equal(mime.split('Message-ID:').length,2);assert.ok(mime.includes('From: "Ary, Bloomwired" <hello@example.test>'));assert.ok(mime.includes('To: inbox@example.test'));assert.ok(mime.includes('multipart/alternative'));assert.ok(mime.includes('&lt;script&gt;'));assert.ok(!mime.includes('\r\nBcc:'));assert.ok(!mime.includes('Third'));});
test('MIME rejects header/boundary injection and invalid approved fields',()=>{for(const [r,s] of [[{...receipt,id:'bad\r\nBcc: victim'},snapshot],[{...receipt,messageId:'bad\r\nBcc: victim'},snapshot],[receipt,{...snapshot,draft:{...snapshot.draft,subject:'bad\r\nBcc: victim'}}],[receipt,{...snapshot,sender:{...snapshot.sender,displayName:'bad\r\n'}}],[receipt,{...snapshot,draft:{...snapshot.draft,recipient:'one@example.test, two@example.test'}}]])assert.throws(()=>deliveryMime(r,s));});
test('all redirect classes refuse credential forwarding for send and recovery',async()=>{for(const status of [301,302,303,307,308]){let calls=0;const fetcher=async(url,options)=>{calls++;assert.equal(options.redirect,'manual');assert.ok(options.signal);return new Response(null,{status,headers:{location:'https://foreign.example.test/collect'}});};assert.deepEqual(await submitGoogleIntroduction('synthetic',deliveryMime(receipt,snapshot),{fetcher}),{uncertain:true});assert.equal(calls,1);assert.deepEqual(await findGoogleIntroduction('synthetic',receipt,snapshot,{fetcher}),{uncertain:true});assert.equal(calls,2);}});
test('unsafe IDs, oversized and arbitrary error content remain opaque uncertainty',async()=>{for(const response of [()=>Response.json({id:'../unsafe',threadId:'thread'}),()=>Response.json({id:'message',threadId:'x'.repeat(201)}),()=>new Response('x'.repeat(65537)),()=>new Response('sensitive error',{status:401}),()=>new Response('{broken')])assert.deepEqual(await submitGoogleIntroduction('synthetic',deliveryMime(receipt,snapshot),{fetcher:async()=>response()}),{uncertain:true});});
