import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {sourceFixture} from './_prospect-source-fixture.mjs';
import {run,one,all} from './_bloomops-db.mjs';
import {createProspect,updateProspect} from '../lib/bloomops/prospects.mjs';
import {getProspectSender,saveProspectSender,getProspectOutreach,saveProspectOutreach,approveProspectOutreach,prospectOutreachOverview} from '../lib/bloomops/prospect-outreach.mjs';
import {previewSkillResult,applySkillResult} from '../lib/bloomops/prospect-skill-results.mjs';
const fields={recipient:'hello@fern.example.com',timeZone:'Australia/Melbourne',subject:'A thought on your course page',intro:'Hi Maya, may I share a short outline?',followUp2:'Would an outline be useful?',followUp3:'Happy to leave this here.'};
const sender=(revision=0,email='hello@bloomwired.io')=>({workspaceId:'fresh',expectedRevision:revision,fields:{provider:'google_workspace',email,displayName:'Ary'}});
async function setup(c){const t=await sourceFixture(c),r=await createProspect(t.db,{actor:t.actor,input:{workspaceId:'fresh',requestId:crypto.randomUUID(),fields:{businessName:'Fern Studio',website:'https://fern.example.com',publicEmail:fields.recipient,timeZone:fields.timeZone,fit:'strong',observedFacts:'Enrol opens a course checkout.',evidenceDate:'2026-09-12',evidenceTarget:'https://fern.example.com/course',proposedWork:'Clarify the course options.',draftSubject:fields.subject,draftBody:fields.intro}}});assert.ok(r.ok);t.id=r.prospectId;const checked=await updateProspect(t.db,{actor:t.actor,id:t.id,input:{workspaceId:'fresh',expectedRevision:1,fields:{publicEmail:fields.recipient},sources:{publicEmail:{url:'https://fern.example.com/contact',checked:true}}}});assert.ok(checked.ok);return t;}
const state=t=>JSON.stringify(['bloomops_prospects','prospect_field_sources','prospect_senders','prospect_outreach_drafts','prospect_outreach_approvals','activity_events','send_events'].map(table=>all(t.raw,'SELECT * FROM '+table+' ORDER BY rowid')));
async function draftInput(t,patch={}){const data=await getProspectOutreach(t.db,t.actor,t.id);return {workspaceId:'fresh',prospectId:t.id,expectedRevision:data.draft?.revision||0,expectedProfileRevision:data.profile.revision,expectedSenderRevision:data.sender?.revision||0,sourceResultId:null,fields:{...fields},...patch};}
async function approval(t){const d=await getProspectOutreach(t.db,t.actor,t.id);return {workspaceId:'fresh',prospectId:t.id,expectedRevision:d.draft.revision,expectedProfileRevision:d.profile.revision,expectedSenderRevision:d.sender.revision,reviewed:true};}
async function ready(t){assert.ok((await saveProspectSender(t.db,t.actor,sender())).saved);assert.ok((await saveProspectOutreach(t.db,t.actor,await draftInput(t))).saved);return approval(t);}
const count=(t,table)=>one(t.raw,'SELECT count(*) n FROM '+table).n;
test('fresh workspace has no sender or urgent drafts; profile values seed an unsaved draft',async c=>{const t=await setup(c),before=state(t),d=await getProspectOutreach(t.db,t.actor,t.id);assert.equal(d.sender,null);assert.equal(d.draft,null);assert.equal(d.seed.intro,fields.intro);assert.equal(d.seed.followUp2,null);assert.equal(d.approved,false);assert.deepEqual((await prospectOutreachOverview(t.db,t.actor)).rows,[]);assert.equal(state(t),before);});
test('sender saves normalized identity only; retry and concurrent creation produce one event',async c=>{const t=await setup(c),input=sender(0,' HELLO@BLOOMWIRED.IO '),results=await Promise.all([saveProspectSender(t.db,t.actor,input),saveProspectSender(t.db,t.actor,input)]);assert.ok(results.every(r=>r.saved),JSON.stringify(results));assert.equal((await getProspectSender(t.db,t.actor)).sender.email,'hello@bloomwired.io');assert.equal(count(t,'prospect_senders'),1);assert.equal(one(t.raw,"SELECT count(*) n FROM activity_events WHERE event_type='PROSPECT_SENDER_UPDATED'").n,1);const before=state(t);assert.ok((await saveProspectSender(t.db,t.actor,input)).unchanged);assert.equal(state(t),before);assert.equal(count(t,'send_events'),0);});
test('sender rejects unsupported provider, invalid address, control characters and stale edits',async c=>{const t=await setup(c);await saveProspectSender(t.db,t.actor,sender());for(const patch of [{provider:'smtp'},{email:'invalid'},{displayName:'Ary\nBcc: x'},{email:null},{extra:true}]){const before=state(t);assert.ok((await saveProspectSender(t.db,t.actor,{...sender(1),fields:{...sender().fields,...patch}})).invalid);assert.equal(state(t),before);}assert.ok((await saveProspectSender(t.db,t.actor,sender(0,'new@example.com'))).conflict);assert.ok((await saveProspectSender(t.db,t.actor,sender(1,'new@example.com'))).saved);});
test('incomplete draft can be saved but cannot be approved; unknowns are not fabricated',async c=>{const t=await setup(c);await saveProspectSender(t.db,t.actor,sender());assert.ok((await saveProspectOutreach(t.db,t.actor,await draftInput(t,{fields:{...fields,followUp2:null,timeZone:null}}))).saved);const before=state(t),a=await approveProspectOutreach(t.db,t.actor,await approval(t));assert.ok(a.invalid);assert.equal(state(t),before);assert.equal((await prospectOutreachOverview(t.db,t.actor)).rows[0].approved,false);});
test('complete reviewed draft records one immutable snapshot and event; retries never send',async c=>{const t=await setup(c),a=await ready(t);assert.equal((await getProspectOutreach(t.db,t.actor,t.id)).blockers.length,0);assert.ok((await approveProspectOutreach(t.db,t.actor,a)).approved);assert.ok((await approveProspectOutreach(t.db,t.actor,a)).unchanged);assert.equal(count(t,'prospect_outreach_approvals'),1);assert.equal(one(t.raw,"SELECT count(*) n FROM activity_events WHERE event_type='PROSPECT_DRAFT_APPROVED'").n,1);const row=one(t.raw,'SELECT * FROM prospect_outreach_approvals'),snap=JSON.parse(row.snapshot_json);assert.equal(snap.sender.email,'hello@bloomwired.io');assert.deepEqual(snap.draft,fields);assert.equal(snap.profile.observedFacts,'Enrol opens a course checkout.');assert.throws(()=>run(t.raw,"UPDATE prospect_outreach_approvals SET snapshot_json='{}'"),/immutable/);assert.throws(()=>run(t.raw,'DELETE FROM prospect_outreach_approvals'),/immutable/);assert.deepEqual(all(t.raw,'PRAGMA foreign_key_check'),[]);assert.equal(count(t,'send_events'),0);assert.equal((await prospectOutreachOverview(t.db,t.actor)).rows[0].approved,true);});
test('human review acknowledgement is required even when every stored field is complete',async c=>{const t=await setup(c),a=await ready(t),before=state(t);for(const reviewed of [false,null,'true',1])assert.ok((await approveProspectOutreach(t.db,t.actor,{...a,reviewed})).invalid);assert.equal(state(t),before);});
test('fit, current checked recipient and dated evidence/offer each gate approval',async c=>{for(const [column,value] of [['fit','unknown'],['public_email','other@example.com'],['observed_facts',null],['evidence_date',null],['evidence_target',null],['proposed_work',null]]){const t=await setup(c);await ready(t);run(t.raw,`UPDATE bloomops_prospects SET ${column}=?,revision=revision+1 WHERE id=?`,value,t.id);await saveProspectOutreach(t.db,t.actor,await draftInput(t));const before=state(t);assert.ok((await approveProspectOutreach(t.db,t.actor,await approval(t))).invalid,column);assert.equal(state(t),before);}});
test('unverified contact source blocks approval even if the public email matches',async c=>{const t=await setup(c);await ready(t);run(t.raw,"UPDATE prospect_field_sources SET verification='unverified',checked_at=NULL WHERE field_key='publicEmail'");assert.ok((await approveProspectOutreach(t.db,t.actor,await approval(t))).invalid);});
test('profile, sender and draft edits invalidate approval without rewriting snapshots',async c=>{for(const kind of ['profile','sender','draft']){const t=await setup(c),a=await ready(t);await approveProspectOutreach(t.db,t.actor,a);const before=JSON.stringify(all(t.raw,'SELECT * FROM prospect_outreach_approvals'));if(kind==='profile')await updateProspect(t.db,{actor:t.actor,id:t.id,input:{workspaceId:'fresh',expectedRevision:a.expectedProfileRevision,fields:{unknowns:'New uncertainty'}}});if(kind==='sender')await saveProspectSender(t.db,t.actor,sender(1,'other@example.com'));if(kind==='draft')await saveProspectOutreach(t.db,t.actor,await draftInput(t,{fields:{...fields,intro:'Changed introduction'}}));assert.equal((await getProspectOutreach(t.db,t.actor,t.id)).approved,false,kind);assert.equal((await prospectOutreachOverview(t.db,t.actor)).rows[0].approved,false,kind);assert.ok((await approveProspectOutreach(t.db,t.actor,a)).conflict);assert.equal(JSON.stringify(all(t.raw,'SELECT * FROM prospect_outreach_approvals')),before);}});
test('revoked or demoted approving member invalidates approval for another active admin',async c=>{for(const change of ["status='suspended'","role='team_member'"]){const t=await setup(c),a=await ready(t);await approveProspectOutreach(t.db,t.actor,a);run(t.raw,"INSERT INTO workspace_memberships(id,workspace_id,user_id,role,status) VALUES('reviewer','fresh','stranger','admin','active')");const actor={...t.actor,membershipId:'reviewer',userId:'stranger',role:'admin'};run(t.raw,`UPDATE workspace_memberships SET ${change},updated_at='2026-09-13T00:00:00Z' WHERE id='dest'`);assert.equal((await getProspectOutreach(t.db,actor,t.id)).approved,false);run(t.raw,"UPDATE workspace_memberships SET role='owner',status='active' WHERE id='dest'");assert.equal((await getProspectOutreach(t.db,actor,t.id)).approved,false);assert.ok((await approveProspectOutreach(t.db,actor,a)).approved);assert.equal(count(t,'prospect_outreach_approvals'),2);}});
test('concurrent approvals create one approval and one event',async c=>{const t=await setup(c),a=await ready(t),results=await Promise.all([approveProspectOutreach(t.db,t.actor,a),approveProspectOutreach(t.db,t.actor,a)]);assert.ok(results.every(r=>r.approved),JSON.stringify(results));assert.equal(count(t,'prospect_outreach_approvals'),1);assert.equal(one(t.raw,"SELECT count(*) n FROM activity_events WHERE event_type='PROSPECT_DRAFT_APPROVED'").n,1);});
test('concurrent draft saves and retry acknowledge one version; stale text cannot overwrite it',async c=>{const t=await setup(c),input=await draftInput(t),results=await Promise.all([saveProspectOutreach(t.db,t.actor,input),saveProspectOutreach(t.db,t.actor,input)]);assert.ok(results.every(r=>r.saved));assert.equal(count(t,'prospect_outreach_drafts'),1);assert.equal(JSON.parse(one(t.raw,"SELECT metadata_json FROM activity_events WHERE event_type='PROSPECT_DRAFT_SAVED'").metadata_json).draftRevision,1);assert.equal(one(t.raw,"SELECT count(*) n FROM activity_events WHERE event_type='PROSPECT_DRAFT_SAVED'").n,1);assert.ok((await saveProspectOutreach(t.db,t.actor,{...input,fields:{...fields,intro:'Stale changed'}})).conflict);assert.ok((await saveProspectOutreach(t.db,t.actor,input)).unchanged);});
test('draft validation rejects extra/missing fields, invalid timezone/email and header injection',async c=>{const t=await setup(c),input=await draftInput(t),before=state(t);for(const patch of [{timeZone:'Not/AZone'},{recipient:'not-email'},{subject:'Hello\nBcc: x'},{intro:'x'.repeat(12001)},{followUp2:[]},{extra:true}])assert.ok((await saveProspectOutreach(t.db,t.actor,{...input,fields:{...fields,...patch}})).invalid);assert.equal(state(t),before);});
test('stale sender/profile prevents draft overwrite and activity',async c=>{const t=await setup(c);await ready(t);const input=await draftInput(t);await saveProspectSender(t.db,t.actor,sender(1,'other@example.com'));const before=state(t);assert.ok((await saveProspectOutreach(t.db,t.actor,input)).conflict);assert.equal(state(t),before);});
test('denied roles, foreign workspace, operations workspace and revoked authority cannot read or write',async c=>{const t=await setup(c),a=await ready(t),d=await draftInput(t);for(const actor of [null,{...t.actor,role:'client'},{...t.actor,role:'team_member'},{...t.actor,role:'project_manager'},{...t.actor,workspaceId:'foreign',membershipId:'other'},{...t.actor,workspaceId:'source',membershipId:'src'}]){assert.equal(await getProspectSender(t.db,actor),null);assert.equal(await getProspectOutreach(t.db,actor,t.id),null);assert.equal(await prospectOutreachOverview(t.db,actor),null);assert.equal(await saveProspectSender(t.db,actor,{...sender(1),workspaceId:actor?.workspaceId||'fresh'}),null);assert.equal(await saveProspectOutreach(t.db,actor,{...d,workspaceId:actor?.workspaceId||'fresh'}),null);assert.equal(await approveProspectOutreach(t.db,actor,{...a,workspaceId:actor?.workspaceId||'fresh'}),null);}run(t.raw,"UPDATE workspace_memberships SET status='suspended' WHERE id='dest'");assert.equal(await approveProspectOutreach(t.db,t.actor,a),null);assert.equal(await getProspectOutreach(t.db,t.actor,t.id),null);assert.equal(await getProspectSender(t.db,t.actor),null);assert.equal(await prospectOutreachOverview(t.db,t.actor),null);});
test('write-time membership or version changes prevent partial writes across all mutations',async c=>{for(const kind of ['sender','draft','approve'])for(const revoke of [true,false]){const t=await setup(c),a=await ready(t),d=await draftInput(t,{fields:{...fields,intro:'An edit'}}),batch=t.db.batch.bind(t.db);let before;t.db.batch=async statements=>{if(revoke)run(t.raw,"UPDATE workspace_memberships SET status='suspended' WHERE id='dest'");else if(kind==='sender')run(t.raw,'UPDATE prospect_senders SET revision=revision+1');else run(t.raw,'UPDATE bloomops_prospects SET revision=revision+1 WHERE id=?',t.id);before=state(t);return batch(statements);};const r=kind==='sender'?await saveProspectSender(t.db,t.actor,sender(1,'new@example.com')):kind==='draft'?await saveProspectOutreach(t.db,t.actor,d):await approveProspectOutreach(t.db,t.actor,a);assert.ok(r===null||r.conflict,JSON.stringify(r));assert.equal(state(t),before,kind);}});
test('activity failure rolls back sender, draft and approval mutations',async c=>{for(const [kind,event] of [['sender','PROSPECT_SENDER_UPDATED'],['draft','PROSPECT_DRAFT_SAVED'],['approve','PROSPECT_DRAFT_APPROVED']]){const t=await setup(c),a=await ready(t),d=await draftInput(t,{fields:{...fields,intro:'An edit'}}),before=state(t);t.raw.exec(`CREATE TRIGGER fail_p3_event BEFORE INSERT ON activity_events WHEN NEW.event_type='${event}' BEGIN SELECT RAISE(ABORT,'fixture'); END;`);await assert.rejects(()=>kind==='sender'?saveProspectSender(t.db,t.actor,sender(1,'new@example.com')):kind==='draft'?saveProspectOutreach(t.db,t.actor,d):approveProspectOutreach(t.db,t.actor,a));assert.equal(state(t),before,kind);}});
test('explicit saved-result selection replaces only follow-up suggestions and retains provenance',async c=>{const t=await setup(c);await ready(t);const document=JSON.parse(readFileSync(new URL('./fixtures/prospect-skill-results.json',import.meta.url),'utf8'))[1];document.sourceContext={workspaceId:'fresh',prospectId:t.id,revision:2};const v=await previewSkillResult(t.db,t.actor,{workspaceId:'fresh',prospectId:t.id,document}),r=await applySkillResult(t.db,t.actor,{workspaceId:'fresh',prospectId:t.id,document:v.document,requestId:crypto.randomUUID(),previewHash:v.previewHash,expectedRevision:v.revision,choices:Object.fromEntries(v.changes.map(c=>[c.key,'keep']))});assert.ok(r.resultId);const d=await getProspectOutreach(t.db,t.actor,t.id,{resultId:r.resultId});assert.equal(d.seed.intro,fields.intro);assert.equal(d.seed.followUp2,document.followUps[0].body);assert.equal((await getProspectOutreach(t.db,t.actor,t.id)).seed.followUp2,fields.followUp2);assert.ok((await saveProspectOutreach(t.db,t.actor,await draftInput(t,{sourceResultId:r.resultId,fields:d.seed}))).saved);assert.equal((await getProspectOutreach(t.db,t.actor,t.id)).draft.sourceResultId,r.resultId);assert.equal(await getProspectOutreach(t.db,t.actor,'foreign',{resultId:r.resultId}),null);assert.equal(await saveProspectOutreach(t.db,t.actor,await draftInput(t,{sourceResultId:'foreign'})),null);});
test('read final guard catches profile and approver changes after draft read',async c=>{for(const mutate of [t=>run(t.raw,'UPDATE bloomops_prospects SET revision=revision+1 WHERE id=?',t.id),t=>run(t.raw,"UPDATE workspace_memberships SET updated_at='2026-09-13T00:00:00Z' WHERE id='dest'")]){const t=await setup(c);await approveProspectOutreach(t.db,t.actor,await ready(t));const select=t.db.select.bind(t.db);let calls=0;t.db.select=(...args)=>{if(++calls===4)mutate(t);return select(...args);};const result=await getProspectOutreach(t.db,t.actor,t.id);assert.ok(result.conflict||!result.approved);}});
test('Overview paginates only saved drafts with stable ordering and workspace scope',async c=>{const t=await setup(c);for(let i=0;i<22;i++){const r=await createProspect(t.db,{actor:t.actor,input:{workspaceId:'fresh',requestId:crypto.randomUUID(),fields:{businessName:'Draft '+i}}});t.id=r.prospectId;assert.ok((await saveProspectOutreach(t.db,t.actor,await draftInput(t))).saved);}const first=await prospectOutreachOverview(t.db,t.actor),second=await prospectOutreachOverview(t.db,t.actor,2);assert.equal(first.rows.length,20);assert.equal(first.more,true);assert.equal(second.rows.length,2);assert.equal(second.more,false);assert.equal(new Set([...first.rows,...second.rows].map(r=>r.id)).size,22);for(const page of [0,-1,1.5,10001])assert.equal(await prospectOutreachOverview(t.db,t.actor,page),null);});
test('source-result provenance refuses an audit report and cannot cross workspaces at the FK',async c=>{const t=await setup(c),document=JSON.parse(readFileSync(new URL('./fixtures/prospect-skill-results.json',import.meta.url),'utf8'))[0];document.sourceContext={workspaceId:'fresh',prospectId:t.id,revision:2};const input={workspaceId:'fresh',prospectId:t.id,document},v=await previewSkillResult(t.db,t.actor,input),r=await applySkillResult(t.db,t.actor,{...input,document:v.document,requestId:crypto.randomUUID(),previewHash:v.previewHash,expectedRevision:v.revision,choices:Object.fromEntries(v.changes.map(c=>[c.key,'keep']))});assert.equal(await getProspectOutreach(t.db,t.actor,t.id,{resultId:r.resultId}),null);await saveProspectOutreach(t.db,t.actor,await draftInput(t));assert.throws(()=>run(t.raw,"UPDATE prospect_outreach_drafts SET workspace_id='foreign',source_result_id=?",r.resultId),/FOREIGN KEY/);});
