import {test} from 'node:test';
import assert from 'node:assert/strict';
import {testDb,run,one,all} from './_bloomops-db.mjs';
import {listWorkspacePages,getWorkspacePage,createWorkspacePage,saveWorkspacePage} from '../lib/bloomops/pages.mjs';
function fixture(c){const t=testDb();c.after(()=>t.raw.close());for(const id of ['w','other'])run(t.raw,'INSERT INTO workspaces(id,name,slug) VALUES(?,?,?)',id,id,id);run(t.raw,"INSERT INTO user(id,name,email) VALUES('u','Owner','owner@example.test')");run(t.raw,"INSERT INTO workspace_memberships(id,workspace_id,user_id,role,status) VALUES('m','w','u','owner','active')");t.actor={workspaceId:'w',membershipId:'m',userId:'u',role:'owner',status:'active'};t.create=(input={workspaceId:'w',requestId:crypto.randomUUID()})=>createWorkspacePage(t.db,t.actor,input);t.save=(id,patch={})=>saveWorkspacePage(t.db,t.actor,id,{workspaceId:'w',expectedRevision:1,title:'Guide',body:'<h2>Welcome</h2><p>A <strong>useful</strong> guide.</p>',...patch});return t;}
test('create/open/edit preserves exact content and keeps list/activity content-free',async c=>{const t=fixture(c),made=await t.create();assert.ok(made.ok);assert.equal((await getWorkspacePage(t.db,t.actor,made.id)).title,'Untitled');const saved=await t.save(made.id);assert.equal(saved.revision,2);const p=await getWorkspacePage(t.db,t.actor,made.id);assert.equal(p.body,'<h2>Welcome</h2><p>A <strong>useful</strong> guide.</p>');assert.equal((await listWorkspacePages(t.db,t.actor)).rows[0].title,'Guide');assert.ok(!JSON.stringify(await listWorkspacePages(t.db,t.actor)).includes('useful'));assert.ok(!JSON.stringify(all(t.raw,'SELECT metadata_json FROM activity_events')).includes('useful'));});
test('concurrent repeated create produces one page and activity',async c=>{const t=fixture(c),input={workspaceId:'w',requestId:crypto.randomUUID()},results=await Promise.all([t.create(input),t.create(input)]);assert.ok(results.every(x=>x.ok));assert.equal(results[0].id,results[1].id);assert.equal(one(t.raw,'SELECT count(*) n FROM bloomops_pages').n,1);assert.equal(one(t.raw,"SELECT count(*) n FROM activity_events WHERE event_type='PAGE_CREATED'").n,1);});
test('competing revisions never silently overwrite another edit',async c=>{const t=fixture(c),{id}=await t.create(),results=await Promise.all([t.save(id,{title:'A'}),t.save(id,{title:'B'})]);assert.equal(results.filter(x=>x.ok).length,1);assert.equal(results.filter(x=>x.reason==='conflict').length,1);assert.equal(one(t.raw,"SELECT count(*) n FROM activity_events WHERE event_type='PAGE_SAVED'").n,1);assert.equal((await getWorkspacePage(t.db,t.actor,id)).revision,2);});
for(const role of ['project_manager','team_member','client'])test(role+' cannot list/read/create/save pages',async c=>{const t=fixture(c),{id}=await t.create();t.actor.role=role;run(t.raw,'UPDATE workspace_memberships SET role=? WHERE id=?',role,'m');assert.equal(await listWorkspacePages(t.db,t.actor),null);assert.equal(await getWorkspacePage(t.db,t.actor,id),null);assert.equal((await t.create()).reason,'not_found');assert.equal((await t.save(id)).reason,'not_found');});
test('foreign workspace and missing page are indistinguishable',async c=>{const t=fixture(c),{id}=await t.create(),foreign={...t.actor,workspaceId:'other'};assert.equal(await getWorkspacePage(t.db,foreign,id),null);assert.equal((await saveWorkspacePage(t.db,foreign,id,{workspaceId:'other',expectedRevision:1,title:'X',body:''})).reason,'not_found');assert.equal((await t.save(crypto.randomUUID())).reason,'not_found');});
for(const change of ["UPDATE workspace_memberships SET status='suspended' WHERE id='m'","UPDATE workspace_memberships SET role='team_member' WHERE id='m'","UPDATE workspaces SET status='archived' WHERE id='w'"])test('current authority is rechecked under the write lock: '+change,async c=>{const t=fixture(c),{id}=await t.create(),batch=t.db.batch.bind(t.db);t.db.batch=async s=>{run(t.raw,change);return batch(s);};assert.equal((await t.save(id)).reason,'not_found');assert.equal(one(t.raw,'SELECT revision FROM bloomops_pages WHERE id=?',id).revision,1);assert.equal((await t.create()).reason,'not_found');assert.equal(await getWorkspacePage(t.db,t.actor,id),null);});
test('page and activity failures roll back atomically',async c=>{const t=fixture(c);run(t.raw,"CREATE TRIGGER deny_page_activity BEFORE INSERT ON activity_events WHEN NEW.event_type IN ('PAGE_CREATED','PAGE_SAVED') BEGIN SELECT RAISE(ABORT,'injected'); END");await assert.rejects(t.create(),/injected/);assert.equal(one(t.raw,'SELECT count(*) n FROM bloomops_pages').n,0);run(t.raw,'DROP TRIGGER deny_page_activity');const {id}=await t.create();run(t.raw,"CREATE TRIGGER deny_page_save BEFORE UPDATE ON bloomops_pages BEGIN SELECT RAISE(ABORT,'injected save'); END");await assert.rejects(t.save(id),/injected save/);assert.equal(one(t.raw,"SELECT count(*) n FROM activity_events WHERE event_type='PAGE_SAVED'").n,0);assert.equal(one(t.raw,'SELECT revision FROM bloomops_pages').revision,1);});
test('strict fields, revisions, title and byte limits reject without truncation',async c=>{const t=fixture(c),{id}=await t.create();for(const patch of [{title:''},{title:'x'.repeat(201)},{body:'🌷'.repeat(450001)},{expectedRevision:0},{expectedRevision:1.5},{workspaceId:'other'},{shareToken:'x'},{visibility:'public'},{body:null}])assert.equal((await t.save(id,patch)).reason,'invalid');assert.equal((await t.create({workspaceId:'w',requestId:'bad'})).reason,'invalid');assert.equal((await t.save(id,{body:'🌷'.repeat(450000)})).ok,true);assert.equal((await getWorkspacePage(t.db,t.actor,id)).body.length,900000);});
test('database protects page identity and next revision',async c=>{const t=fixture(c),{id}=await t.create();for(const patch of ["workspace_id='other'","creation_request_id='different'","created_at='different'","revision=revision+2"])assert.throws(()=>run(t.raw,'UPDATE bloomops_pages SET '+patch+' WHERE id=?',id),/immutable/);});
test('listing pagination keeps older pages reachable without loading bodies',async c=>{const t=fixture(c);for(let i=0;i<51;i++)await t.create();const a=await listWorkspacePages(t.db,t.actor),b=await listWorkspacePages(t.db,t.actor,2);assert.equal(a.rows.length,50);assert.equal(a.more,true);assert.equal(b.rows.length,1);assert.equal(new Set([...a.rows,...b.rows].map(x=>x.id)).size,51);assert.equal((await listWorkspacePages(t.db,t.actor,-1)).page,1);});
