import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createPageDraftStore,pageDraftData,PAGE_DRAFT_TTL,PAGE_DRAFT_BYTES,syncLegacyPageLogout} from '../lib/bloomops/page-draft-store.mjs';
import {pageDraftKey} from '../lib/bloomops/page-drafts.mjs';
import {changeDraftContext,DRAFT_CONTEXT_KEY,PAGE_LEGACY_LOGOUT_KEY} from '../lib/bloomops/draft-context.mjs';
const scope={userId:'user',workspaceId:'workspace',pageId:'page'},now=1000000000;
function storage(){const values={};return new Proxy({getItem:k=>values[k]??null,setItem:(k,v)=>{values[k]=String(v);},removeItem:k=>{delete values[k];}},{ownKeys:()=>Object.keys(values),getOwnPropertyDescriptor:(_,k)=>Object.hasOwn(values,k)?{enumerable:true,configurable:true}:undefined});}
const draft=()=>({title:'Draft',body:'<p>New input</p>',revision:2,saved:{title:'Page',body:'<p>Original</p>'},pending:{title:'Sent',body:'<p>Unconfirmed</p>',expectedRevision:2}});
test('independent page copies retain exact outstanding attempt and enforce original scope',()=>{const s=storage(),l=storage(),a=createPageDraftStore(s,l,scope,'a',()=>now),b=createPageDraftStore(s,l,scope,'b',()=>now);a.write(draft());b.write({...draft(),body:'Another tab'});assert.equal(a.list().length,2);assert.deepEqual(a.snapshot(a.own).value,draft());for(const patch of [{userId:'other'},{workspaceId:'other'},{pageId:'other'}]){const other=createPageDraftStore(s,l,{...scope,...patch},'a',()=>now);assert.deepEqual(other.list(),[]);assert.equal(other.snapshot(a.own),null);assert.equal(other.remove(a.own),false);}});
test('legacy tab draft remains available without mutation until checked recovery or explicit removal',()=>{const s=storage(),l=storage(),key=pageDraftKey(scope.userId,scope.workspaceId,scope.pageId),raw=JSON.stringify({title:'Legacy',body:'<p>Keep me</p>',revision:1});l.setItem(key,raw);const a=createPageDraftStore(s,l,scope,'a',()=>now);assert.equal(a.list()[0].legacy,true);assert.equal(l.getItem(key),raw);const checked=a.snapshot(key);l.setItem(key,JSON.stringify({...checked.value,body:'Newer legacy copy'}));assert.equal(a.remove(key,checked.raw),false);assert.match(l.getItem(key),/Newer legacy/);});
test('encoded bounds and invalid revisions reject without truncating fields',()=>{const s=storage(),l=storage(),a=createPageDraftStore(s,l,scope,'a',()=>now);for(const patch of [{revision:0},{title:'x'.repeat(201)},{body:'花'.repeat(600001)},{pending:{...draft().pending,expectedRevision:1}},{saved:[]},{body:null}])assert.equal(pageDraftData({...draft(),...patch}),null);a.write(draft());const raw=JSON.parse(s.getItem(a.own));s.setItem(a.own,JSON.stringify({...raw,padding:'花'.repeat(Math.ceil(PAGE_DRAFT_BYTES/3))}));assert.equal(a.snapshot(a.own),null);});
test('expiry removes only old copies in this page scope',()=>{const s=storage(),l=storage(),a=createPageDraftStore(s,l,scope,'a',()=>now),other=createPageDraftStore(s,l,{...scope,pageId:'other'},'a',()=>now);a.write(draft());other.write(draft());const later=createPageDraftStore(s,l,scope,'new',()=>now+PAGE_DRAFT_TTL+1);assert.deepEqual(later.list(),[]);assert.equal(s.getItem(a.own),null);assert.ok(s.getItem(other.own));});
test('ten-copy cap and failed replacement leave source recoverable; CAS preserves newer writer',()=>{const s=storage(),l=storage(),writers=Array.from({length:10},(_,i)=>createPageDraftStore(s,l,scope,'tab'+i,()=>now));for(const w of writers)w.write(draft());const next=createPageDraftStore(s,l,scope,'next',()=>now),copy=next.snapshot(writers[0].own);assert.throws(()=>next.write(copy.value),/Ten recovery copies/);assert.ok(next.snapshot(copy.key));writers[0].write({...draft(),body:'Newer'});assert.equal(next.remove(copy.key,copy.raw),false);assert.equal(next.snapshot(copy.key).value.body,'Newer');assert.equal(next.list().length,10);});
test('workspace epoch and disposed stores cannot resurrect retired drafts',()=>{const s=storage(),l=storage(),a=createPageDraftStore(s,l,scope,'a',()=>now);a.write(draft());s.setItem(DRAFT_CONTEXT_KEY,'changed');assert.equal(a.write(draft()),false);assert.deepEqual(a.list(),[]);const b=createPageDraftStore(s,l,scope,'b',()=>now);assert.equal(b.list().length,1);b.dispose();assert.equal(b.write(draft()),false);});
test('quota rejection keeps previous source and does not claim success',()=>{const s=storage(),l=storage(),a=createPageDraftStore(s,l,scope,'a',()=>now);a.write(draft());const before=s.getItem(a.own),b=createPageDraftStore(s,l,scope,'b',()=>now);s.setItem=()=>{throw Error('Quota exceeded');};assert.throws(()=>b.write(draft()),/Quota/);assert.equal(s.getItem(a.own),before);assert.equal(b.snapshot(b.own),null);});
test('logout removes page copies and retires inactive tabs legacy drafts on their next access',()=>{const s=storage(),l=storage(),otherTab=storage(),a=createPageDraftStore(s,l,scope,'a',()=>now),key=pageDraftKey(scope.userId,scope.workspaceId,scope.pageId);a.write(draft());l.setItem(key,JSON.stringify(draft()));otherTab.setItem(key,JSON.stringify(draft()));s.setItem('preference','keep');const previous=Object.fromEntries(['localStorage','sessionStorage','window'].map(k=>[k,globalThis[k]]));try{globalThis.localStorage=s;globalThis.sessionStorage=l;globalThis.window={dispatchEvent(){}};changeDraftContext({logout:true});assert.equal(s.getItem(a.own),null);assert.equal(l.getItem(key),null);assert.ok(s.getItem(PAGE_LEGACY_LOGOUT_KEY));syncLegacyPageLogout(s,otherTab);assert.equal(otherTab.getItem(key),null);assert.equal(s.getItem('preference'),'keep');assert.equal(a.write(draft()),false);}finally{for(const [k,v]of Object.entries(previous))if(v===undefined)delete globalThis[k];else globalThis[k]=v;}});
test('legacy copies expire seven days after first observation without extending on reload',()=>{const s=storage(),l=storage(),key=pageDraftKey(scope.userId,scope.workspaceId,scope.pageId),raw=JSON.stringify(draft());l.setItem(key,raw);const a=createPageDraftStore(s,l,scope,'a',()=>now);assert.equal(a.snapshot(key).at,now);assert.equal(l.getItem(key),raw);const reload=createPageDraftStore(s,l,scope,'reload',()=>now+1000);assert.equal(reload.snapshot(key).at,now);const expired=createPageDraftStore(s,l,scope,'expired',()=>now+PAGE_DRAFT_TTL+1);assert.equal(expired.snapshot(key),null);assert.equal(l.getItem(key),null);});
