import test from 'node:test';
import assert from 'node:assert/strict';
import {fixture} from './_prospect-conversion-fixture.mjs';
import {run,all} from './_bloomops-db.mjs';
import {listProspectSheet} from '../lib/bloomops/prospect-sheet.mjs';
import {sheetQuery,sheetPreferences} from '../lib/bloomops/prospect-sheet-values.mjs';
import {sampleCsv,parseCsv} from '../lib/bloomops/prospect-csv-values.mjs';
import {previewCsv,commitCsv,csvReceipt} from '../lib/bloomops/prospect-csv.mjs';
import {exportSheetSelection} from '../lib/bloomops/prospect-sheet-export.mjs';
import {convertProspect} from '../lib/bloomops/prospect-conversions.mjs';
import {reviewProspectOnboarding,startProspectOnboarding} from '../lib/bloomops/prospect-onboarding.mjs';
const document=()=>({workspaceId:'w',text:sampleCsv(),fileName:'sample.csv'});
const command=(doc,preview)=>({workspaceId:'w',requestId:crypto.randomUUID(),document:doc,previewHash:preview.previewHash,selected:preview.rows.filter(r=>r.status==='ready').map(r=>r.index),separate:[]});
test('sample parser accepts exact download including social-only unknowns and mapping',()=>{const r=parseCsv(sampleCsv());assert.equal(r.rows.length,2);assert.deepEqual(r.rows.map(r=>r.errors),[[],[]]);assert.equal(r.rows[1].fields.website,null);assert.equal(r.rows[1].fields.publicEmail,null);assert.equal(r.mapping.length,8);});
test('CSV parser rejects malformed quotes, extra cells, unsupported sensitive columns and invalid URLs',()=>{assert.throws(()=>parseCsv('Business name,Fit\nA,strong'));assert.throws(()=>parseCsv('Business name\n"oops'));assert.ok(parseCsv('Business name,Website\nX,javascript:bad').rows[0].errors.length);assert.ok(parseCsv('Business name\nA,B').rows[0].errors.length);assert.equal(parseCsv('Business name,Contact name\n"A, B","Line\nTwo"').rows[0].fields.businessName,'A, B');});
test('strict queries and preference fallback preserve bounded limits',()=>{for(const size of [25,50,100,200])assert.equal(sheetQuery({size}).size,size);for(const q of [{size:201},{size:'all'},{page:0},{sort:'name'},{direction:'desc;drop'},{private:'1'},{view:'unknown'}])assert.equal(sheetQuery(q),null);assert.equal(sheetPreferences({viewId:'deleted',query:{q:'old'}}).query.q,'');});
test('fresh default, all date orders/null-last/page sizes and counts',async c=>{const t=await fixture(c);for(let i=0;i<220;i++)run(t.raw,"INSERT INTO bloomops_prospects(id,workspace_id,creation_request_id,creation_hash,created_by_membership_id,business_name,created_at,evidence_date) VALUES(?, 'w', ?, ?, 'm', ?, ?, ?)",'row'+i,'request'+i,'a'.repeat(64),'Record '+i,'2026-09-'+String(1+i%20).padStart(2,'0')+'T00:00:00.000Z',i%2?'2026-09-01':null);for(const size of [25,50,100,200]){const r=await listProspectSheet(t.db,t.actor,{size});assert.equal(r.rows.length,size);assert.equal(r.total,221);}for(const sort of ['createdAt','importedAt','lastContacted','evidenceDate'])for(const direction of ['asc','desc']){const r=await listProspectSheet(t.db,t.actor,{sort,direction,size:200});let sawNull=false;for(const row of r.rows){if(row[sort]===null)sawNull=true;else assert.equal(sawNull,false);}if(sort==='lastContacted')assert.equal(r.rows.every(r=>r.lastContacted===null),true);}const filtered=await listProspectSheet(t.db,t.actor,{q:'Record 21',size:25});assert.equal(filtered.total,11);});
test('CSV creates canonical rows once; timestamp, receipt and raw unknowns survive retries',async c=>{const t=await fixture(c),doc=document(),preview=await previewCsv(t.db,t.actor,doc),cmd=command(doc,preview);assert.equal(preview.rows.length,2);const first=await commitCsv(t.db,t.actor,cmd,new Date('2026-09-01T00:00:00Z'));assert.ok(first.receiptId,JSON.stringify(first));const second=await commitCsv(t.db,t.actor,cmd,new Date('2026-10-01T00:00:00Z'));assert.equal(second.receiptId,first.receiptId);const receipt=await csvReceipt(t.db,t.actor,first.receiptId);assert.equal(receipt.rows.filter(r=>r.status==='added').length,2);const sheet=await listProspectSheet(t.db,t.actor,{batch:first.receiptId});assert.equal(sheet.total,2);assert.ok(sheet.rows.every(r=>r.importedAt==='2026-09-01T00:00:00.000Z'&&r.fit==='unknown'));assert.equal((await previewCsv(t.db,t.actor,doc)).receiptId,first.receiptId);assert.equal(all(t.raw,'SELECT * FROM prospect_conversions').length,0);assert.equal(all(t.raw,'SELECT * FROM prospect_deliveries').length,0);});
test('probable duplicates require explicit distinct-contact review; stale preview rejects',async c=>{const t=await fixture(c),doc={workspaceId:'w',fileName:'same.csv',text:'Business name,Contact name,Email\nCedar House,Another Person,other@example.test\nUnique,One,one@example.test\nUnique,Two,two@example.test'},v=await previewCsv(t.db,t.actor,doc);assert.equal(v.rows[0].status,'duplicate');assert.equal(v.rows[2].status,'duplicate');const cmd={...command(doc,v),selected:[1,2,3]};assert.ok((await commitCsv(t.db,t.actor,cmd)).invalid);cmd.separate=[1,3];const ok=await commitCsv(t.db,t.actor,cmd);assert.ok(ok.receiptId);const nextDoc={...doc,text:'Business name\nAnother'},next=await previewCsv(t.db,t.actor,nextDoc);run(t.raw,'UPDATE bloomops_prospects SET revision=revision+1 WHERE id=?',t.id);assert.ok((await commitCsv(t.db,t.actor,command(nextDoc,next))).conflict);});
test('import atomic rollback and parallel retries',async c=>{const t=await fixture(c),doc=document(),v=await previewCsv(t.db,t.actor,doc),cmd=command(doc,v);run(t.raw,"CREATE TRIGGER fail_csv BEFORE INSERT ON prospect_csv_rows BEGIN SELECT RAISE(ABORT,'test rollback'); END");await assert.rejects(()=>commitCsv(t.db,t.actor,cmd));assert.equal(all(t.raw,'SELECT * FROM prospect_csv_batches').length,0);assert.equal(all(t.raw,'SELECT * FROM bloomops_prospects').length,1);run(t.raw,'DROP TRIGGER fail_csv');const both=await Promise.all([commitCsv(t.db,t.actor,cmd),commitCsv(t.db,t.actor,cmd)]);assert.equal(both[0].receiptId,both[1].receiptId);});
test('revoked, foreign and non-admin sheet/import/export are denied',async c=>{const t=await fixture(c);assert.equal(await listProspectSheet(t.db,{...t.actor,role:'client'}),null);assert.equal(await previewCsv(t.db,{...t.actor,role:'team_member'},document()),null);const selected={workspaceId:'w',kind:'records',rows:[{id:t.id,revision:1}]};assert.ok((await exportSheetSelection(t.db,t.actor,{...selected,rows:[{id:'foreign',revision:1}]})).conflict);run(t.raw,"UPDATE workspace_memberships SET status='suspended' WHERE id='m'");assert.equal((await listProspectSheet(t.db,t.actor)).total,0);assert.equal(await previewCsv(t.db,t.actor,document()),null);assert.ok((await exportSheetSelection(t.db,t.actor,selected)).conflict);});
test('manual audit batch packages canonical IDs/revisions; stale export rejects',async c=>{const t=await fixture(c),cmd={workspaceId:'w',kind:'audit',rows:[{id:t.id,revision:1}]},r=await exportSheetSelection(t.db,t.actor,cmd);assert.equal(r.records[0].context.prospect.id,t.id);assert.equal(r.records[0].context.prospect.workspaceId,'w');assert.match(r.instructions,/manually/);run(t.raw,'UPDATE bloomops_prospects SET revision=2 WHERE id=?',t.id);assert.ok((await exportSheetSelection(t.db,t.actor,cmd)).conflict);});
async function converted(t){const preview=await t.preview();const r=await convertProspect(t.db,t.actor,t.id,{...t.input,requestId:crypto.randomUUID(),reviewHash:preview.conversionReview.hash,confirmed:true});assert.ok(r.ok);return r;}
test('canonical onboarding setup is explicit and duplicate-safe with zero invitations',async c=>{const t=await fixture(c);await converted(t);let sheet=await listProspectSheet(t.db,t.actor);assert.equal(sheet.rows[0].nextAction,'Finish client setup');const review=await reviewProspectOnboarding(t.db,t.actor,t.id);assert.equal(review.state,'review',JSON.stringify(review));const cmd={workspaceId:'w',confirmed:true,reviewHash:review.reviewHash};const result=await startProspectOnboarding(t.db,t.actor,t.id,cmd);assert.equal(result.state,'ready',JSON.stringify(result));assert.equal((await startProspectOnboarding(t.db,t.actor,t.id,cmd)).instanceId,result.instanceId);assert.equal(all(t.raw,'SELECT * FROM onboarding_instances').length,1);assert.equal(all(t.raw,'SELECT * FROM workspace_invitations').length,0);sheet=await listProspectSheet(t.db,t.actor);assert.equal(sheet.rows[0].outreach,'Won');assert.equal(all(t.raw,'SELECT user_id FROM client_contacts WHERE client_id=?',result.clientId)[0].user_id,null);});
test('missing onboarding template preserves sale and stop; repair works',async c=>{const t=await fixture(c);run(t.raw,"UPDATE template_versions SET status='retired'");await converted(t);const review=await reviewProspectOnboarding(t.db,t.actor,t.id);assert.equal(review.state,'blocked');assert.equal(all(t.raw,'SELECT * FROM prospect_conversions').length,1);assert.equal(all(t.raw,'SELECT * FROM client_activations').length,0);});

test('manual contacts and interest project facts without sending; retries do not inflate dates',async c=>{const {recordProspectContactFact}=await import('../lib/bloomops/prospect-contact-facts.mjs'),t=await fixture(c),cmd={workspaceId:'w',requestId:crypto.randomUUID(),kind:'contact',occurredAt:'2026-09-01T12:00:00Z',note:'Manually sent through the business contact form.'};assert.ok((await recordProspectContactFact(t.db,t.actor,t.id,cmd)).ok);assert.ok((await recordProspectContactFact(t.db,t.actor,t.id,cmd)).ok);let row=(await listProspectSheet(t.db,t.actor)).rows[0];assert.equal(row.lastContacted,'2026-09-01T12:00:00.000Z');assert.equal(row.outreach,'Contacted');await recordProspectContactFact(t.db,t.actor,t.id,{...cmd,requestId:crypto.randomUUID(),kind:'interest',occurredAt:'2026-09-02T12:00:00Z',note:'They explicitly requested a proposal.'});row=(await listProspectSheet(t.db,t.actor)).rows[0];assert.equal(row.outreach,'Interested');assert.equal(row.lastContacted,'2026-09-01T12:00:00.000Z');assert.equal(all(t.raw,'SELECT * FROM prospect_deliveries').length,0);assert.throws(()=>run(t.raw,"DELETE FROM activity_events WHERE event_type='PROSPECT_MANUAL_CONTACT'"));});
test('onboarding rejects changed contact and rolls back late revocation',async c=>{const t=await fixture(c);await converted(t);const review=await reviewProspectOnboarding(t.db,t.actor,t.id),cmd={workspaceId:'w',confirmed:true,reviewHash:review.reviewHash};run(t.raw,"UPDATE client_contacts SET email='changed@example.test' WHERE client_id=?",review.clientId);assert.ok((await startProspectOnboarding(t.db,t.actor,t.id,cmd)).conflict);const fresh=await reviewProspectOnboarding(t.db,t.actor,t.id),batch=t.db.batch.bind(t.db);t.db.batch=async statements=>{run(t.raw,"UPDATE workspace_memberships SET status='suspended' WHERE id='m'");return batch(statements);};const result=await startProspectOnboarding(t.db,t.actor,t.id,{...cmd,reviewHash:fresh.reviewHash});assert.ok(!result||result.conflict);assert.equal(all(t.raw,'SELECT * FROM onboarding_instances').length,0);assert.equal(all(t.raw,'SELECT * FROM prospect_conversions').length,1);});
test('sheet edit eligibility is checked atomically without invalidating its own source updates',async c=>{const {updateProspect}=await import('../lib/bloomops/prospects.mjs'),{sheetScope}=await import('../lib/bloomops/prospect-sheet.mjs'),t=await fixture(c);await updateProspect(t.db,{actor:t.actor,id:t.id,input:{workspaceId:'w',expectedRevision:1,fields:{fit:'strong'},sources:{fit:{checked:true,url:'https://example.test'}}}});const ready=sheetScope(t.actor,{view:'ready'});assert.equal((await listProspectSheet(t.db,t.actor,{view:'ready'})).total,1);const updated=await updateProspect(t.db,{actor:t.actor,id:t.id,input:{workspaceId:'w',expectedRevision:2,fields:{fit:'hold'}},additionalCondition:ready.where});assert.ok(updated.ok);assert.equal(all(t.raw,'SELECT fit FROM bloomops_prospects WHERE id=?',t.id)[0].fit,'hold');assert.equal((await listProspectSheet(t.db,t.actor,{view:'ready'})).total,0);const rejected=await updateProspect(t.db,{actor:t.actor,id:t.id,input:{workspaceId:'w',expectedRevision:3,fields:{platform:'Wix'}},additionalCondition:ready.where});assert.equal(rejected.reason,'conflict');assert.equal(all(t.raw,'SELECT platform FROM bloomops_prospects WHERE id=?',t.id)[0].platform,null);});
test('maximum onboarding service selection stays within D1 binding limits',async c=>{const t=await fixture(c);await converted(t);const review=await reviewProspectOnboarding(t.db,t.actor,t.id);for(let i=0;i<49;i++){run(t.raw,"INSERT INTO service_types(id,workspace_id,name,slug) VALUES(?, 'w', ?, ?)",'extra-type-'+i,'Extra '+i,'extra-'+i);run(t.raw,"INSERT INTO service_engagements(id,workspace_id,client_id,service_type_id) VALUES(?,'w',?,?)",'extra-service-'+i,review.clientId,'extra-type-'+i);}let max=0;const original=t.db.batch.bind(t.db);t.db.batch=async stmts=>{for(const s of stmts)max=Math.max(max,s.toSQL().params.length);return original(stmts);};const fresh=await reviewProspectOnboarding(t.db,t.actor,t.id);assert.equal(fresh.state,'review');const done=await startProspectOnboarding(t.db,t.actor,t.id,{workspaceId:'w',confirmed:true,reviewHash:fresh.reviewHash});assert.equal(done.state,'ready',JSON.stringify(done));assert.ok(max<=100,'Largest statement has '+max+' bindings');console.log('Maximum onboarding statement bindings:',max);});

test('sheet undo restores checked provenance exactly and preserves unrelated concurrent edits',async c=>{
 const {updateProspect,undoProspectSheetEdit,getProspect}=await import('../lib/bloomops/prospects.mjs'),t=await fixture(c);
 await updateProspect(t.db,{actor:t.actor,id:t.id,input:{workspaceId:'w',expectedRevision:1,fields:{fit:'strong'},sources:{fit:{checked:true,url:'https://example.test/evidence'}}},now:new Date('2026-09-01T00:00:00Z')});
 const before=all(t.raw,"SELECT * FROM prospect_field_sources WHERE prospect_id=? AND field_key='fit'",t.id)[0];
 const edit=await updateProspect(t.db,{actor:t.actor,id:t.id,input:{workspaceId:'w',expectedRevision:2,fields:{fit:'hold'}},captureUndo:true});assert.ok(edit.undoEventId);
 assert.equal((await listProspectSheet(t.db,t.actor,{view:'ready'})).total,0);
 await updateProspect(t.db,{actor:t.actor,id:t.id,input:{workspaceId:'w',expectedRevision:3,fields:{platform:'Kajabi'}}});
 const undone=await undoProspectSheetEdit(t.db,{actor:t.actor,id:t.id,eventId:edit.undoEventId});assert.ok(undone.ok,JSON.stringify(undone));
 assert.deepEqual(all(t.raw,"SELECT * FROM prospect_field_sources WHERE prospect_id=? AND field_key='fit'",t.id)[0],before);
 assert.equal((await listProspectSheet(t.db,t.actor,{view:'ready'})).total,1);const profile=await getProspect(t.db,t.actor,t.id);assert.equal(profile.profile.platform,'Kajabi');assert.ok(profile.activity.every(e=>!Object.hasOwn(e.metadata,'undo')));
 assert.ok((await undoProspectSheetEdit(t.db,{actor:t.actor,id:t.id,eventId:edit.undoEventId})).unchanged);
});
test('sheet undo denies foreign/revoked actors and refuses same-field or source edits',async c=>{
 const {updateProspect,undoProspectSheetEdit}=await import('../lib/bloomops/prospects.mjs'),t=await fixture(c);
 const edit=await updateProspect(t.db,{actor:t.actor,id:t.id,input:{workspaceId:'w',expectedRevision:1,fields:{platform:'Kajabi'}},captureUndo:true});
 assert.equal((await undoProspectSheetEdit(t.db,{actor:{...t.actor,workspaceId:'foreign'},id:t.id,eventId:edit.undoEventId})).reason,'not_found');
 await updateProspect(t.db,{actor:t.actor,id:t.id,input:{workspaceId:'w',expectedRevision:2,fields:{platform:'Kajabi'},sources:{platform:{checked:true}}}});
 assert.equal((await undoProspectSheetEdit(t.db,{actor:t.actor,id:t.id,eventId:edit.undoEventId})).reason,'conflict');
 const next=await updateProspect(t.db,{actor:t.actor,id:t.id,input:{workspaceId:'w',expectedRevision:3,fields:{businessName:'Changed'}},captureUndo:true});
 const batch=t.db.batch.bind(t.db);t.db.batch=async stmts=>{run(t.raw,"UPDATE workspace_memberships SET status='suspended' WHERE id='m'");return batch(stmts);};
 assert.equal((await undoProspectSheetEdit(t.db,{actor:t.actor,id:t.id,eventId:next.undoEventId})).reason,'conflict');assert.equal(all(t.raw,'SELECT business_name FROM bloomops_prospects WHERE id=?',t.id)[0].business_name,'Changed');
});
test('sheet undo rolls back its receipt with failed source restore, then retries once',async c=>{
 const {updateProspect,undoProspectSheetEdit}=await import('../lib/bloomops/prospects.mjs'),t=await fixture(c);
 const edit=await updateProspect(t.db,{actor:t.actor,id:t.id,input:{workspaceId:'w',expectedRevision:1,fields:{platform:'Kajabi'}},captureUndo:true});
 run(t.raw,"CREATE TRIGGER fail_undo BEFORE DELETE ON prospect_field_sources BEGIN SELECT RAISE(ABORT,'synthetic restore failure'); END");
 await assert.rejects(()=>undoProspectSheetEdit(t.db,{actor:t.actor,id:t.id,eventId:edit.undoEventId}));assert.equal(all(t.raw,"SELECT * FROM activity_events WHERE json_extract(metadata_json,'$.undoOf')=?",edit.undoEventId).length,0);
 run(t.raw,'DROP TRIGGER fail_undo');const both=await Promise.all([undoProspectSheetEdit(t.db,{actor:t.actor,id:t.id,eventId:edit.undoEventId}),undoProspectSheetEdit(t.db,{actor:t.actor,id:t.id,eventId:edit.undoEventId})]);assert.ok(both.every(x=>x.ok));assert.equal(all(t.raw,"SELECT * FROM activity_events WHERE json_extract(metadata_json,'$.undoOf')=?",edit.undoEventId).length,1);assert.equal(all(t.raw,"SELECT * FROM prospect_field_sources WHERE prospect_id=? AND field_key='platform'",t.id).length,0);
});
test('waiting follows the latest outbound after a resolved reply without clearing sending holds',async c=>{
 const {repliesFixture}=await import('./_prospect-replies-fixture.mjs'),{recordProspectContactFact}=await import('../lib/bloomops/prospect-contact-facts.mjs'),t=await repliesFixture(c),base=Date.now()+1000,at=n=>new Date(base+n).toISOString(),now=new Date(base+10000);
 run(t.raw,"INSERT INTO prospect_reply_states(workspace_id,prospect_id,delivery_id,revision) VALUES(?,?,?,1)",t.actor.workspaceId,t.id,t.input.deliveryId);
 const addReply=(message,n)=>run(t.raw,"INSERT INTO prospect_reply_observations(id,workspace_id,prospect_id,delivery_id,account_email,provider_message_id,received_at,kind,match,observed_by_membership_id) VALUES(?,?,?,?,?,?,?,'reply_unreviewed','reply_chain',?)",crypto.randomUUID(),t.actor.workspaceId,t.id,t.input.deliveryId,'hello@example.test',message,at(n),t.actor.membershipId);
 addReply('first-reply',0);assert.equal((await listProspectSheet(t.db,t.actor,{view:'reply'})).total,1);assert.equal((await listProspectSheet(t.db,t.actor,{view:'waiting'})).total,0);
 await recordProspectContactFact(t.db,t.actor,t.id,{workspaceId:t.actor.workspaceId,requestId:crypto.randomUUID(),kind:'resolved',occurredAt:at(1000),note:'Reviewed the first reply.'},now);assert.equal((await listProspectSheet(t.db,t.actor,{view:'reply'})).total,0);assert.equal((await listProspectSheet(t.db,t.actor,{view:'waiting'})).total,0);
 await recordProspectContactFact(t.db,t.actor,t.id,{workspaceId:t.actor.workspaceId,requestId:crypto.randomUUID(),kind:'contact',occurredAt:at(2000),note:'Sent a separately approved manual response.'},now);assert.equal((await listProspectSheet(t.db,t.actor,{view:'waiting'})).total,1);
 addReply('second-reply',3000);assert.equal((await listProspectSheet(t.db,t.actor,{view:'waiting'})).total,0);assert.equal((await listProspectSheet(t.db,t.actor,{view:'reply'})).total,1);
 run(t.raw,"UPDATE prospect_reply_states SET hold_state='held',revision=revision+1");await recordProspectContactFact(t.db,t.actor,t.id,{workspaceId:t.actor.workspaceId,requestId:crypto.randomUUID(),kind:'contact',occurredAt:at(4000),note:'Manual response does not clear protection.'},now);assert.equal((await listProspectSheet(t.db,t.actor,{view:'waiting'})).total,0);assert.equal(all(t.raw,'SELECT hold_state FROM prospect_reply_states')[0].hold_state,'held');
});
test('manual evidence notes remain readable only in authorized prospect history',async c=>{
 const {recordProspectContactFact}=await import('../lib/bloomops/prospect-contact-facts.mjs'),{getProspect}=await import('../lib/bloomops/prospects.mjs'),t=await fixture(c);
 for(const kind of ['contact','interest','resolved'])await recordProspectContactFact(t.db,t.actor,t.id,{workspaceId:'w',requestId:crypto.randomUUID(),kind,occurredAt:new Date().toISOString(),note:'Visible internal evidence for '+kind});
 const history=(await getProspect(t.db,t.actor,t.id)).activity;assert.equal(history.filter(e=>e.metadata.note?.startsWith('Visible internal evidence')).length,3);assert.ok(history.every(e=>!Object.hasOwn(e.metadata,'source')));
 assert.equal(await getProspect(t.db,{...t.actor,role:'client'},t.id),null);assert.equal(await getProspect(t.db,{...t.actor,workspaceId:'foreign'},t.id),null);run(t.raw,"UPDATE workspace_memberships SET status='suspended' WHERE id='m'");assert.equal(await getProspect(t.db,t.actor,t.id),null);
});

test('empty-state copy distinguishes a filtered miss from an empty authorized workspace',async c=>{
 const t=await fixture(c);
 assert.equal((await listProspectSheet(t.db,t.actor,{q:'no matching synthetic record'})).workspaceEmpty,false);
 assert.equal((await listProspectSheet(t.db,t.actor,{})).workspaceEmpty,false);
 run(t.raw,"INSERT INTO workspace_memberships(id,workspace_id,user_id,role,status) VALUES('empty-member','foreign','owner','owner','active')");
 t.actor={...t.actor,workspaceId:'foreign',membershipId:'empty-member'};
 assert.equal((await listProspectSheet(t.db,t.actor,{})).workspaceEmpty,true);
 assert.equal((await listProspectSheet(t.db,t.actor,{q:'no matching synthetic record'})).workspaceEmpty,true);
 run(t.raw,"UPDATE workspace_memberships SET status='suspended' WHERE id='empty-member'");
 assert.equal((await listProspectSheet(t.db,t.actor,{})).rows.length,0);
});
