import {test} from 'node:test';
import assert from 'node:assert/strict';
import {fixture} from './_prospect-conversion-fixture.mjs';
import {run,all} from './_bloomops-db.mjs';
import {convertProspect,getProspectConversion} from '../lib/bloomops/prospect-conversions.mjs';
import {getRecipientProtection,recipientUnrestricted} from '../lib/bloomops/prospect-recipient-protection.mjs';
import {sql} from 'drizzle-orm';
async function setup(c){const t=await fixture(c);t.command=async(patch={})=>{const input={...t.input,...patch},view=await t.preview(patch);assert.ok(view.ok);return {...input,requestId:crypto.randomUUID(),reviewHash:view.conversionReview.hash,confirmed:true};};t.convert=(command,actor=t.actor)=>convertProspect(t.db,actor,t.id,command);return t;}
const rows=(t,table)=>all(t.raw,'SELECT * FROM '+table);
test('new conversion atomically creates canonical records, history and permanent stop without portal links',async c=>{const t=await setup(c),command=await t.command(),before=rows(t,'bloomops_prospects'),result=await t.convert(command);assert.ok(result.ok,JSON.stringify(result));assert.equal(result.receipt.clientCreated,true);assert.equal(result.receipt.serviceCreated,true);assert.equal(result.receipt.outreachStopped,true);assert.equal(rows(t,'prospect_conversions').length,1);const client=rows(t,'bloomops_clients').find(x=>x.id===result.receipt.clientId);assert.equal(client.relationship_status,'draft');assert.equal(client.health,'on_track');const contact=rows(t,'client_contacts').find(x=>x.client_id===client.id);assert.equal(contact.email,'maya@example.test');assert.equal(contact.user_id,null);assert.equal(rows(t,'service_engagements')[0].status,'planned');assert.deepEqual(rows(t,'bloomops_prospects'),before);for(const table of ['onboarding_instances','workspace_invitations','client_activations'])assert.equal(rows(t,table).length,0);assert.equal(rows(t,'activity_events').filter(x=>x.event_type==='PROSPECT_CONVERTED').length,1);assert.equal((await getRecipientProtection(t.db,t.actor,'maya@example.test')).kind,'stopped');});
test('same request retry and concurrent retry return one receipt and one set of records',async c=>{const t=await setup(c),command=await t.command(),results=await Promise.all([t.convert(command),t.convert(command)]);assert.ok(results.every(x=>x.ok),JSON.stringify(results));assert.equal(results[0].receipt.id,results[1].receipt.id);const snapshot=t.snapshot();assert.equal((await t.convert(command)).replayed,true);assert.deepEqual(t.snapshot(),snapshot);assert.equal(rows(t,'prospect_conversions').length,1);assert.equal(rows(t,'service_engagements').length,1);});
test('competing different requests cannot leave extra clients or engagements',async c=>{const t=await setup(c),a=await t.command(),b={...a,requestId:crypto.randomUUID()},results=await Promise.all([t.convert(a),t.convert(b)]);assert.equal(results.filter(x=>x.ok).length,1,JSON.stringify(results));assert.equal(rows(t,'bloomops_clients').length,3);assert.equal(rows(t,'client_contacts').length,2);assert.equal(rows(t,'service_engagements').length,1);assert.equal(rows(t,'prospect_conversions').length,1);});
test('existing active client and open service retain canonical contact, lifecycle and scope',async c=>{const t=await setup(c);run(t.raw,"UPDATE bloomops_clients SET relationship_status='active' WHERE id='w-client'");run(t.raw,"INSERT INTO service_engagements(id,workspace_id,client_id,service_type_id,scope_notes) VALUES('eng','w','w-client','w-service','Existing agreed scope')");const command=await t.command({mode:'existing',clientId:'w-client'}),before=['bloomops_clients','client_contacts','service_engagements'].map(x=>rows(t,x)),result=await t.convert(command);assert.ok(result.ok,JSON.stringify(result));assert.equal(result.receipt.clientCreated,false);assert.equal(result.receipt.serviceCreated,false);assert.equal(result.receipt.serviceEngagementId,'eng');assert.equal(result.receipt.scopeNotes,t.input.scopeNotes);assert.deepEqual(['bloomops_clients','client_contacts','service_engagements'].map(x=>rows(t,x)),before);assert.equal((await getRecipientProtection(t.db,t.actor,'existing@example.test')).kind,'stopped');});
test('missing templates do not prevent recording the sale',async c=>{const t=await setup(c);run(t.raw,'UPDATE templates SET active=0');assert.ok((await t.convert(await t.command())).ok);assert.equal(rows(t,'onboarding_instances').length,0);});
for(const point of ['client_contacts','service_engagements','prospect_conversions','activity_events'])test('failure at '+point+' rolls back every business change',async c=>{const t=await setup(c),command=await t.command();run(t.raw,'CREATE TRIGGER conversion_failure BEFORE INSERT ON '+point+" BEGIN SELECT RAISE(ABORT,'Injected conversion failure'); END");const before=t.snapshot();assert.equal((await t.convert(command)).ok,false);assert.deepEqual(t.snapshot(),before);});
for(const mutation of ["UPDATE workspace_memberships SET status='suspended' WHERE id='m'","UPDATE workspace_memberships SET role='team_member' WHERE id='m'","UPDATE workspaces SET status='archived' WHERE id='w'"])test('authority revoked immediately before the transaction creates nothing: '+mutation,async c=>{const t=await setup(c),command=await t.command(),batch=t.db.batch.bind(t.db);let before;t.db.batch=async statements=>{run(t.raw,mutation);before=t.snapshot();return batch(statements);};assert.equal((await t.convert(command)).ok,false);assert.deepEqual(t.snapshot(),before);});
for(const mutation of ["UPDATE bloomops_clients SET name='Changed' WHERE id='w-client'","UPDATE client_contacts SET email='changed@example.test' WHERE id='primary'","UPDATE service_types SET name='Changed' WHERE id='w-service'","UPDATE bloomops_prospects SET revision=revision+1 WHERE workspace_id='w'"])test('canonical changes immediately before write cannot use a stale review: '+mutation,async c=>{const t=await setup(c),command=await t.command({mode:'existing',clientId:'w-client'}),batch=t.db.batch.bind(t.db);let before;t.db.batch=async statements=>{run(t.raw,mutation);before=t.snapshot();return batch(statements);};assert.equal((await t.convert(command)).ok,false);assert.deepEqual(t.snapshot(),before);});
test('changed scope, foreign IDs, hidden commands, missing confirmation and stale fingerprints are refused',async c=>{const t=await setup(c),command=await t.command(),before=t.snapshot();for(const patch of [{scopeNotes:'Different scope'},{serviceTypeId:'foreign-service'},{mode:'existing',clientId:'foreign-client'},{workspaceId:'foreign'},{activate:true},{sendInvitation:true},{confirmed:false},{reviewHash:'0'.repeat(64)},{requestId:[command.requestId]},{requestId:{}},{requestId:null}])assert.equal((await t.convert({...command,...patch})).ok,false);assert.deepEqual(t.snapshot(),before);});
test('reused request ID with changed intent does not alter the receipt',async c=>{const t=await setup(c),command=await t.command();assert.ok((await t.convert(command)).ok);const before=t.snapshot();assert.equal((await t.convert({...command,scopeNotes:'Changed'})).ok,false);assert.deepEqual(t.snapshot(),before);});
test('receipt is immutable and the stop survives profile address changes',async c=>{const t=await setup(c);const result=await t.convert(await t.command());assert.ok(result.ok);assert.throws(()=>run(t.raw,'UPDATE prospect_conversions SET recipient_emails_json=?','[]'),/immutable/);assert.throws(()=>run(t.raw,'DELETE FROM prospect_conversions'),/permanent/);run(t.raw,"UPDATE bloomops_prospects SET public_email='new@example.test',revision=revision+1 WHERE id=?",t.id);assert.equal((await getRecipientProtection(t.db,t.actor,'maya@example.test')).kind,'stopped');assert.equal((await getRecipientProtection(t.db,t.actor,'new@example.test',t.id)).kind,'stopped');assert.equal(await getRecipientProtection(t.db,{...t.actor,workspaceId:'foreign'},'maya@example.test'),null);assert.equal((await getProspectConversion(t.db,t.actor,t.id)).receipt.id,result.receipt.id);});
test('terminal clients and invalid new contacts cannot be converted',async c=>{const t=await setup(c);run(t.raw,"UPDATE bloomops_clients SET relationship_status='ended' WHERE id='w-client'");assert.equal((await t.convert(await t.command({mode:'existing',clientId:'w-client'}))).ok,false);run(t.raw,'UPDATE bloomops_prospects SET public_email=NULL,revision=revision+1 WHERE id=?',t.id);assert.equal((await t.convert(await t.command())).ok,false);assert.equal(rows(t,'prospect_conversions').length,0);});
test('client slug collision retries the whole transaction without overwriting a namesake',async c=>{const t=await setup(c);run(t.raw,"UPDATE bloomops_clients SET slug='cedar-house' WHERE id='w-client'");const result=await t.convert(await t.command());assert.ok(result.ok,JSON.stringify(result));assert.match(rows(t,'bloomops_clients').find(x=>x.id===result.receipt.clientId).slug,/^cedar-house-/);assert.equal(rows(t,'bloomops_clients').length,3);});

for(const [source,saved] of [['Asia/Kolkata','Asia/Kolkata'],['UTC','Etc/UTC'],[null,null]])test('client handoff retains supported prospect timezone '+source,async c=>{const t=await setup(c);run(t.raw,'UPDATE bloomops_prospects SET time_zone=?,revision=revision+1 WHERE id=?',source,t.id);const result=await t.convert(await t.command());assert.ok(result.ok);assert.equal(rows(t,'bloomops_clients').find(row=>row.id===result.receipt.clientId).timezone,saved);});
