import {test} from 'node:test';
import assert from 'node:assert/strict';
import {setup} from './_projects.mjs';
import {run,one,all} from './_bloomops-db.mjs';
import {createWorkspacePage,getWorkspacePage,saveWorkspacePage} from '../lib/bloomops/pages.mjs';
import {getPageSharing,updatePageSharing} from '../lib/bloomops/page-sharing.mjs';
import {getPageRecordContext,pageRecordOptions,savePageRecordContext,listRecordPages} from '../lib/bloomops/page-record-context.mjs';
async function fixture(t){const f=await setup();t.after(()=>f.raw.close());f.pageId=(await createWorkspacePage(f.db,f.owner,{workspaceId:'a',requestId:crypto.randomUUID()})).id;f.projectId=(await f.create()).projectId;f.save=(patch={},actor=f.owner)=>savePageRecordContext(f.db,actor,f.pageId,{workspaceId:'a',userId:actor.userId,expectedRevision:0,clientId:'james',projectId:f.projectId,...patch});f.grant=async(user,permission='view')=>{const s=await getPageSharing(f.db,f.owner,f.pageId);assert.ok((await updatePageSharing(f.db,f.owner,f.pageId,{workspaceId:'a',expectedTreeRevision:s.revision,kind:'grant',membershipId:'m-'+user,permission})).ok);};return f;}
test('context saves, reopens and appears on its real records without changing document/grants',async t=>{const f=await fixture(t),before=await getWorkspacePage(f.db,f.owner,f.pageId);assert.deepEqual(await f.save(),{ok:true,revision:1});const view=await getPageRecordContext(f.db,f.owner,f.pageId);assert.equal(view.client.id,'james');assert.equal(view.project.id,f.projectId);assert.equal(view.revision,1);assert.equal((await listRecordPages(f.db,f.owner,{kind:'client',recordId:'james'})).items[0].id,f.pageId);assert.equal((await listRecordPages(f.db,f.owner,{kind:'project',recordId:f.projectId})).items[0].id,f.pageId);assert.deepEqual(await getWorkspacePage(f.db,f.owner,f.pageId),before);assert.equal(all(f.raw,'SELECT * FROM bloomops_page_grants').length,0);assert.equal(one(f.raw,"SELECT count(*) n FROM activity_events WHERE event_type='PAGE_CONTEXT_CHANGED'").n,1);});
test('unchanged retry has no extra revision/activity; removal preserves Page writing',async t=>{const f=await fixture(t);await f.save();assert.deepEqual(await f.save(),{ok:true,revision:1,unchanged:true});assert.ok((await saveWorkspacePage(f.db,f.owner,f.pageId,{workspaceId:'a',expectedRevision:1,title:'Real guide',body:'<p>Keep this content.</p>'})).ok);assert.ok((await f.save({expectedRevision:1,clientId:null,projectId:null})).ok);const view=await getPageRecordContext(f.db,f.owner,f.pageId);assert.equal(view.client,null);assert.equal(view.project,null);assert.equal(view.revision,2);assert.equal((await getWorkspacePage(f.db,f.owner,f.pageId)).body,'<p>Keep this content.</p>');assert.equal((await listRecordPages(f.db,f.owner,{kind:'client',recordId:'james'})).items.length,0);});
test('concurrent changed context has one winner and explicit conflict',async t=>{const f=await fixture(t);await f.save();const result=await Promise.all([f.save({expectedRevision:1,projectId:null}),f.save({expectedRevision:1,clientId:'lawrence',projectId:null})]);assert.equal(result.filter(r=>r.ok).length,1);assert.equal(result.filter(r=>r.reason==='conflict').length,1);assert.equal((await getPageRecordContext(f.db,f.owner,f.pageId)).revision,2);});
test('Client and Project must be related and current in the same workspace',async t=>{const f=await fixture(t);for(const patch of [{clientId:'lawrence'},{clientId:'foreign-client'},{projectId:'missing'},{clientId:null},{workspaceId:'b'},{userId:'ary'}])assert.equal((await f.save(patch)).ok,false);assert.equal(all(f.raw,'SELECT * FROM bloomops_page_contexts').length,0);assert.equal((await f.save({projectId:null})).ok,true);});
test('only Page administrators manage context; linked records never grant Page access',async t=>{const f=await fixture(t);await f.save();for(const user of ['pm','sam','james','foreign'])assert.equal((await f.save({},await f.actor(user))).ok,false);const pm=await f.actor('pm');assert.equal(await getPageRecordContext(f.db,pm,f.pageId),null);assert.equal((await listRecordPages(f.db,pm,{kind:'client',recordId:'james'})).items.length,0);await f.grant('pm','edit');assert.ok(await getPageRecordContext(f.db,pm,f.pageId));assert.equal((await f.save({projectId:null},pm)).ok,false);});
test('shared Page never grants record access and portal links independently respect visibility',async t=>{const f=await fixture(t);await f.save();await f.grant('sam');await f.grant('james');const sam=await f.actor('sam'),client=await f.actor('james');let view=await getPageRecordContext(f.db,sam,f.pageId);assert.equal(view.client,null);assert.equal(view.project,null);view=await getPageRecordContext(f.db,client,f.pageId);assert.equal(view.client.id,'james');assert.equal(view.client.href,'/portal');assert.equal(view.project,null);assert.equal(view.canManage,false);run(f.raw,"UPDATE projects SET visibility='client',revision=revision+1 WHERE id=?",f.projectId);view=await getPageRecordContext(f.db,client,f.pageId);assert.equal(view.project.href,'/portal/projects/'+f.projectId);run(f.raw,"UPDATE projects SET visibility='internal',revision=revision+1 WHERE id=?",f.projectId);assert.equal((await getPageRecordContext(f.db,client,f.pageId)).project,null);assert.equal(await listRecordPages(f.db,client,{kind:'client',recordId:'james'}),null);});
test('revoked membership and Page permissions deny metadata, options and writes',async t=>{const f=await fixture(t);await f.save();await f.grant('pm');const pm=await f.actor('pm');assert.ok(await getPageRecordContext(f.db,pm,f.pageId));await f.grant('pm','none');assert.equal(await getPageRecordContext(f.db,pm,f.pageId),null);run(f.raw,"UPDATE workspace_memberships SET status='suspended' WHERE id='m-ellen'");assert.equal(await getPageRecordContext(f.db,f.owner,f.pageId),null);assert.equal(await pageRecordOptions(f.db,f.owner,f.pageId),null);assert.equal((await f.save({expectedRevision:1,projectId:null})).ok,false);});
test('ignored writes leave no context activity and failures roll back the source',async t=>{const f=await fixture(t);run(f.raw,'CREATE TRIGGER ignore_context BEFORE INSERT ON bloomops_page_contexts BEGIN SELECT RAISE(IGNORE); END');assert.equal((await f.save()).reason,'conflict');assert.equal(one(f.raw,"SELECT count(*) n FROM activity_events WHERE event_type='PAGE_CONTEXT_CHANGED'").n,0);run(f.raw,'DROP TRIGGER ignore_context');run(f.raw,"CREATE TRIGGER reject_context_activity BEFORE INSERT ON activity_events WHEN NEW.event_type='PAGE_CONTEXT_CHANGED' BEGIN SELECT RAISE(ABORT,'injected context activity failure'); END");await assert.rejects(f.save(),/injected/);assert.equal(all(f.raw,'SELECT * FROM bloomops_page_contexts').length,0);});
test('native schema relationships reject foreign/mismatched parents without changing shipped rows',async t=>{const f=await fixture(t);await f.save();for(const set of ["workspace_id='b'","client_id='lawrence'","client_id=NULL","project_id='missing'","revision=0"])assert.throws(()=>run(f.raw,'UPDATE bloomops_page_contexts SET '+set+' WHERE page_id=?',f.pageId),/FOREIGN KEY|CHECK/);assert.equal(all(f.raw,'PRAGMA foreign_key_check').length,0);});
test('searchable choices are bounded and exclude unsupported Client/Project pairs',async t=>{const f=await fixture(t);const clients=await pageRecordOptions(f.db,f.owner,f.pageId,{search:'james'});assert.deepEqual(clients.items,[{id:'james',name:'james'}]);assert.equal((await pageRecordOptions(f.db,f.owner,f.pageId,{kind:'project',clientId:'lawrence'})).items.length,0);assert.equal((await pageRecordOptions(f.db,f.owner,f.pageId,{kind:'project',clientId:'james'})).items[0].id,f.projectId);assert.equal(await pageRecordOptions(f.db,f.owner,f.pageId,{search:9}),null);});
test('record pagination filters hidden Pages before applying limits',async t=>{const f=await fixture(t);for(let n=0;n<24;n++){
 const page=(await createWorkspacePage(f.db,f.owner,{workspaceId:'a',requestId:crypto.randomUUID()})).id;
 assert.ok((await saveWorkspacePage(f.db,f.owner,page,{workspaceId:'a',expectedRevision:1,title:(n<3?'A hidden ':'B visible ')+String(n).padStart(2,'0'),body:''})).ok);
 assert.ok((await savePageRecordContext(f.db,f.owner,page,{workspaceId:'a',userId:'ellen',expectedRevision:0,clientId:'james',projectId:null})).ok);
 if(n>=3){const s=await getPageSharing(f.db,f.owner,page);assert.ok((await updatePageSharing(f.db,f.owner,page,{workspaceId:'a',expectedTreeRevision:s.revision,kind:'grant',membershipId:'m-pm',permission:'view'})).ok);}
 }const pm=await f.actor('pm'),a=await listRecordPages(f.db,pm,{kind:'client',recordId:'james'}),b=await listRecordPages(f.db,pm,{kind:'client',recordId:'james',page:2});assert.equal(a.items.length,20);assert.equal(a.more,true);assert.equal(b.items.length,1);assert.equal(b.more,false);assert.equal(new Set([...a.items,...b.items].map(p=>p.id)).size,21);assert.ok([...a.items,...b.items].every(p=>p.title.startsWith('B visible')));
});
test('membership change just before the write leaves neither context nor history',async t=>{const f=await fixture(t),batch=f.db.batch.bind(f.db);f.db.batch=async statements=>{if(statements[0].toSQL().sql.startsWith('insert into "bloomops_page_contexts"'))run(f.raw,"UPDATE workspace_memberships SET status='suspended' WHERE id='m-ellen'");return batch(statements);};assert.equal((await f.save()).reason,'not_found');assert.equal(all(f.raw,'SELECT * FROM bloomops_page_contexts').length,0);assert.equal(one(f.raw,"SELECT count(*) n FROM activity_events WHERE event_type='PAGE_CONTEXT_CHANGED'").n,0);});
