import {test} from 'node:test';
import assert from 'node:assert/strict';
import {testDb,run,one,all} from './_bloomops-db.mjs';
import {getWorkspacePageTree,moveWorkspacePage} from '../lib/bloomops/page-hierarchy.mjs';
import {createWorkspacePage,saveWorkspacePage,getWorkspacePage} from '../lib/bloomops/pages.mjs';
function fixture(c){const t=testDb();c.after(()=>t.raw.close());for(const id of ['w','other'])run(t.raw,'INSERT INTO workspaces(id,name,slug) VALUES(?,?,?)',id,id,id);run(t.raw,"INSERT INTO user(id,name,email) VALUES('u','Owner','owner@example.test')");run(t.raw,"INSERT INTO workspace_memberships(id,workspace_id,user_id,role,status) VALUES('m','w','u','owner','active')");t.actor={workspaceId:'w',membershipId:'m',userId:'u',role:'owner',status:'active'};t.tree=()=>getWorkspacePageTree(t.db,t.actor);t.create=async(parentId=null)=>createWorkspacePage(t.db,t.actor,{workspaceId:'w',requestId:crypto.randomUUID(),parentId,expectedTreeRevision:(await t.tree()).revision});t.move=async(id,parentId=null,beforeId=null)=>moveWorkspacePage(t.db,t.actor,id,{workspaceId:'w',parentId,beforeId,expectedTreeRevision:(await t.tree()).revision});return t;}
test('nesting and explicit reorder preserve body, title and document revision',async c=>{const t=fixture(c),a=await t.create(),b=await t.create(),child=await t.create(a.id);await saveWorkspacePage(t.db,t.actor,child.id,{workspaceId:'w',expectedRevision:1,title:'Keep me',body:'<p>Exact body</p>'});const before=await getWorkspacePage(t.db,t.actor,child.id);assert.ok((await t.move(child.id,b.id)).ok);assert.ok((await t.move(b.id,null,a.id)).ok);assert.deepEqual(await getWorkspacePage(t.db,t.actor,child.id),before);const tree=await t.tree();assert.deepEqual(tree.rows.filter(r=>!r.parent_id).map(r=>r.id),[b.id,a.id]);assert.equal(tree.rows.find(r=>r.id===child.id).parent_id,b.id);assert.equal(tree.revision,5);assert.ok(tree.rows.every(r=>!('body' in r)));assert.equal(all(t.raw,"SELECT * FROM activity_events WHERE event_type='PAGE_MOVED'").length,2);});
test('five levels allowed; sixth and subtree overflow rejected',async c=>{const t=fixture(c);let parent=null;const ids=[];for(let i=0;i<5;i++){const made=await t.create(parent);assert.ok(made.ok);ids.push(made.id);parent=made.id;}assert.equal((await t.create(parent)).reason,'invalid');const root=await t.create(),child=await t.create(root.id);assert.equal((await t.move(root.id,ids[3])).reason,'invalid');assert.ok((await t.move(root.id,ids[2])).ok);assert.ok((await t.move(child.id)).ok);});
test('reject self, descendant cycle, foreign/missing destination and wrong sibling',async c=>{const t=fixture(c),a=await t.create(),b=await t.create(a.id),other=await t.create();for(const [id,parent,before] of [[a.id,a.id,null],[a.id,b.id,null],[a.id,crypto.randomUUID(),null],[a.id,null,b.id],[a.id,null,a.id]])assert.equal((await t.move(id,parent,before)).reason,'invalid');assert.equal((await t.tree()).revision,3);assert.ok((await t.move(b.id,null,other.id)).ok);});
test('stale create and move cannot change the tree',async c=>{const t=fixture(c),a=await t.create(),stale=(await t.tree()).revision;await t.create();assert.equal((await moveWorkspacePage(t.db,t.actor,a.id,{workspaceId:'w',parentId:null,beforeId:null,expectedTreeRevision:stale})).reason,'conflict');assert.equal((await createWorkspacePage(t.db,t.actor,{workspaceId:'w',requestId:crypto.randomUUID(),parentId:a.id,expectedTreeRevision:stale})).reason,'conflict');assert.equal((await t.tree()).rows.length,2);});
test('opposing concurrent moves serialize and cannot create a cycle',async c=>{const t=fixture(c),a=await t.create(),b=await t.create(),version=(await t.tree()).revision;const input=parentId=>({workspaceId:'w',parentId,beforeId:null,expectedTreeRevision:version});const results=await Promise.all([moveWorkspacePage(t.db,t.actor,a.id,input(b.id)),moveWorkspacePage(t.db,t.actor,b.id,input(a.id))]);assert.equal(results.filter(r=>r.ok).length,1);assert.equal(results.filter(r=>r.reason==='conflict').length,1);assert.equal((await t.tree()).rows.filter(r=>r.parent_id).length,1);});
test('create replay returns original child after hierarchy changes',async c=>{const t=fixture(c),a=await t.create(),input={workspaceId:'w',requestId:crypto.randomUUID(),parentId:a.id,expectedTreeRevision:1},made=await createWorkspacePage(t.db,t.actor,input);await t.move(made.id);assert.equal((await createWorkspacePage(t.db,t.actor,input)).id,made.id);assert.equal((await t.tree()).rows.length,2);});
test('content save and hierarchy move both succeed independently',async c=>{const t=fixture(c),a=await t.create(),b=await t.create();const results=await Promise.all([t.move(a.id,b.id),saveWorkspacePage(t.db,t.actor,a.id,{workspaceId:'w',expectedRevision:1,title:'Concurrent writing',body:'<p>Retained</p>'})]);assert.ok(results.every(r=>r.ok));assert.equal((await getWorkspacePage(t.db,t.actor,a.id)).revision,2);assert.equal((await t.tree()).rows.find(r=>r.id===a.id).parent_id,b.id);});
for(const role of ['project_manager','team_member','client'])test(role+' cannot read hierarchy or move/create children',async c=>{const t=fixture(c),a=await t.create();run(t.raw,"UPDATE workspace_memberships SET role=? WHERE id='m'",role);assert.equal(await t.tree(),null);assert.equal((await moveWorkspacePage(t.db,t.actor,a.id,{workspaceId:'w',parentId:null,beforeId:null,expectedTreeRevision:1})).reason,'not_found');assert.equal((await createWorkspacePage(t.db,t.actor,{workspaceId:'w',requestId:crypto.randomUUID()})).reason,'not_found');});
for(const change of ["UPDATE workspace_memberships SET status='suspended' WHERE id='m'","UPDATE workspaces SET status='archived' WHERE id='w'"])test('authority lost just before move transaction: '+change,async c=>{const t=fixture(c),a=await t.create(),b=await t.create(),batch=t.db.batch.bind(t.db);let calls=0;t.db.batch=async s=>{if(++calls===2)run(t.raw,change);return batch(s);};assert.equal((await moveWorkspacePage(t.db,t.actor,a.id,{workspaceId:'w',parentId:b.id,beforeId:null,expectedTreeRevision:2})).reason,'not_found');assert.equal(one(t.raw,'SELECT parent_id FROM bloomops_page_locations WHERE page_id=?',a.id).parent_id,null);assert.equal(one(t.raw,'SELECT revision FROM bloomops_page_trees').revision,2);});
test('foreign workspace reads are empty and SQL prevents cross-workspace parent',async c=>{const t=fixture(c),a=await t.create(),foreignId=crypto.randomUUID();run(t.raw,"INSERT INTO bloomops_pages(id,workspace_id,creation_request_id,title,body,revision,created_at,updated_at) VALUES(?,'other',?,'Foreign','',1,'now','now')",foreignId,crypto.randomUUID());assert.equal(await getWorkspacePageTree(t.db,{...t.actor,workspaceId:'other'}),null);assert.equal((await t.move(a.id,foreignId)).reason,'invalid');assert.throws(()=>run(t.raw,'UPDATE bloomops_page_locations SET parent_id=? WHERE page_id=?',foreignId,a.id),/FOREIGN KEY/);});
test('activity failure rolls back positions and hierarchy revision',async c=>{const t=fixture(c),a=await t.create(),b=await t.create();run(t.raw,"CREATE TRIGGER reject_move BEFORE INSERT ON activity_events WHEN NEW.event_type='PAGE_MOVED' BEGIN SELECT RAISE(ABORT,'injected'); END");const before=await t.tree();await assert.rejects(t.move(a.id,b.id),/injected/);assert.deepEqual(await t.tree(),before);});
test('strict hierarchy inputs reject without side effects',async c=>{const t=fixture(c),a=await t.create(),input={workspaceId:'w',parentId:null,beforeId:null,expectedTreeRevision:1};for(const patch of [{workspaceId:'other'},{parentId:12},{beforeId:'invalid'},{expectedTreeRevision:-1},{expectedTreeRevision:1.5},{visibility:'public'}])assert.equal((await moveWorkspacePage(t.db,t.actor,a.id,{...input,...patch})).reason,'invalid');assert.equal((await t.tree()).revision,1);});
