import {test} from 'node:test';
import assert from 'node:assert/strict';
import {deliveryFixture} from './_prospect-delivery-fixture.mjs';
import {run,all,one} from './_bloomops-db.mjs';
import {previewProspectConversion} from '../lib/bloomops/prospect-conversion-preview.mjs';
import {convertProspect} from '../lib/bloomops/prospect-conversions.mjs';
import {getRecipientProtection} from '../lib/bloomops/prospect-recipient-protection.mjs';
import {prepareProspectDelivery,sendProspectIntroduction,getProspectDelivery} from '../lib/bloomops/prospect-delivery.mjs';
import {createProspect,updateProspect} from '../lib/bloomops/prospects.mjs';
import {saveProspectOutreach,approveProspectOutreach} from '../lib/bloomops/prospect-outreach.mjs';
async function fixture(c){const t=await deliveryFixture(c);run(t.raw,"INSERT INTO service_types(id,workspace_id,name,slug) VALUES('sale-service','fresh','Purchased service','purchased-service')");run(t.raw,"INSERT INTO bloomops_clients(id,workspace_id,name,slug) VALUES('sale-client','fresh','Existing client','existing-client')");run(t.raw,"INSERT INTO client_contacts(id,workspace_id,client_id,name,email,is_primary) VALUES('sale-contact','fresh','sale-client','Buyer','buyer@example.test',1)");t.selection={workspaceId:'fresh',mode:'existing',clientId:'sale-client',serviceTypeId:'sale-service',scopeNotes:'Confirmed purchased work.'};t.command=async()=>{const result=await previewProspectConversion(t.db,t.actor,t.id,t.selection);assert.ok(result.ok);return {...t.selection,requestId:crypto.randomUUID(),reviewHash:result.conversionReview.hash,confirmed:true};};t.convert=command=>convertProspect(t.db,t.actor,t.id,command);return t;}
async function duplicate(t,recipient=t.fields.recipient){const {prospectId}=await createProspect(t.db,{actor:t.actor,input:{workspaceId:'fresh',requestId:crypto.randomUUID(),fields:{businessName:'Other prospect',publicEmail:recipient,timeZone:'UTC',fit:'strong',observedFacts:'Synthetic reviewed address.',evidenceDate:'2026-09-13',evidenceTarget:'https://example.test',proposedWork:'Synthetic test.'}}});await updateProspect(t.db,{actor:t.actor,id:prospectId,input:{workspaceId:'fresh',expectedRevision:1,fields:{publicEmail:recipient},sources:{publicEmail:{url:'https://example.test/contact',checked:true}}}});const common={workspaceId:'fresh',prospectId,expectedRevision:0,expectedProfileRevision:2,expectedSenderRevision:1};assert.ok((await saveProspectOutreach(t.db,t.actor,{...common,sourceResultId:null,fields:{...t.fields,recipient,timeZone:'UTC'}})).saved);assert.ok((await approveProspectOutreach(t.db,t.actor,{...common,expectedRevision:1,reviewed:true})).approved);return {workspaceId:'fresh',prospectId,approvalId:one(t.raw,'SELECT id FROM prospect_outreach_approvals WHERE draft_id IN (SELECT id FROM prospect_outreach_drafts WHERE prospect_id=?)',prospectId).id};}
test('converted prospect cannot prepare a first delivery or expose a send action',async c=>{const t=await fixture(c),result=await t.convert(await t.command());assert.ok(result.ok);assert.ok((await prepareProspectDelivery(t.db,t.actor,t.prepare)).conflict);const view=await getProspectDelivery(t.db,t.actor,t.env,t.id);assert.equal(view.canSend,false);assert.equal(view.recipientProtection.kind,'stopped');assert.equal(all(t.raw,'SELECT * FROM prospect_deliveries').length,0);});
test('a prepared delivery cannot submit after conversion, including direct SQL bypass attempts',async c=>{const t=await fixture(c);await t.ready();assert.ok((await t.convert(await t.command())).ok);let calls=0;assert.ok((await sendProspectIntroduction(t.db,t.actor,t.env,t.session,{...t.input,reviewed:true},{fetcher:async()=>{calls++;throw Error('Forbidden provider request');}})).conflict);assert.equal(calls,0);assert.throws(()=>run(t.raw,"UPDATE prospect_deliveries SET state='submitting',attempted_at=CURRENT_TIMESTAMP,account_email='hello@example.test' WHERE prospect_id=?",t.id),/permanently stopped/);});
test('immutable delivery and contact addresses remain stopped after a prospect edit',async c=>{const t=await fixture(c);await t.ready();run(t.raw,"UPDATE bloomops_prospects SET public_email='changed@example.test',revision=revision+1 WHERE id=?",t.id);assert.ok((await t.convert(await t.command())).ok);for(const email of ['changed@example.test','inbox@example.test','buyer@example.test'])assert.equal((await getRecipientProtection(t.db,t.actor,email)).kind,'stopped');});
for(const state of ['submitting','uncertain'])test(state+' delivery blocks conversion without orphan records',async c=>{const t=await fixture(c);await t.ready();run(t.raw,"UPDATE prospect_deliveries SET state='submitting',attempted_at=CURRENT_TIMESTAMP,account_email='hello@example.test' WHERE prospect_id=?",t.id);if(state==='uncertain')run(t.raw,"UPDATE prospect_deliveries SET state='uncertain' WHERE prospect_id=?",t.id);assert.equal((await t.convert(await t.command())).ok,false);assert.equal(all(t.raw,'SELECT * FROM prospect_conversions').length,0);assert.equal(all(t.raw,'SELECT * FROM service_engagements').length,0);});
test('duplicate address protection blocks preparation and previously prepared delivery',async c=>{const t=await fixture(c),target=await duplicate(t),prepared=await prepareProspectDelivery(t.db,t.actor,target);assert.ok(prepared.prepared);const unsent=await duplicate(t);assert.ok((await t.convert(await t.command())).ok);assert.ok((await prepareProspectDelivery(t.db,t.actor,unsent)).conflict);let calls=0;const sent=await sendProspectIntroduction(t.db,t.actor,{...t.env,BLOOMOPS_GOOGLE_TEST_DELIVERY_ID:prepared.deliveryId},t.session,{workspaceId:'fresh',prospectId:target.prospectId,deliveryId:prepared.deliveryId,reviewed:true},{fetcher:async()=>{calls++;throw Error('Forbidden provider request');}});assert.ok(sent.conflict);assert.equal(calls,0);});
test('a duplicate address claimed immediately before conversion is guarded inside the transaction',async c=>{const t=await fixture(c),target=await duplicate(t);assert.ok((await prepareProspectDelivery(t.db,t.actor,target)).prepared);const command=await t.command(),batch=t.db.batch.bind(t.db);t.db.batch=async statements=>{run(t.raw,"UPDATE prospect_deliveries SET state='submitting',attempted_at=CURRENT_TIMESTAMP,account_email='hello@example.test' WHERE prospect_id=?",target.prospectId);return batch(statements);};assert.equal((await t.convert(command)).ok,false);assert.equal(all(t.raw,'SELECT * FROM prospect_conversions').length,0);assert.equal(all(t.raw,'SELECT * FROM service_engagements').length,0);});
