import {test} from 'node:test';
import './_jsx.mjs';
import assert from 'node:assert/strict';
import {setup} from './_work-projections.mjs';
import {all,run,APP_URL} from './_bloomops-db.mjs';
import {onboardingSetup,installOnboardingDefaults} from '../lib/bloomops/onboarding-setup.mjs';
const command={workspaceId:'a',userId:'ellen',categories:['common','ghl']};
test('onboarding setup installs selected canonical defaults once and leaves unselected categories alone',async ctx=>{const t=await setup();ctx.after(()=>t.raw.close());run(t.raw,'DELETE FROM template_versions');run(t.raw,'DELETE FROM templates');
 const result=await installOnboardingDefaults(t.db,t.owner,command);assert.ok(result.complete);assert.equal(result.items.find(i=>i.slug==='social').state,'missing');const before=all(t.raw,'SELECT * FROM template_versions');
 assert.equal(before.length,2);await Promise.all([installOnboardingDefaults(t.db,t.owner,command),installOnboardingDefaults(t.db,t.owner,command)]);assert.deepEqual(all(t.raw,'SELECT * FROM template_versions'),before);
 assert.equal(all(t.raw,'SELECT * FROM onboarding_instances').length,0);
});
 test('onboarding setup denies portal, preview, foreign scope, revoked roles and stale capabilities',async ctx=>{const t=await setup();ctx.after(()=>t.raw.close());for(const actor of [{...t.owner,preview:true},{...t.owner,role:'client'},{...t.owner,userId:'sam',membershipId:'m-sam',role:'team_member',capabilities:new Set(['templates.manage'])}])assert.equal((await onboardingSetup(t.db,actor)).ok,false);
 assert.equal((await installOnboardingDefaults(t.db,t.owner,{...command,workspaceId:'b'})).ok,false);run(t.raw,"UPDATE workspace_memberships SET status='suspended' WHERE id='m-ellen'");assert.equal((await installOnboardingDefaults(t.db,t.owner,command)).ok,false);
});
test('setup preserves every existing version and rolls back new template on version failure',async ctx=>{const t=await setup();ctx.after(()=>t.raw.close());await installOnboardingDefaults(t.db,t.owner,command);const before=all(t.raw,'SELECT * FROM template_versions');assert.equal(before.length,2);await installOnboardingDefaults(t.db,t.owner,command);assert.deepEqual(all(t.raw,'SELECT * FROM template_versions'),before);
 run(t.raw,'DELETE FROM template_versions');run(t.raw,'DELETE FROM templates');run(t.raw,"CREATE TRIGGER refuse_setup BEFORE INSERT ON template_versions BEGIN SELECT RAISE(ABORT,'synthetic refusal'); END");await assert.rejects(installOnboardingDefaults(t.db,t.owner,command));assert.equal(all(t.raw,'SELECT * FROM templates').length,0);
});
test('setup HTTP uses real sessions, current permissions, origin and explicit scope',async ctx=>{const t=await setup({auth:true});ctx.after(()=>t.raw.close());globalThis[Symbol.for('__cloudflare-context__')]={env:t.env,cf:{},ctx:{}};const route=await import('../app/api/bloomops/onboarding/setup/route.js');
 const call=async(user,method='GET',body=command,origin=APP_URL)=>{const cookie=user?(await t.signIn(user+'@example.com')).cookie:null;return route[method](new Request(APP_URL+'/api/bloomops/onboarding/setup',{method,headers:{...(cookie?{cookie}:{}),origin,'content-type':'application/json'},...(method==='POST'?{body:JSON.stringify(body)}:{})}));};
 assert.equal((await call(null)).status,401);for(const user of ['james','sam'])assert.equal((await call(user)).status,404);
 const read=await call('ellen');assert.equal(read.status,200);assert.equal(read.headers.get('cache-control'),'no-store');
 assert.equal((await call('ellen','POST',command,'https://foreign.invalid')).status,403);assert.equal((await call('ellen','POST',{...command,workspaceId:'b'})).status,404);assert.equal((await call('ellen','POST',command)).status,200);
});

test('reviewed template recovery creates immutable drafts, publishes explicitly and never silently enables',async ctx=>{
 const {manageOnboardingSetup}=await import('../lib/bloomops/onboarding-setup.mjs');
 const t=await setup();ctx.after(()=>t.raw.close());await installOnboardingDefaults(t.db,t.owner,command);
 let state=await onboardingSetup(t.db,t.owner),item=state.items.find(i=>i.slug==='common');
 const original=all(t.raw,'SELECT * FROM template_versions WHERE template_id=?',item.templateId);
 const definition=structuredClone(item.versions[0].definition);definition.items[0].instructions='Synthetic reviewed requirement.';
 const action=(i,patch)=>manageOnboardingSetup(t.db,t.owner,{workspaceId:'a',userId:'ellen',slug:i.slug,reviewToken:i.reviewToken,...patch});
 state=await action(item,{action:'save_version',definition});assert.ok(state.ok);item=state.items.find(i=>i.slug==='common');assert.equal(item.versions[0].status,'draft');assert.deepEqual(all(t.raw,'SELECT * FROM template_versions WHERE id=?',original[0].id),original);
 const stale=item;
 state=await action(item,{action:'publish',versionId:item.versions[0].id});assert.ok(state.ok);item=state.items.find(i=>i.slug==='common');assert.equal(item.versions[0].status,'published');assert.equal(item.versions[1].status,'retired');assert.equal((await action(stale,{action:'save_version',definition})).reason,'conflict');
 run(t.raw,'UPDATE templates SET active=0 WHERE id=?',item.templateId);state=await onboardingSetup(t.db,t.owner);item=state.items.find(i=>i.slug==='common');assert.equal(item.state,'inactive');
 const versions=all(t.raw,'SELECT * FROM template_versions WHERE template_id=?',item.templateId);state=await action(item,{action:'enable'});assert.ok(state.ok);assert.equal(state.items.find(i=>i.slug==='common').state,'published');assert.deepEqual(all(t.raw,'SELECT * FROM template_versions WHERE template_id=?',item.templateId),versions);
 assert.equal(all(t.raw,'SELECT * FROM client_activations').length,0);
});
test('template recovery rejects stale scope, invalid definitions and revoked managers',async ctx=>{
 const {manageOnboardingSetup}=await import('../lib/bloomops/onboarding-setup.mjs');const t=await setup();ctx.after(()=>t.raw.close());await installOnboardingDefaults(t.db,t.owner,command);
 const item=(await onboardingSetup(t.db,t.owner)).items.find(i=>i.slug==='common');const input={workspaceId:'a',userId:'ellen',slug:'common',reviewToken:item.reviewToken,action:'save_version',definition:{}};
 assert.equal((await manageOnboardingSetup(t.db,t.owner,input)).reason,'invalid_definition');assert.equal((await manageOnboardingSetup(t.db,t.owner,{...input,workspaceId:'b'})).ok,false);
 run(t.raw,"UPDATE workspace_memberships SET status='suspended' WHERE id='m-ellen'");assert.equal((await manageOnboardingSetup(t.db,t.owner,input)).ok,false);
});
