import {test} from 'node:test';
import assert from 'node:assert/strict';
import {setup} from './_work-projections.mjs';
import {run,all} from './_bloomops-db.mjs';
import {input,draft} from './_client-report-fixture.mjs';
import {saveClientReport as save} from '../lib/bloomops/client-reports.mjs';
import {changeReportPublication as publish,getPublishedReport,reportPublicationReview,listPublishedReports} from '../lib/bloomops/client-report-publications.mjs';
import {checkReportPublications} from './_client-report-publications.mjs';
const command=()=>({workspaceId:'a',userId:'ellen',requestId:crypto.randomUUID(),expectedRevision:1,expectedSequence:0,kind:'publish',acknowledgeUnverified:true});
test('publication freezes saved data, retries once, revisions preserve history and withdrawal removes client access',async t=>{const x=await setup();t.after(()=>x.raw.close());await checkReportPublications(x.db,x.owner,await x.actor('james'));});
test('publication requires review, public narrative, current recipient and actual edit authority',async t=>{const x=await setup();t.after(()=>x.raw.close());let created=await save(x.db,x.owner,'james',null,input());
 assert.equal((await publish(x.db,x.owner,'james',created.id,command())).reason,'invalid');
 created=await save(x.db,x.owner,'james',null,input({draft:draft({clientSummary:'Ready'})}));
 assert.equal((await publish(x.db,x.owner,'james',created.id,{...command(),acknowledgeUnverified:false})).reason,'invalid');
 for(const who of ['james','sam','foreign'])assert.equal((await publish(x.db,await x.actor(who),'james',created.id,command())).reason,'not_found');
 assert.equal((await publish(x.db,{...x.owner,preview:true},'james',created.id,command())).reason,'not_found');
 for(const patch of [{workspaceId:'b'},{userId:'foreign'},{snapshotJson:'spoof'},{actorMembershipId:'m-foreign'}])assert.equal((await publish(x.db,x.owner,'james',created.id,{...command(),...patch})).reason,'not_found');
 run(x.raw,"UPDATE workspace_memberships SET status='suspended' WHERE id='m-james'");assert.equal((await publish(x.db,x.owner,'james',created.id,command())).reason,'invalid');assert.equal(all(x.raw,'SELECT * FROM client_report_publications').length,0);
});
test('publication enforces immutable ledger, tenant parent tuples and zero-row writes',async t=>{const x=await setup();t.after(()=>x.raw.close());const created=await save(x.db,x.owner,'james',null,input({draft:draft({clientSummary:'Ready'})}));
 run(x.raw,"CREATE TRIGGER publication_ignore BEFORE INSERT ON client_report_publications BEGIN SELECT RAISE(IGNORE); END");assert.equal((await publish(x.db,x.owner,'james',created.id,command())).reason,'conflict');assert.equal(all(x.raw,'SELECT * FROM client_report_publications').length,0);run(x.raw,'DROP TRIGGER publication_ignore');
 assert.ok((await publish(x.db,x.owner,'james',created.id,command())).ok);
 assert.throws(()=>run(x.raw,"UPDATE client_report_publications SET snapshot_json='{}'"),/immutable/);assert.throws(()=>run(x.raw,'DELETE FROM client_report_publications'),/immutable/);
 const row=all(x.raw,'SELECT * FROM client_report_publications')[0];for(const patch of [{workspace_id:'b'},{actor_membership_id:'m-foreign'}]){const v={...row,id:crypto.randomUUID(),sequence:2,request_id:crypto.randomUUID(),...patch};assert.throws(()=>run(x.raw,`INSERT INTO client_report_publications(${Object.keys(v).join(',')}) VALUES(${Object.keys(v).map(()=>'?').join(',')})`,...Object.values(v)),/FOREIGN KEY/);}
});
test('client release queries recheck contact and membership, hide other Clients and preserve authorized owner view',async t=>{const x=await setup();t.after(()=>x.raw.close());const created=await save(x.db,x.owner,'james',null,input({draft:draft({clientSummary:'Ready'})})),released=await publish(x.db,x.owner,'james',created.id,command()),client=await x.actor('james');
 assert.ok(await getPublishedReport(x.db,client,released.id,{portal:true}));for(const who of ['lawrence','foreign','ellen'])assert.equal(await getPublishedReport(x.db,await x.actor(who),released.id,{portal:true}),null);
 run(x.raw,"UPDATE client_contacts SET user_id=NULL WHERE id='c-james'");assert.equal(await getPublishedReport(x.db,client,released.id,{portal:true}),null);assert.equal((await listPublishedReports(x.db,client,{portal:true})).items.length,0);assert.ok(await getPublishedReport(x.db,x.owner,released.id));
 run(x.raw,"UPDATE workspace_memberships SET status='suspended' WHERE id='m-ellen'");assert.equal(await reportPublicationReview(x.db,x.owner,'james',created.id),null);assert.equal((await publish(x.db,x.owner,'james',created.id,{...command(),expectedSequence:1,kind:'withdraw'})).reason,'not_found');
});
