import {test} from 'node:test';
import assert from 'node:assert/strict';
import {testDb,run,one,all} from './_bloomops-db.mjs';
import {createWorkspacePage,getWorkspacePage,saveWorkspacePage} from '../lib/bloomops/pages.mjs';
import {getWorkspacePageTree} from '../lib/bloomops/page-hierarchy.mjs';
import {updatePageSharing} from '../lib/bloomops/page-sharing.mjs';
import {readPageRecovery} from '../lib/bloomops/page-recovery.mjs';
function fixture(c){
 const t=testDb();c.after(()=>t.raw.close());for(const id of ['w','other'])run(t.raw,'INSERT INTO workspaces(id,name,slug) VALUES(?,?,?)',id,id,id);
 t.actors={};for(const [id,role] of [['owner','owner'],['member','team_member'],['client','client']]){run(t.raw,'INSERT INTO user(id,name,email) VALUES(?,?,?)',id,id,id+'@example.test');run(t.raw,"INSERT INTO workspace_memberships(id,workspace_id,user_id,role,status) VALUES(?,'w',?,?,'active')",id,id,role);t.actors[id]={workspaceId:'w',membershipId:id,userId:id,role,status:'active'};}
 run(t.raw,"INSERT INTO bloomops_clients(id,workspace_id,name,slug) VALUES('client','w','Client','client')");run(t.raw,"INSERT INTO client_contacts(id,workspace_id,client_id,name,user_id) VALUES('contact','w','client','Client','client')");
 t.tree=()=>getWorkspacePageTree(t.db,t.actors.owner);t.create=async(parentId=null)=>(await createWorkspacePage(t.db,t.actors.owner,{workspaceId:'w',requestId:crypto.randomUUID(),parentId,expectedTreeRevision:(await t.tree()).revision})).id;
 t.grant=async(id,membershipId,permission)=>updatePageSharing(t.db,t.actors.owner,id,{workspaceId:'w',kind:'grant',membershipId,permission,expectedTreeRevision:(await t.tree()).revision});
 t.read=(who,id,input={userId:who,workspaceId:'w'})=>readPageRecovery(t.db,t.actors[who],id,input);
 t.save=(who,id,patch={})=>saveWorkspacePage(t.db,t.actors[who],id,{workspaceId:'w',userId:who,expectedRevision:1,title:'Guide',body:'<p>Exact <strong>content</strong></p>',...patch});
 t.data=()=>({pages:all(t.raw,'SELECT * FROM bloomops_pages'),events:all(t.raw,'SELECT * FROM activity_events')});return t;
}
test('bound recovery returns canonical editable document without any write',async c=>{const t=fixture(c),id=await t.create();assert.ok((await t.save('owner',id)).ok);const before=t.data(),r=await t.read('owner',id);assert.equal(r.status,200);assert.deepEqual(r.page,await getWorkspacePage(t.db,t.actors.owner,id));assert.equal(r.userId,'owner');assert.deepEqual(t.data(),before);});
test('direct and inherited internal/portal edit grants enable recovery, view/comment do not',async c=>{const t=fixture(c),root=await t.create(),child=await t.create(root),sibling=await t.create();for(const who of ['member','client']){assert.equal((await t.read(who,child)).status,404);for(const permission of ['view','comment']){assert.ok((await t.grant(root,who,permission)).ok);assert.equal((await t.read(who,child)).status,404);}assert.ok((await t.grant(root,who,'edit')).ok);for(const id of [root,child])assert.equal((await t.read(who,id)).status,200);assert.equal((await t.read(who,sibling)).status,404);assert.ok((await t.grant(child,who,'none')).ok);assert.equal((await t.read(who,child)).status,404);}});
test('wrong initiating identity or workspace cannot reveal drafts or save under a replacement account',async c=>{const t=fixture(c),id=await t.create(),before=t.data();for(const input of [{userId:'member',workspaceId:'w'},{userId:'owner',workspaceId:'other'}])assert.equal((await t.read('owner',id,input)).status,403);assert.equal((await t.read('owner',id,{userId:'owner',workspaceId:'w',extra:true})).status,400);assert.equal((await t.save('owner',id,{userId:'member'})).reason,'not_found');assert.equal((await t.save('owner',id,{userId:null})).reason,'not_found');assert.deepEqual(t.data(),before);});
for(const change of ["UPDATE bloomops_page_grants SET permission='view' WHERE membership_id='client'","UPDATE workspace_memberships SET status='suspended' WHERE id='client'","UPDATE client_contacts SET user_id=NULL WHERE id='contact'","UPDATE workspaces SET status='archived' WHERE id='w'"])test('live revoked edit authority blocks recovery and pending writes: '+change,async c=>{const t=fixture(c),id=await t.create();await t.grant(id,'client','edit');assert.equal((await t.read('client',id)).status,200);const batch=t.db.batch.bind(t.db);t.db.batch=async statements=>{run(t.raw,change);return batch(statements);};const before=t.data();assert.equal((await t.save('client',id)).reason,'not_found');assert.equal((await t.read('client',id)).status,404);assert.deepEqual(t.data(),before);});
test('foreign page recovery is indistinguishable from missing and original save callers still work',async c=>{const t=fixture(c),id=await t.create();const other=crypto.randomUUID();run(t.raw,"INSERT INTO bloomops_pages(id,workspace_id,creation_request_id,title,body,revision,created_at,updated_at) VALUES(?,'other',?,'Foreign','Private',1,'now','now')",other,crypto.randomUUID());assert.equal((await t.read('owner',other)).status,404);assert.equal((await t.read('owner',crypto.randomUUID())).status,404);assert.ok((await saveWorkspacePage(t.db,t.actors.owner,id,{workspaceId:'w',expectedRevision:1,title:'Old caller',body:''})).ok);assert.equal(one(t.raw,"SELECT count(*) n FROM activity_events WHERE event_type='PAGE_SAVED'").n,1);});
test('canonical lost reply recovery preserves later input without replaying the committed save',async c=>{
 const {createPageDraftSession}=await import('../lib/bloomops/page-drafts.mjs'),t=fixture(c),id=await t.create(),initial=await getWorkspacePage(t.db,t.actors.owner,id);let release,entered;
 const gate=new Promise(r=>release=r),arrived=new Promise(r=>entered=r),first=createPageDraftSession({initial,delay:100000,save:async input=>{const result=await saveWorkspacePage(t.db,t.actors.owner,id,{...input,userId:'owner',workspaceId:'w'});assert.ok(result.ok);entered();await gate;throw Error('reply lost after actual commit');}});c.after(()=>first.dispose());
 first.edit({body:'<p>Actually committed</p>'});const flight=first.flush();await arrived;first.edit({body:'<p>Typed while waiting</p>'});const copy=first.retained();first.dispose();release();await flight;
 const current=(await t.read('owner',id)).page,second=createPageDraftSession({initial:current,delay:100000,read:async()=>(await t.read('owner',id)).page,save:input=>saveWorkspacePage(t.db,t.actors.owner,id,{...input,userId:'owner',workspaceId:'w'})});c.after(()=>second.dispose());const before=t.data();
 assert.ok(second.restore(copy,current));assert.equal(second.snapshot().revision,2);assert.equal(second.snapshot().error.kind,'recovered');assert.deepEqual(t.data(),before);
 await second.retry();assert.equal(second.snapshot().dirty,false);assert.equal((await t.read('owner',id)).page.body,'<p>Typed while waiting</p>');assert.equal(one(t.raw,"SELECT count(*) n FROM activity_events WHERE event_type='PAGE_SAVED'").n,2);
 await second.retry();assert.equal(one(t.raw,"SELECT count(*) n FROM activity_events WHERE event_type='PAGE_SAVED'").n,2);
});
