'use client';
import {useEffect,useRef,useState} from 'react';
import {PageHeader,Button} from './Primitives';
import {REPORT_TEMPLATES,reportTemplate} from '@/lib/bloomops/client-report-values.mjs';
import ClientReportCsv from './ClientReportCsv';
const emptyMetric=()=>({state:'missing',value:null,sourceNote:'',collectedAt:null});
const draftFields=r=>Object.fromEntries(['title','periodStart','periodEnd','timezone','channel','accountLabel','scopeLabel','commentary','metrics'].map(k=>[k,r[k]]));
export default function ClientReportEditor({client,initial=null,services=null,scope}){
 const [templateId,setTemplate]=useState(initial?.templateId||''),[serviceId,setService]=useState(initial?.serviceEngagementId||'');
 const template=reportTemplate(templateId,initial?.templateVersion||1),[data,setData]=useState(initial?draftFields(initial):{title:'',periodStart:'',periodEnd:'',timezone:'UTC',channel:'',accountLabel:'',scopeLabel:'',commentary:'',metrics:{}});
 const [status,setStatus]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[denied,setDenied]=useState(false),[dirty,setDirty]=useState(false),[isConflict,setConflict]=useState(false);
 const [options,setOptions]=useState(services),[search,setSearch]=useState(''),[optionsBusy,setOptionsBusy]=useState(false);
 const scopeRef=useRef(scope),live=useRef(true),saveGeneration=useRef(0),readGeneration=useRef(0),serviceGeneration=useRef(0),request=useRef(null),pending=useRef(null),dirtyRef=useRef(false);
 const editable=initial?initial.canEdit:true;
 useEffect(()=>{live.current=true;function leave(e){if(dirtyRef.current){e.preventDefault();e.returnValue='';}}document.addEventListener('click',link);function link(e){const a=e.target.closest('a[href]');if(a&&dirtyRef.current&&!window.confirm('Leave this report with unsaved changes?'))e.preventDefault();}
 window.addEventListener('beforeunload',leave);return()=>{live.current=false;saveGeneration.current++;readGeneration.current++;serviceGeneration.current++;document.removeEventListener('click',link);window.removeEventListener('beforeunload',leave);};},[]);
 useEffect(()=>{async function refresh(){const g=++readGeneration.current;try{const res=await fetch(`/api/bloomops/clients/${client.id}/reports${initial?'/'+initial.id:''}`,{cache:'no-store'});const body=await res.json();if(!live.current||g!==readGeneration.current)return;if(!res.ok||body.scope?.userId!==scope.userId||body.scope?.workspaceId!==scope.workspaceId){saveGeneration.current++;setDenied(true);dirtyRef.current=false;setDirty(false);setError('Report access changed. Reopen it in the correct workspace.');}}catch{/* Save rechecks authority; a read failure does not discard unsaved input. */}}
 window.addEventListener('focus',refresh);window.addEventListener('pageshow',refresh);return()=>{readGeneration.current++;window.removeEventListener('focus',refresh);window.removeEventListener('pageshow',refresh);};},[client.id,initial?.id,scope.userId,scope.workspaceId]);
 function change(key,value){dirtyRef.current=true;setDirty(true);setStatus('');setData(d=>({...d,[key]:value}));}
 function metric(key,patch){change('metrics',{...data.metrics,[key]:{...(data.metrics[key]||emptyMetric()),...patch,sourceKind:'manual'}});}
 async function loadServices(page=1){setOptionsBusy(true);setError('');const g=++serviceGeneration.current;try{const res=await fetch(`/api/bloomops/clients/${client.id}/reports?services=true&search=${encodeURIComponent(search)}&page=${page}`,{cache:'no-store'}),body=await res.json();if(!live.current||g!==serviceGeneration.current)return;if(!res.ok||body.scope?.userId!==scope.userId||body.scope?.workspaceId!==scope.workspaceId)throw Error('Could not load authorized services.');setOptions(body);}catch(e){if(live.current&&g===serviceGeneration.current)setError(e.message);}finally{if(live.current&&g===serviceGeneration.current)setOptionsBusy(false);}}
 async function save(e){e.preventDefault();if(busy||denied||isConflict||!editable)return;setBusy(true);setError('');setStatus('Saving…');const g=++saveGeneration.current;
 if(!request.current)request.current=crypto.randomUUID();
 const body=pending.current||{...scopeRef.current,requestId:request.current,expectedRevision:initial?.revision||null,serviceEngagementId:serviceId,templateId,templateVersion:template?.version,draft:data};pending.current=body;
 try{const res=await fetch(`/api/bloomops/clients/${client.id}/reports${initial?'/'+initial.id:''}`,{method:initial?'PUT':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const result=await res.json();if(!live.current||g!==saveGeneration.current)return;
 if(!res.ok){if(res.status===409)setConflict(true);if([401,403,404].includes(res.status)){setDenied(true);dirtyRef.current=false;}if(res.status<500)pending.current=null;throw Error(result.error||'Draft could not be saved.');}
 dirtyRef.current=false;setDirty(false);setStatus('Saved.');window.location.assign(`/clients/${client.id}/reports/${result.id}`);
 }catch(e){if(live.current&&g===saveGeneration.current){setError(e.message||'Save failed. Retry the same request.');setStatus('Save failed.');}}finally{if(live.current&&g===saveGeneration.current)setBusy(false);}}
 const locked=busy||!!pending.current||!editable||isConflict;
 if(denied)return <p role="alert">{error}</p>;
 return <div className="bo-report"><PageHeader title={initial?'Edit report draft':'New report draft'} subtitle={`Private manual reporting for ${client.name}`}/>
 <div className="bo-form-actions"><Button variant="ghost" href={`/clients/${client.id}/reports`}>All reports</Button>{initial&&<Button variant="ghost" href={`/clients/${client.id}/reports/${initial.id}/preview`}>Preview saved draft</Button>}</div>
 {!editable&&<p>Read-only access. A workspace Owner, Admin or Project Manager can edit.</p>}
 {error&&<div role="alert"><p>{error}</p>{isConflict&&<Button variant="ghost" href={`/clients/${client.id}/reports/${initial?.id||''}`}>Reopen saved draft</Button>}</div>}
 <p role="status">{status|| (dirty?'Unsaved changes.':'Private draft. Nothing is published.')}</p>
 {!initial&&<div className="bo-report-service"><label>Find a purchased service<input value={search} onChange={e=>setSearch(e.target.value)} disabled={locked}/></label><Button type="button" onClick={()=>loadServices()} disabled={locked||optionsBusy}>Find services</Button>{options?.page>1&&<Button type="button" onClick={()=>loadServices(options.page-1)} disabled={optionsBusy}>Previous services</Button>}{options?.more&&<Button type="button" onClick={()=>loadServices(options.page+1)} disabled={optionsBusy}>More services</Button>}{optionsBusy&&<p role="status">Loading services…</p>}</div>}
 {initial&&editable&&template&&<ClientReportCsv report={{...data,templateId,templateVersion:template.version}} disabled={locked} onApply={metrics=>change('metrics',metrics)}/>}
 <form onSubmit={save}><fieldset disabled={locked}><div className="bo-report-grid">
 <label>Purchased service{initial?<input value={`${initial.serviceName}${initial.packageName?' — '+initial.packageName:''}`} readOnly/>:<select required value={serviceId} onChange={e=>{setService(e.target.value);change('title',data.title);}}><option value="">Choose a service</option>{options?.items.map(s=><option key={s.id} value={s.id}>{s.name}{s.packageName?' — '+s.packageName:''} — {s.status}{s.startDate?` · ${s.startDate}`:''}</option>)}</select>}</label>
 <label>Report template<select required disabled={!!initial} value={templateId} onChange={e=>{setTemplate(e.target.value);change('metrics',{});setData(d=>({...d,channel:''}));}}><option value="">Choose a template</option>{REPORT_TEMPLATES.map(t=><option key={t.id} value={t.id}>{t.label}</option>)}</select></label>
 {template&&<><label>Report title<input required maxLength={180} value={data.title} onChange={e=>change('title',e.target.value)}/></label><label>Channel<select required value={data.channel} onChange={e=>change('channel',e.target.value)}><option value="">Choose a channel</option>{template.channels.map(c=><option key={c}>{c}</option>)}</select></label>
 <label>Period start<input required type="date" value={data.periodStart} onChange={e=>change('periodStart',e.target.value)}/></label><label>Period end<input required type="date" value={data.periodEnd} onChange={e=>change('periodEnd',e.target.value)}/></label>
 <label>Timezone<input required maxLength={80} value={data.timezone} onChange={e=>change('timezone',e.target.value)} aria-describedby="report-timezone-help"/><span id="report-timezone-help">IANA name, for example Australia/Sydney or UTC.</span></label><label>Account<input maxLength={180} value={data.accountLabel} onChange={e=>change('accountLabel',e.target.value)}/></label><label>Campaign or content scope<input maxLength={300} value={data.scopeLabel} onChange={e=>change('scopeLabel',e.target.value)}/></label></>}
 </div>{template&&<><h2>Manual metrics</h2><p>Leave unknown numbers missing. All entered values remain unverified; use source notes to explain their origin and definition.</p>
 {template.metrics.map(m=>{const v=data.metrics[m.key]||emptyMetric();return <fieldset className="bo-report-metric" key={m.key}><legend>{m.label}</legend><p>{m.definition}</p><div className="bo-report-grid"><label>{m.label} availability<select value={v.state} onChange={e=>metric(m.key,{state:e.target.value,value:null})}><option value="missing">Not supplied</option><option value="value">Enter value</option><option value="unavailable">Unavailable</option><option value="not_tracked">Not tracked</option></select></label>{v.state==='value'&&<label>{m.label} count<input type="number" min="0" max={m.max} step="1" required value={v.value??''} onChange={e=>metric(m.key,{value:e.target.value===''?null:Number(e.target.value)})}/></label>}<label>{m.label} source note<textarea maxLength={1000} value={v.sourceNote} onChange={e=>metric(m.key,{sourceNote:e.target.value})}/></label><label>{m.label} collection time (UTC)<input type="datetime-local" step="1" value={v.collectedAt?.slice(0,19)||''} onChange={e=>metric(m.key,{collectedAt:e.target.value?new Date(e.target.value+'Z').toISOString():null})}/></label></div></fieldset>;})}
 <label>Report commentary<textarea rows="7" maxLength={8000} value={data.commentary} onChange={e=>change('commentary',e.target.value)}/></label></>}
 </fieldset>{editable&&<Button variant="primary" type="submit" disabled={busy||isConflict||!template}>{busy?'Saving…':pending.current?'Retry save':'Save draft'}</Button>}</form></div>;
}
