'use client';
import {useState,useRef,useEffect} from 'react';
import {PageHeader,Button} from './Primitives';
import {FINANCE_FIELDS,FINANCE_CURRENCIES,FINANCE_STATUSES,financeLabel} from '@/lib/bloomops/finance-values.mjs';
export default function FinanceEditor({scope,initial=null,parents=null,canEdit=false}){
 const [data,setData]=useState(initial?Object.fromEntries(FINANCE_FIELDS.map(k=>[k,initial[k]??''])):{title:'',amount:'',currency:'USD',status:'draft',dueDate:'',paidDate:'',renewalDate:'',provider:'',reference:'',notes:'',archived:false});
 const [kind,setKind]=useState(initial?.kind||'invoice'),[parent,setParent]=useState(initial?{clientId:initial.clientId,serviceEngagementId:initial.serviceEngagementId}:null),[choices,setChoices]=useState(parents),[search,setSearch]=useState(''),[busy,setBusy]=useState(false),[choicesBusy,setChoicesBusy]=useState(false),[error,setError]=useState(''),[choiceError,setChoiceError]=useState(''),[denied,setDenied]=useState(false),[conflict,setConflict]=useState(false),[dirty,setDirty]=useState(false);
 const live=useRef(true),readGen=useRef(0),saveGen=useRef(0),choiceGen=useRef(0),pending=useRef(null),request=useRef(null),dirtyRef=useRef(false);
 useEffect(()=>{live.current=true;const leave=e=>{if(dirtyRef.current){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',leave);return()=>{live.current=false;readGen.current++;saveGen.current++;choiceGen.current++;window.removeEventListener('beforeunload',leave);};},[]);
 useEffect(()=>{const check=async()=>{const g=++readGen.current;try{const res=await fetch('/api/bloomops/finance'+(initial?'/'+initial.id:''),{cache:'no-store'}),body=await res.json();if(!live.current||g!==readGen.current)return;if(!res.ok||body.scope?.workspaceId!==scope.workspaceId||body.scope?.userId!==scope.userId){saveGen.current++;choiceGen.current++;dirtyRef.current=false;setDenied(true);}}catch{}};window.addEventListener('focus',check);window.addEventListener('pageshow',check);return()=>{readGen.current++;window.removeEventListener('focus',check);window.removeEventListener('pageshow',check);};},[scope.workspaceId,scope.userId,initial?.id]);
 const locked=!canEdit||busy||denied||!!pending.current||conflict;
 function change(k,v){dirtyRef.current=true;setDirty(true);setData(d=>({...d,[k]:v}));}
 async function loadChoices(page=1){const g=++choiceGen.current;setChoicesBusy(true);setChoiceError('');try{const res=await fetch('/api/bloomops/finance/parents?'+new URLSearchParams({search,page}),{cache:'no-store'}),body=await res.json();if(!live.current||g!==choiceGen.current)return;if(!res.ok||body.scope?.workspaceId!==scope.workspaceId||body.scope?.userId!==scope.userId)throw Error('Could not load authorized Client/Service choices. Retry search.');setChoices(body);}catch(e){if(live.current&&g===choiceGen.current)setChoiceError(e.message);}finally{if(live.current&&g===choiceGen.current)setChoicesBusy(false);}}
 async function save(e){e.preventDefault();if(busy||denied||!canEdit||conflict)return;const g=++saveGen.current;setBusy(true);setError('');request.current??=crypto.randomUUID();const body=pending.current||{...scope,requestId:request.current,expectedRevision:initial?.revision,...parent,kind,record:data};pending.current=body;try{const res=await fetch('/api/bloomops/finance'+(initial?'/'+initial.id:''),{method:initial?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),result=await res.json();if(!live.current||g!==saveGen.current)return;if(!res.ok){if(res.status<500){pending.current=null;if(res.status===409)setConflict(true);if([401,403,404].includes(res.status))setDenied(true);}throw Error(result.error||'Finance access changed or the save failed.');}dirtyRef.current=false;window.location.assign('/finance/'+result.id);}catch(e){if(live.current&&g===saveGen.current)setError(e.message+' Your input has not been discarded.');}finally{if(live.current&&g===saveGen.current)setBusy(false);}}
 if(denied)return <><PageHeader title="Finance access changed"/><p role="alert">Reopen Finance in the correct workspace. This record is no longer shown.</p><Button href="/finance">Return to Finance</Button></>;
 return <><PageHeader title={initial?initial.title:'New finance record'} subtitle="Manual tracking only. Saving does not send an invoice or process a payment." actions={<Button href="/finance">Finance records</Button>}/>
 {initial&&<section className="bo-finance-row" aria-label="Finance record context"><dl><div><dt>Client</dt><dd>{initial.clientName}</dd></div><div><dt>Service</dt><dd>{initial.serviceName||'Client-level'}</dd></div><div><dt>Package</dt><dd>{initial.packageName||'Not set'}</dd></div></dl></section>}
 {!canEdit&&<p>Read-only Finance access.</p>}
 <form onSubmit={save} className="bo-finance-editor">
 {!initial&&<section aria-label="Client and Service setup"><div className="bo-form-actions"><label>Find Client or Service<input value={search} maxLength={100} onChange={e=>setSearch(e.target.value)} disabled={locked}/></label><Button onClick={()=>loadChoices()} loading={choicesBusy} disabled={locked}>Search choices</Button></div>{choiceError&&<p role="alert">{choiceError}</p>}<label>Client and applicable Service<select aria-label="Client and applicable Service" required disabled={locked||choicesBusy} value={parent?JSON.stringify([parent.clientId,parent.serviceEngagementId]):''} onChange={e=>{const [clientId,serviceEngagementId]=JSON.parse(e.target.value);setParent({clientId,serviceEngagementId});dirtyRef.current=true;setDirty(true);}}><option value="">Choose an authorized Client / Service</option>{parent&&!choices?.items.some(p=>p.clientId===parent.clientId&&p.serviceEngagementId===parent.serviceEngagementId)&&<option value={JSON.stringify([parent.clientId,parent.serviceEngagementId])}>Previously selected Client / Service</option>}{choices?.items.map(p=><option key={JSON.stringify([p.clientId,p.serviceEngagementId])} value={JSON.stringify([p.clientId,p.serviceEngagementId])}>{p.clientName}: {p.serviceName||'Client-level'}{p.packageName?' — '+p.packageName:''}</option>)}</select></label>{choices?.page>1&&<Button disabled={locked||choicesBusy} onClick={()=>loadChoices(choices.page-1)}>Previous choices</Button>}{choices?.more&&<Button disabled={locked||choicesBusy} onClick={()=>loadChoices(choices.page+1)}>Next choices</Button>}{!choices?.items.length&&<p>No authorized Clients or Services match. Create or assign the Client/Service through Clients first.</p>}</section>}
 <fieldset disabled={locked}><div className="bo-finance-grid"><label>Record type<select aria-label="Record type" disabled={!!initial} value={kind} onChange={e=>{setKind(e.target.value);change('status',FINANCE_STATUSES[e.target.value][0]);}}><option value="invoice">Invoice</option><option value="payment">Payment</option></select></label><label>Title<input required maxLength={160} value={data.title} onChange={e=>change('title',e.target.value)}/></label><label>Amount<input required inputMode="decimal" value={data.amount} onChange={e=>change('amount',e.target.value)}/></label><label>Currency<select aria-label="Currency" value={data.currency} onChange={e=>change('currency',e.target.value)}>{FINANCE_CURRENCIES.map(c=><option key={c}>{c}</option>)}</select></label><label>Status<select aria-label="Status" value={data.status} onChange={e=>change('status',e.target.value)}>{FINANCE_STATUSES[kind].map(s=><option key={s} value={s}>{financeLabel(s)}</option>)}</select></label>{['dueDate','paidDate','renewalDate'].map(k=><label key={k}>{({dueDate:'Due date',paidDate:'Paid date',renewalDate:'Renewal date'})[k]}<input type="date" min="1900-01-01" max="9999-12-31" value={data[k]} onChange={e=>change(k,e.target.value)}/></label>)}<label>Provider (manual reference)<input maxLength={160} value={data.provider} onChange={e=>change('provider',e.target.value)}/></label><label>Reference<input maxLength={160} value={data.reference} onChange={e=>change('reference',e.target.value)}/></label></div><label>Private notes<textarea maxLength={8000} rows={5} value={data.notes} onChange={e=>change('notes',e.target.value)}/></label>{initial&&<label className="bo-finance-check"><input type="checkbox" checked={data.archived} onChange={e=>change('archived',e.target.checked)}/>Archived (retains this record and removes it from active views)</label>}</fieldset>
 {error&&<p role="alert">{error}</p>}{conflict&&<Button href={'/finance/'+initial.id} target="_blank" rel="noopener">Open saved record in a new tab</Button>}
 {canEdit&&<div className="bo-form-actions"><Button type="submit" variant="primary" loading={busy} disabled={busy||conflict||!parent}>{pending.current&&!busy?'Retry identical save':initial?'Save finance record':'Create finance record'}</Button><span role="status">{busy?'Saving…':dirty?'Unsaved changes':initial?'Saved record':''}</span></div>}
 </form></>;
}
