'use client';
import {useEffect,useRef,useState} from 'react';
import {Button} from './Primitives';
import OnboardingTemplateReview from './OnboardingTemplateReview';
import {DRAFT_CONTEXT_KEY} from '@/lib/bloomops/draft-context.mjs';
export default function OnboardingSetup({initial}){
 const [data,setData]=useState(initial),[selected,setSelected]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');const readGeneration=useRef(0),writeGeneration=useRef(0),inFlight=useRef(false),live=useRef(true);
 const scope=initial.scope;
 useEffect(()=>{live.current=true;async function refresh(){const g=++readGeneration.current;try{const r=await fetch('/api/bloomops/onboarding/setup',{cache:'no-store'}),b=await r.json();if(!live.current||g!==readGeneration.current)return;if(!r.ok||b.scope?.userId!==scope.userId||b.scope?.workspaceId!==scope.workspaceId){writeGeneration.current++;inFlight.current=false;setBusy(false);setData(null);setError('Setup access changed. Reopen Settings.');}else if(!inFlight.current){setData(b);setSelected([]);}}catch{if(live.current&&g===readGeneration.current&&!inFlight.current)setError('Could not refresh setup. Reopen Settings to retry.');}}
 const lost=()=>{live.current=false;readGeneration.current++;writeGeneration.current++;setData(null);setError('Setup access changed. Reopen Settings.');};const storage=e=>{if(e.key===DRAFT_CONTEXT_KEY||e.key===null)lost();};let channel;try{channel=new BroadcastChannel(DRAFT_CONTEXT_KEY);channel.onmessage=lost;}catch{}addEventListener(DRAFT_CONTEXT_KEY,lost);addEventListener('storage',storage);window.addEventListener('focus',refresh);return()=>{channel?.close();removeEventListener(DRAFT_CONTEXT_KEY,lost);removeEventListener('storage',storage);live.current=false;readGeneration.current++;writeGeneration.current++;window.removeEventListener('focus',refresh);};},[scope.userId,scope.workspaceId]);
 async function install(){if(inFlight.current)return;inFlight.current=true;const g=++writeGeneration.current;setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/bloomops/onboarding/setup',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...scope,categories:selected})}),b=await r.json();if(!live.current||g!==writeGeneration.current)return;if(!r.ok||b.scope?.userId!==scope.userId||b.scope?.workspaceId!==scope.workspaceId){if([401,403,404].includes(r.status))setData(null);throw Error('Setup could not be completed. Refresh and check your access.');}setData(b);setSelected([]);setMessage(b.complete?'Selected onboarding categories are ready. No client was activated or contacted.':'Existing versions were preserved. Some selected categories still require review.');}catch(e){if(live.current&&g===writeGeneration.current)setError(e.message);}finally{if(live.current&&g===writeGeneration.current){inFlight.current=false;setBusy(false);}}}
 async function manage(item,command){
  if(inFlight.current||!live.current)return false;inFlight.current=true;const g=++writeGeneration.current;setBusy(true);setError('');setMessage('');
  try{const r=await fetch('/api/bloomops/onboarding/setup',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({...scope,slug:item.slug,reviewToken:item.reviewToken,...command})}),b=await r.json();
   if(!live.current||g!==writeGeneration.current)return false;
   if(!r.ok){if([401,403,404].includes(r.status))setData(null);throw Error(r.status===409?'The template changed. Refresh setup and review the current version before trying again.':'The template could not be changed. Your draft remains here; check the instructions and retry.');}
   if(b.scope?.userId!==scope.userId||b.scope?.workspaceId!==scope.workspaceId){setData(null);throw Error('Setup scope changed. Reopen Settings.');}
   readGeneration.current++;setData(b);setMessage(command.action==='publish'?'Version published. Existing onboarding and invitations are unchanged.':command.action==='enable'?'Template enabled. Review its publication before activating a client.':'New draft saved. Review it before publishing.');return true;
  }catch(e){if(live.current&&g===writeGeneration.current)setError(e.message);return false;}
  finally{if(live.current&&g===writeGeneration.current){inFlight.current=false;setBusy(false);}}
 }
 if(!data)return <p role="alert">{error}</p>;
 return <div className="bo-page-narrow bo-setup-categories"><p>Review the built-in instructions before installing missing onboarding categories for this workspace. Existing versions and client progress are never replaced. Activation and portal invitations remain separate actions.</p>
 {error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
 {data.items.map(item=><section key={item.slug} className="bo-report-metric"><h2>{item.name}</h2><p>{item.state==='published'?`Published version ${item.publishedVersion}`:item.state==='existing_draft'?'Existing draft (not automatically published)':item.state==='inactive'?'Inactive template (unchanged)':'No configured version'}</p>
 <label className="bo-check"><input type="checkbox" disabled={busy||item.state!=='missing'} checked={selected.includes(item.slug)} onChange={e=>setSelected(s=>e.target.checked?[...s,item.slug]:s.filter(k=>k!==item.slug))}/>Install missing {item.name} defaults</label>
 <details><summary>Review {item.name} default instructions</summary><ol>{item.definition.items.map(i=><li key={i.logicalKey}><strong>{i.title}</strong><p>{i.instructions}</p><p>{i.required?'Required':'Optional'}; {i.verificationRequired?'team verification required':'no additional verification'}. Visible to the client.</p></li>)}</ol></details><OnboardingTemplateReview key={item.slug} item={item} busy={busy} onAction={manage}/></section>)}
 <Button type="button" disabled={busy||!selected.length} onClick={install}>{busy?'Installing…':'Install selected defaults'}</Button></div>;
}
