'use client';
import {useEffect,useRef,useState} from 'react';
import {Button} from './Primitives';
import {Icon} from './Icons';
import PageGlyph from './PageGlyph';
import {PAGE_ICONS} from '@/lib/bloomops/page-icons.mjs';
import {usePages} from './PagesWorkspace';
const labels={file:'Document',flower:'Flower',sprout:'Sprout','book-open':'Book',lightbulb:'Idea',target:'Goal',star:'Star',heart:'Heart',table:'Table','calendar-check':'Calendar'};
export function PageIconPicker({id,initialIcon,workspaceId,canManage}){
 const pages=usePages(),[open,setOpen]=useState(false),[chosen,setChosen]=useState(initialIcon||'file');
 const icon=pages?.tree.rows.find(p=>p.id===id)?.icon||chosen;
 return <><button type="button" className="bo-page-mark bo-page-icon-picker" aria-label="Change page icon" disabled={!canManage} onClick={()=>setOpen(true)}><PageGlyph name={icon} size={22}/></button>{open&&<PageControls id={id} workspaceId={workspaceId} mode="icon" onClose={()=>setOpen(false)} onIcon={setChosen}/>}</>;
}
export function PageShareButton({id,workspaceId}){const [open,setOpen]=useState(false);return <><Button variant="ghost" icon="team" onClick={()=>setOpen(true)}>Share</Button>{open&&<PageControls id={id} workspaceId={workspaceId} onClose={()=>setOpen(false)}/>}</>;}
function PageControls({id,workspaceId,mode='sharing',onClose,onIcon}){
 const pages=usePages(),ref=useRef(null),pending=useRef(false),[data,setData]=useState(null),[query,setQuery]=useState(''),[member,setMember]=useState(''),[permission,setPermission]=useState('view'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const api='/api/bloomops/pages/'+id+'/sharing';
 async function load(){const response=await fetch(api,{cache:'no-store'});if(!response.ok)throw Error('Page access could not load.');const next=await response.json();setData(next);return next;}
 useEffect(()=>{const previous=document.activeElement,dialog=ref.current;dialog.showModal();let alive=true;fetch(api,{cache:'no-store'}).then(async r=>{if(!r.ok)throw Error();const result=await r.json();if(alive)setData(result);}).catch(()=>{if(alive)setError('Page access could not load.');});return()=>{alive=false;dialog.close();previous?.focus();};},[api]);
 async function update(change){if(pending.current||!data)return;pending.current=true;setBusy(true);setError('');setMessage('');try{const response=await fetch(api,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({workspaceId,expectedTreeRevision:data.revision,...change})});const result=await response.json();if(!response.ok){if(response.status===409)await load();throw Error(result.error||'This change could not save.');}await load();await pages?.refresh();if(change.kind==='icon'){onIcon?.(change.icon);onClose();}else{setMember('');setMessage('Access updated.');}}catch(e){setError(e.message);}finally{pending.current=false;setBusy(false);}}
 async function copyLink(){try{await navigator.clipboard.writeText(location.origin+'/shared-pages/'+id+'?workspace='+encodeURIComponent(workspaceId));setMessage('Link copied. Only people with access can open it.');}catch{setError('The link could not copy. Select it below.');}}
 const shared=data?.people.filter(person=>person.source)||[],matches=data?.people.filter(person=>(person.name+' '+person.email).toLowerCase().includes(query.toLowerCase())).slice(0,50)||[];
 return <dialog ref={ref} className="bo-page-move-dialog bo-page-share-dialog" aria-labelledby="bo-page-share-title" onCancel={e=>{e.preventDefault();if(!busy)onClose();}}><div className="bo-page-move-heading"><h2 id="bo-page-share-title">{mode==='icon'?'Page icon':'Share page'}</h2><button type="button" className="bo-page-icon-button" aria-label="Close page controls" disabled={busy} onClick={onClose}><Icon name="x" size={18}/></button></div>
 {!data&&!error&&<p role="status">Loading…</p>}{error&&<p role="alert">{error} {!data&&<Button onClick={()=>load().catch(e=>setError(e.message))}>Try again</Button>}</p>}
 {data&&mode==='icon'&&<div className="bo-page-icon-grid">{PAGE_ICONS.map(icon=><button key={icon} type="button" disabled={busy} aria-label={labels[icon]} aria-pressed={data.icon===icon} onClick={()=>update({kind:'icon',icon})}><PageGlyph name={icon} size={24}/><span>{labels[icon]}</span></button>)}</div>}
 {data&&mode==='sharing'&&<><p className="bo-page-sharing-description"><Icon name="lock" size={16}/>Only people with access</p><label className="bo-page-access-confirm"><input type="checkbox" checked={Boolean(data.inheritAccess)} disabled={busy} onChange={e=>update({kind:'inheritance',inheritAccess:e.target.checked})}/>Inherit access from the parent page</label><p className="bo-hint">Subpages inherit access unless you restrict them.</p>
 <form onSubmit={e=>{e.preventDefault();update({kind:'grant',membershipId:member,permission});}}><label className="bo-page-search"><span>Find a person</span><input type="search" value={query} onChange={e=>setQuery(e.target.value)} maxLength={200} placeholder="Name or email"/></label><label className="bo-page-order">Person<select required value={member} disabled={busy} onChange={e=>setMember(e.target.value)}><option value="">Choose a workspace user or client</option>{matches.map(person=><option key={person.id} value={person.id}>{person.name} ({person.email})</option>)}</select></label><div className="bo-page-add-access"><label className="bo-page-order">Access<select value={permission} onChange={e=>setPermission(e.target.value)} disabled={busy}><option value="view">Can view</option><option value="comment">Can comment</option><option value="edit">Can edit</option></select></label><Button type="submit" variant="primary" disabled={busy||!member}>Give access</Button></div></form>
 <h3 className="bo-page-access-heading">People with access</h3><p className="bo-hint">Workspace owners and admins can always manage pages.</p><ul className="bo-page-access-list">{shared.map(person=><li key={person.id}><Icon name={person.role==='client'?'clients':'user'} size={18}/><div><strong>{person.name}</strong><span>{person.role==='client'?'Client':'Workspace user'}</span>{person.source.id!==id&&<a href={'/pages/'+person.source.id}>Inherited from {person.source.title}</a>}</div><label><span className="sr-only">Access for {person.name}</span><select aria-label={'Access for '+person.name} value={person.permission} disabled={busy} onChange={e=>update({kind:'grant',membershipId:person.id,permission:e.target.value})}><option value="view">Can view</option><option value="comment">Can comment</option><option value="edit">Can edit</option><option value="none">No access</option></select></label></li>)}</ul>{!shared.length&&<p className="bo-hint">No additional people have access.</p>}
 <div className="bo-page-share-link"><Button icon="copy" onClick={copyLink}>Copy link</Button><input aria-label="Page share link" readOnly value={typeof location==='undefined'?'':location.origin+'/shared-pages/'+id+'?workspace='+encodeURIComponent(workspaceId)} onFocus={e=>e.target.select()}/></div></>}{message&&<p role="status">{message}</p>}
 </dialog>;
}
