'use client';
import {useEffect,useRef,useState} from 'react';
import {Button} from './Primitives';
import {Icon} from './Icons';
import ThreadMute from './ThreadMute';
import UserAvatar from './UserAvatar';
export default function PageComments({id,workspaceId}){
 const [open,setOpen]=useState(false),[initialThread,setInitialThread]=useState(null);
 useEffect(()=>{const thread=new URLSearchParams(location.search).get('discussion');if(thread&&/^[0-9a-f-]{36}$/i.test(thread)){setInitialThread(thread);setOpen(true);}},[id]);
 return <><Button variant="ghost" icon="message" onClick={()=>setOpen(true)}>Comments</Button>{open&&<Discussions initialThread={initialThread} id={id} workspaceId={workspaceId} onClose={()=>setOpen(false)}/>}</>;
}
function Discussions({id,workspaceId,onClose,initialThread=null}){
 const dialog=useRef(null),pending=useRef(false),version=useRef(0),drafts=useRef({});
 const [data,setData]=useState(null),[selected,setSelected]=useState(initialThread),[resolved,setResolved]=useState(false),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[body,setBody]=useState('');
 const api='/api/bloomops/pages/'+id+'/comments',key=selected||'new';
 function close(){if(!busy&&(!Object.values(drafts.current).some(d=>d.body.trim())||confirm('Close with an unsent comment? Copy your writing first to keep it.')))onClose();}
 async function load(threadId=selected,filter=resolved,page=1,append=false){const run=++version.current;setLoading(true);try{const q=new URLSearchParams({page:String(page),resolved:String(filter)});if(threadId)q.set('threadId',threadId);const response=await fetch(api+'?'+q,{cache:'no-store'});if(!response.ok)throw Error('Comments could not load. Your unsent writing is still here.');const next=await response.json();if(run===version.current){setData(old=>append?{...next,[threadId?'messages':'threads']:[...(old?.[threadId?'messages':'threads']||[]),...next[threadId?'messages':'threads']]}:next);setError('');}}catch(e){if(run===version.current)setError(e.message);}finally{if(run===version.current)setLoading(false);}}
 useEffect(()=>{const previous=document.activeElement,node=dialog.current;node.showModal();load();return()=>{version.current++;node.close();previous?.focus();};},[]);
 function navigate(threadId,filter=resolved){if(busy)return;setSelected(threadId);setResolved(filter);setBody(drafts.current[threadId||'new']?.body||'');setData(null);setNotice('');load(threadId,filter);}
 async function submit(e){e.preventDefault();if(pending.current||!body.trim())return;pending.current=true;setBusy(true);setError('');setNotice('');const draft=drafts.current[key]||{body,requestId:crypto.randomUUID()};drafts.current[key]=draft;
 try{const response=await fetch(api,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({workspaceId,requestId:draft.requestId,threadId:selected,expectedRevision:selected?data.thread.revision:null,body:draft.body})});const result=await response.json();if(!response.ok)throw Error(result.error||'Comment was not saved. Your writing is still here.');delete drafts.current[key];setBody('');setData(null);setSelected(result.threadId);setNotice('Comment posted.');await load(result.threadId);}catch(e){setError(e.message);}finally{pending.current=false;setBusy(false);}}
 async function toggle(){if(pending.current)return;pending.current=true;setBusy(true);setError('');try{const response=await fetch(api,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({workspaceId,threadId:selected,expectedRevision:data.thread.revision,resolved:!data.thread.resolved})});const result=await response.json();if(!response.ok)throw Error(result.error||'Discussion could not update.');setNotice(data.thread.resolved?'Discussion reopened.':'Discussion resolved.');await load(selected);}catch(e){setError(e.message);}finally{pending.current=false;setBusy(false);}}
 return <dialog ref={dialog} className="bo-page-comments-dialog" aria-labelledby="bo-comments-heading" onCancel={e=>{e.preventDefault();close();}}><header><div><Icon name="message" size={20}/><h2 id="bo-comments-heading">Comments</h2></div><button type="button" className="bo-page-icon-button" aria-label="Close comments" disabled={busy} onClick={close}><Icon name="x" size={18}/></button></header>
 <div className="bo-comments-controls">{selected?<Button variant="ghost" icon="chevron-left" disabled={busy} onClick={()=>navigate(null)}>All discussions</Button>:<label>Show<select aria-label="Discussion status" value={resolved?'resolved':'open'} disabled={busy} onChange={e=>navigate(null,e.target.value==='resolved')}><option value="open">Open</option><option value="resolved">Resolved</option></select></label>}<Button variant="ghost" icon="refresh" disabled={busy||loading} onClick={()=>load()}>Refresh</Button></div>
 {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{loading&&<p role="status">Loading comments…</p>}
 {data&&!selected&&<><ul className="bo-comment-threads">{data.threads.map(thread=><li key={thread.id}><button type="button" disabled={busy} onClick={()=>navigate(thread.id)}><span className="bo-comment-author"><UserAvatar seed={thread.author} src={`${api}/${thread.id}/photo`} size={28}/><strong>{thread.author}</strong></span><span className="bo-comment-preview">{thread.preview}</span><span className="bo-comment-meta"><span>{thread.count===1?'1 comment':thread.count+' comments'}</span><time dateTime={thread.createdAt}>{new Date(thread.createdAt).toLocaleDateString()}</time></span></button></li>)}</ul>{!data.threads.length&&<div className="bo-comments-empty"><Icon name="message" size={24}/><p>{resolved?'No resolved discussions.':'Start the conversation.'}</p></div>}</>}
 {data&&selected&&<><div className="bo-comment-thread-state"><ThreadMute key={selected} threadId={selected} kind="page" workspaceId={workspaceId}/><span className={'bo-comment-state'+(data.thread.resolved?' is-resolved':'')}>{data.thread.resolved?'Resolved':'Open discussion'}</span>{Boolean(data.thread.canResolve)&&<Button variant="ghost" icon={data.thread.resolved?'refresh':'check'} disabled={busy||loading} onClick={toggle}>{data.thread.resolved?'Reopen':'Resolve'}</Button>}</div><ol className="bo-comment-messages">{data.messages.map(message=><li key={message.id}><div className="bo-comment-author"><UserAvatar seed={message.author} src={`${api}/${message.id}/photo`} size={28}/><strong>{message.author}</strong></div><time dateTime={message.createdAt}>{new Date(message.createdAt).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'})}</time><p>{message.body}</p></li>)}</ol></>}
 {data?.more&&<Button disabled={busy||loading} onClick={()=>load(selected,resolved,data.page+1,true)}>Load more {selected?'comments':'discussions'}</Button>}
 {data&&(Boolean(body.trim())||Boolean(data.canComment)&&(!selected?!resolved:!data.thread.resolved))&&<form onSubmit={submit}><label htmlFor="bo-comment-writing">{selected?'Reply':'New discussion'}</label><textarea id="bo-comment-writing" value={body} maxLength={8000} rows={4} disabled={busy} placeholder={selected?'Write a reply…':'Share feedback or ask a question…'} onChange={e=>{setBody(e.target.value);drafts.current[key]={body:e.target.value,requestId:crypto.randomUUID()};}}/><Button type="submit" variant="primary" icon="message" disabled={busy||loading||!body.trim()||!data.canComment||Boolean(selected&&data.thread.resolved)}>{busy?'Posting…':selected?'Post reply':'Post comment'}</Button></form>}
 {data&&!data.canComment&&<p className="bo-hint">You can read these discussions. Ask the page owner for comment access to join in.</p>}
 </dialog>;
}
