'use client';
import {useEffect,useRef,useState} from 'react';
import {Button,PageHeader,Field} from './Primitives';
import {Icon} from './Icons';
import {plural} from '@/lib/bloomops/format.mjs';
import {CSV_LIMIT} from '@/lib/bloomops/prospect-csv-values.mjs';
export default function ProspectCsvImport({workspaceId}){
 const [ready,setReady]=useState(false),fileControl=useRef(null);useEffect(()=>{setReady(true);setFile(fileControl.current?.files?.[0]||null);},[]);
 const [file,setFile]=useState(null),[preview,setPreview]=useState(null),[selected,setSelected]=useState([]),[separate,setSeparate]=useState([]),[busy,setBusy]=useState(''),[error,setError]=useState(''),[receipt,setReceipt]=useState(null),doc=useRef(null),pending=useRef(null),lock=useRef(false);
 async function request(action,input){const res=await fetch('/api/bloomops/prospecting/csv',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,input})});const data=await res.json();if(!res.ok)throw Error(data.error||'The request could not be confirmed. Retry.');return data;}
 async function openReceipt(id){const res=await fetch('/api/bloomops/prospecting/csv?id='+encodeURIComponent(id));if(!res.ok)throw Error('Could not load the receipt. Retry the import to reopen it.');setReceipt(await res.json());setPreview(null);}
 async function check(e){e.preventDefault();if(lock.current||!file)return;lock.current=true;setBusy('Reading file');setError('');setPreview(null);setReceipt(null);try{if(file.size>CSV_LIMIT)throw Error('Choose a file of 256 KiB or less.');doc.current={workspaceId,text:await file.text(),fileName:file.name};setBusy('Checking rows and duplicates');const data=await request('preview',doc.current);if(data.receiptId){await openReceipt(data.receiptId);return;}setPreview(data);setSelected(data.rows.filter(r=>r.status==='ready').map(r=>r.index));setSeparate([]);pending.current=null;}catch(e){setError(e.message);}finally{lock.current=false;setBusy('');}}
 async function commit(){if(lock.current)return;lock.current=true;setBusy('Saving selected rows');setError('');try{pending.current??={workspaceId,requestId:crypto.randomUUID(),document:doc.current,previewHash:preview.previewHash,selected,separate};const data=await request('commit',pending.current);await openReceipt(data.receiptId);}catch(e){setError(e.message);}finally{lock.current=false;setBusy('');}}
 function choose(i,checked,duplicate){pending.current=null;setSelected(s=>checked?[...s,i]:s.filter(v=>v!==i));if(duplicate)setSeparate(s=>checked?[...s,i]:s.filter(v=>v!==i));}
 return <div className="bo-prospect-page"><Button href="/prospecting" icon="chevron-left">Back to prospects</Button><PageHeader title="Import prospects" subtitle="Preview raw contact details before adding records." actions={<a className="bo-sheet-download" href="/api/bloomops/prospecting/sample-csv" download><Icon name="download"/>Sample CSV</a>}/><p>Replace both fictional example rows with your own records. Blank website and email are allowed.</p><form onSubmit={check} className="bo-import-file"><Field id="csv-file" label="CSV file" hint="Up to 50 records and 256 KiB per batch."><input className="bo-control" id="csv-file" ref={fileControl} type="file" accept=".csv,text/csv" disabled={!ready||!!busy} onChange={e=>{setFile(e.target.files?.[0]||null);setPreview(null);setReceipt(null);setError('');pending.current=null;}}/></Field><Button type="submit" variant="primary" disabled={!file||!!busy}>Preview import</Button></form><p><a href="/prospecting/import">Review an existing workspace export</a></p>
 {busy&&<p role="status" className="bo-sheet-progress"><Icon name="prospecting"/>{busy}…</p>}{error&&<p role="alert" className="bo-prospect-notice">{error}</p>}
 {preview&&<section aria-label="Import preview"><h2>Review {plural(preview.rows.length, 'row')}</h2><details><summary>Column mapping</summary><dl className="bo-prospect-facts">{preview.mapping.map(m=><div key={m.field}><dt>{m.label}</dt><dd>{m.target}</dd></div>)}</dl></details><p>Possible duplicates start unselected. A shared website can belong to different contacts; select one only after confirming it is a separate record.</p><div className="bo-sheet-scroll"><table className="bo-sheet-table"><thead><tr><th>Select</th><th>Business</th><th>Contact</th><th>Website</th><th>Check</th></tr></thead><tbody>{preview.rows.map(r=><tr key={r.index}><td><input type="checkbox" aria-label={(r.status==='duplicate'?'Confirm separate record: ':'Import ')+(r.raw.businessName||'row '+r.index)} disabled={r.status==='invalid'||!!busy} checked={selected.includes(r.index)} onChange={e=>choose(r.index,e.target.checked,r.status==='duplicate')}/></td><td>{r.raw.businessName||'Missing business name'}</td><td>{r.raw.personName||'Unknown'}</td><td>{r.raw.website||'Unknown'}</td><td>{r.status==='ready'?'Ready':r.status==='invalid'?r.errors.join(' '):<><strong>Possible duplicate</strong>{r.fileDuplicate&&<p>Similar row in this file</p>}{r.matches.map(m=><p key={m.id}><a href={'/prospecting/'+m.id} target="_blank" rel="noreferrer">{m.businessName}{m.personName?': '+m.personName:''}</a></p>)}</>}</td></tr>)}</tbody></table></div><Button variant="primary" disabled={!selected.length||!!busy} onClick={commit}>Import {selected.length} selected</Button></section>}
 {receipt&&<section aria-label="Import receipt"><h2>Import recorded</h2><p>{receipt.rows.filter(r=>r.status==='added').length} added, {receipt.rows.filter(r=>r.status==='skipped').length} skipped, {receipt.rows.filter(r=>r.status==='invalid').length} invalid.</p><Button href={'/prospecting?batch='+receipt.id}>View this import batch</Button><ul>{receipt.rows.map(r=><li key={r.ordinal}>{r.prospectId?<a href={'/prospecting/'+r.prospectId}>{r.fields.businessName}</a>:r.fields.businessName||'Row '+r.ordinal}<p>{r.status}{r.reason?': '+r.reason:''}</p></li>)}</ul></section>}
 </div>;
}
