'use client';
import {useEffect,useRef,useState} from 'react';
import {Button,PageHeader,Field} from './Primitives';
export default function ProspectAuditBatch({workspaceId}){
 const [ready,setReady]=useState(false),fileControl=useRef(null);useEffect(()=>{setReady(true);setFiles([...(fileControl.current?.files||[])]);},[]);
 const [files,setFiles]=useState([]),[rows,setRows]=useState([]),[busy,setBusy]=useState(''),[error,setError]=useState(''),lock=useRef(false);
 async function preview(e){e.preventDefault();if(lock.current)return;lock.current=true;setError('');setRows([]);const next=[];try{if(files.length>50)throw Error('Review up to 50 result files at a time.');for(let i=0;i<files.length;i++){setBusy('Checking '+(i+1)+' of '+files.length);const file=files[i];try{if(file.size>524288)throw Error('Use a result file of 512 KiB or less.');const document=JSON.parse(await file.text()),prospectId=document.sourceContext?.prospectId;if(document.sourceContext?.workspaceId!==workspaceId)throw Error('This result belongs to another workspace.');const response=await fetch('/api/bloomops/prospecting/result-preview',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({workspaceId,prospectId,document})});const data=await response.json();if(!response.ok)throw Error(data.error||'Result unavailable.');next.push({name:file.name,prospectId,document,preview:data,choices:Object.fromEntries(data.changes.map(c=>[c.key,'keep'])),requestId:crypto.randomUUID()});}catch(e){next.push({name:file.name,error:e.message});}}setRows(next);}catch(e){setError(e.message);}finally{lock.current=false;setBusy('');}}
 async function save(index){if(lock.current)return;lock.current=true;setBusy('Saving reviewed audit');setError('');const row=rows[index];try{const response=await fetch('/api/bloomops/prospecting/result-apply',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({workspaceId,prospectId:row.prospectId,document:row.document,requestId:row.requestId,previewHash:row.preview.previewHash,expectedRevision:row.preview.revision,choices:row.choices})});const result=await response.json();if(!response.ok)throw Error(result.error||'This review changed. Preview the files again.');setRows(v=>v.map((r,i)=>i===index?{...r,saved:true,resultId:result.resultId}:r));}catch(e){setError(e.message);}finally{lock.current=false;setBusy('');}}
 return <div className="bo-prospect-page"><Button href="/prospecting">Back to prospects</Button><PageHeader title="Review returned audits" subtitle="Map each manual result by its saved prospect and workspace IDs."/><form className="bo-import-file" onSubmit={preview}><Field id="audit-results" label="Returned JSON result files"><input id="audit-results" ref={fileControl} className="bo-control" type="file" accept=".json,application/json" multiple disabled={!ready||!!busy} onChange={e=>{setFiles([...e.target.files]);setRows([]);}}/></Field><Button type="submit" disabled={!files.length||!!busy}>Preview results</Button></form>{busy&&<p role="status">{busy}…</p>}{error&&<p role="alert" className="bo-prospect-notice">{error}</p>}{rows.map((r,i)=><section className="bo-sheet-bulk" key={i}><h2>{r.name}</h2>{r.error?<p role="alert">{r.error}</p>:r.saved?<p role="status">Review saved. <a href={'/prospecting/'+r.prospectId+'/results/'+r.resultId}>Open retained source</a></p>:<><a href={'/prospecting/'+r.prospectId}>Open prospect profile</a>{r.preview.stale&&<p className="bo-prospect-notice">The profile changed after export. Current values are shown; keep newer edits unless you explicitly choose the result.</p>}<details className="bo-sheet-change-list"><summary>Audit evidence and limitations</summary><p>{r.document.fullReport}</p><p>{r.document.unknowns?.join('\n')}</p></details><p>Keep current dismisses a proposed field. Use result accepts it as unverified. Edit accepted fields and verify sources in the profile; source history is retained.</p>{r.preview.changes.map(c=><div className="bo-sheet-change-list" key={c.key}><h3>{c.label}</h3><p>Current: {c.current||'Unknown'}</p><p>Proposed: {c.proposed||'Unknown'}</p><label><select className="bo-control" aria-label={c.label+' decision for '+r.name} value={r.choices[c.key]} disabled={!!busy} onChange={e=>setRows(v=>v.map((row,j)=>j===i?{...row,requestId:crypto.randomUUID(),choices:{...row.choices,[c.key]:e.target.value}}:row))}><option value="keep">Keep current</option><option value="apply">Use result</option></select></label></div>)}<Button variant="primary" disabled={!!busy} onClick={()=>save(i)}>Save reviewed audit</Button></>}</section>)}</div>;
}
