'use client';
import {useEffect,useRef,useState} from 'react';
import {Button,Status} from './Primitives';
import {Icon} from './Icons';
const states={prepared:['Prepared','neutral'],submitting:['Awaiting confirmation','warning'],uncertain:['Unresolved','warning'],accepted:['Accepted by Google','success'],cancelled:['Cancelled','neutral']};
export default function ProspectDeliveryReview({initial}){
 const [data,setData]=useState(initial),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[reviewed,setReviewed]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(false);
 const pending=useRef(false),focus=useRef(null);
 useEffect(()=>setReady(true),[]);useEffect(()=>{if(notice)focus.current?.focus();},[notice]);
 async function act(action){
  if(pending.current||!ready)return;pending.current=true;setBusy(true);setNotice('');setError(false);
  try{
   const followup=action.includes('followup'),body={action,workspaceId:data.workspaceId,prospectId:data.prospectId,...(action==='prepare'?{approvalId:data.approvalId}:followup&&action!=='activate-followups'?{sequenceId:data.followups.sequence.id}:{deliveryId:data.receipt.id}),...(['send','activate-followups'].includes(action)?{reviewed}:{} )};
   const response=await fetch('/api/bloomops/prospecting/delivery',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),result=await response.json();
   if(!response.ok)throw new Error(result.error||'Delivery status could not be confirmed. Reload the receipt.');
   const refreshed=await fetch('/api/bloomops/prospecting/delivery?prospectId='+encodeURIComponent(data.prospectId),{cache:'no-store'}),next=await refreshed.json();
   if(!refreshed.ok)throw new Error('Reload this receipt to check its current status.');
   setData(next);setReviewed(false);
   setNotice(action==='prepare'?'Receipt prepared. Nothing was sent.':action==='cancel'?'Test cancelled. Nothing will be sent from this receipt.':action==='activate-followups'?'Sequence saved. Live execution remains disabled unless the server is explicitly configured.':action==='run-followup'?'The due check finished. Reloaded status reflects only recorded provider evidence.':action==='reconcile-followup'?'The ambiguous follow-up receipt was checked without resending.':next.receipt.state==='accepted'?'Google accepted the introduction. Inbox delivery is not yet confirmed.':'No confirmed result yet. This receipt cannot send again.');
  }catch(e){setError(true);setReviewed(false);setNotice(e instanceof TypeError?'The response was interrupted. Reload this receipt before taking another action.':e.message);}finally{pending.current=false;setBusy(false);}
 }
 const state=data.receipt?.state,status=states[state]||['Not prepared','neutral'],message=data.message;
 return <div className="bo-delivery-review">
 <div className="bo-outreach-review-status"><Status label={status[0]} tone={status[1]}/>{!data.enabled&&<Status label="Test sending disabled" tone="warning"/>}</div>
 {notice&&<p ref={focus} tabIndex={-1} role={error?'alert':'status'} className="bo-skill-notice">{notice}</p>}
 {message?<section className="bo-delivery-message" aria-label="Exact introduction"><dl className="bo-delivery-addresses"><div><dt><Icon name="mail"/>From</dt><dd>{message.displayName&&<strong>{message.displayName}</strong>}{message.sender||'Sender not configured'}</dd></div><div><dt><Icon name="mail"/>To</dt><dd>{message.recipient||'Recipient not recorded'}</dd></div></dl><h2>{message.subject||'Subject not recorded'}</h2><div className="bo-delivery-body">{message.body||'Introduction not recorded'}</div></section>:<p>Save and approve an outreach draft before preparing a test.</p>}
 {data.recipientProtection&&<section className="bo-delivery-protection" aria-label="Recipient protection"><h2><Icon name="shield-check"/>{data.recipientProtection.kind==='stopped'?'Outreach stopped for this email':data.recipientProtection.kind==='held'?'Outreach held for this email':'Conversation check pending'}</h2><p>{data.recipientProtection.recipient}</p><p>{data.recipientProtection.kind==='stopped'?'A saved stop decision blocks further introductions to this address.':data.recipientProtection.kind==='held'?'A reply or unresolved check needs review before further outreach.':'An unfinished conversation check blocks further outreach to this address.'}</p><Button href={'/prospecting/'+data.recipientProtection.prospectId+'/replies'} icon="history" variant="ghost">Review protected conversation</Button></section>}
 <section className="bo-delivery-actions" aria-label="Delivery controls">
 {!state&&<><p>Preparation saves a permanent receipt for this introduction. It does not send email.</p><Button variant="primary" icon="check" disabled={!ready||busy||!data.approvalId||Boolean(data.recipientProtection)} loading={busy} onClick={()=>act('prepare')}>Prepare test receipt</Button>{!data.approvalId&&<p className="bo-hint">Review and approve the current content in the draft first.</p>}</>}
 {state==='prepared'&&<>
 {!data.enabled&&<p>This test needs an explicitly enabled receipt and owner-controlled recipient before sending.</p>}
 {!data.approvalCurrent&&<p role="status">The approval changed. This saved message is held.</p>}
 {!data.googleConnected&&<Button href="/prospecting/sender" icon="refresh" variant="ghost">Check Google connection</Button>}
 <label className="bo-prospect-check"><input type="checkbox" checked={reviewed} disabled={!ready||busy||!data.canSend} onChange={e=>setReviewed(e.target.checked)}/><span>I control {message.recipient} and approve sending this introduction now.</span></label>
 <div className="bo-delivery-buttons"><Button variant="primary" icon="mail" disabled={!ready||busy||!reviewed||!data.canSend} loading={busy} onClick={()=>act('send')}>Send this test email</Button><Button icon="x" disabled={!ready||busy} onClick={()=>act('cancel')}>Cancel test</Button></div><p className="bo-hint">Sends immediately. No follow-up is scheduled. Submitted email cannot be recalled here.</p></>}
 {['submitting','uncertain'].includes(state)&&<><p>Google may have accepted this email. Sending again is blocked to prevent a duplicate.</p><Button icon="refresh" disabled={!ready||busy||!data.enabled||!data.googleConnected} loading={busy} onClick={()=>act('reconcile')}>Check sent receipt</Button><p className="bo-hint">Checks only this message in Google Sent. An interrupted submission needs 90 seconds before checking. No match remains unresolved.</p></>}
 {state==='accepted'&&<><Button href={'/prospecting/'+data.prospectId+'/replies'} icon="history">Replies and stop review</Button><p>Google accepted one introduction. Confirm its arrival in the test inbox; this is not proof of delivery.</p><dl className="bo-delivery-receipt"><div><dt>Accepted at (UTC)</dt><dd><time dateTime={data.receipt.acceptedAt}>{data.receipt.acceptedAt.replace('T',' ').replace('Z','')}</time></dd></div><div><dt>Google message</dt><dd>{data.receipt.providerMessageId}</dd></div><div><dt>Google thread</dt><dd>{data.receipt.providerThreadId}</dd></div></dl>
 {data.followups&&!data.followups.sequence&&<section className="bo-delivery-protection" aria-label="Follow-up sequence"><h2>Approved follow-up sequence</h2><p>{data.followups.totalMessages} total cold {data.followups.totalMessages===1?'email':'emails'}, including the introduction.</p>{data.followups.reason&&<p>{data.followups.reason}</p>}<label className="bo-prospect-check"><input type="checkbox" checked={reviewed} disabled={!ready||busy||!data.followups.canActivate} onChange={e=>setReviewed(e.target.checked)}/><span>Schedule only the exact approved messages and keep all recorded stops effective.</span></label><Button variant="primary" icon="check" disabled={!ready||busy||!reviewed||!data.followups.canActivate} loading={busy} onClick={()=>act('activate-followups')}>Activate approved sequence</Button><p className="bo-hint">Activation saves the schedule. It does not enable a provider or send now.</p></section>}
 {data.followups?.sequence&&<section className="bo-delivery-protection" aria-label="Follow-up sequence"><h2>Follow-up automation</h2><div className="bo-outreach-review-status"><Status label={data.followups.sequence.state==='running'&&!data.followups.enabled?'Scheduled':data.followups.sequence.state[0].toUpperCase()+data.followups.sequence.state.slice(1)} tone={data.followups.sequence.state==='running'&&data.followups.enabled?'success':data.followups.sequence.state==='complete'||!data.followups.enabled?'neutral':'warning'}/>{!data.followups.enabled&&<Status label="Execution disabled" tone="warning"/>}</div><p>{data.followups.sequence.totalMessages} total cold {data.followups.sequence.totalMessages===1?'email':'emails'}, including the introduction.</p>{data.followups.attempt&&<p>Message {data.followups.attempt.messageNumber} is {data.followups.attempt.state}; due <time dateTime={data.followups.attempt.scheduledAt}>{data.followups.attempt.scheduledAt.replace('T',' ').replace('Z','')} UTC</time>.</p>}{data.followups.sequence.lastReason&&<p>Recorded reason: {data.followups.sequence.lastReason.replaceAll('_',' ')}.</p>}{data.followups.sequence.state==='running'&&data.followups.attempt?.state==='scheduled'&&<Button icon="refresh" disabled={!ready||busy||!data.followups.enabled} loading={busy} onClick={()=>act('run-followup')}>Run due check</Button>}{data.followups.attempt?.state==='submitting'&&<Button icon="refresh" disabled={!ready||busy||!data.followups.enabled} loading={busy} onClick={()=>act('reconcile-followup')}>Recover receipt without resending</Button>}{data.followups.sequence.state==='failed'&&data.followups.attempt?.state!=='submitting'&&<Button icon="refresh" disabled={!ready||busy||!data.followups.enabled} loading={busy} onClick={()=>act('reconcile-followup')}>Reconcile without resending</Button>}<p className="bo-hint">Every due send requires a fresh metadata check. Reply handling alone never resumes this sequence.</p></section>}
 </>}
 {state==='cancelled'&&<p>This receipt is closed. It cannot send or be reopened.</p>}
 </section></div>;
}
