import {PROSPECT_FIELDS} from '@/lib/bloomops/prospect-values.mjs';
// Uploaded prose is always escaped React text, never HTML or executable Markdown.
export default function ProspectSkillResultDocument({document}){
 return <div className="bo-result-document">
 <details className="bo-prospect-evidence"><summary>Full report</summary><p className="bo-result-prose">{document.fullReport}</p></details>
 <details className="bo-prospect-evidence"><summary>Observations and uncertainty</summary>{document.observations.map((o,i)=><section key={i}><h3>{o.interaction}</h3><dl className="bo-prospect-source-properties"><div><dt>Reported outcome</dt><dd>{o.outcome==='observed'?'Observed':o.outcome==='uncertain'?'Uncertain':'Not tested'}</dd></div><div><dt>Source</dt><dd>{o.targetUrl||'Unknown'}</dd></div><div><dt>Observed date</dt><dd>{o.observedAt||'Unknown'}</dd></div></dl><p className="bo-result-prose">{o.description}</p></section>)}{!document.observations.length&&<p>No observations supplied.</p>}<h3>Unknowns</h3>{document.unknowns.length?<ul>{document.unknowns.map((s,i)=><li key={i}>{s}</li>)}</ul>:<p>No unknowns supplied.</p>}</details>
 <details className="bo-prospect-evidence"><summary>Contact and field sources</summary><p>Public discovery does not verify email delivery. Suggested field sources remain unverified.</p><dl className="bo-prospect-source-properties"><div><dt>Contact research</dt><dd>{document.contactResearch.state.replaceAll('_',' ')}</dd></div><div><dt>Email</dt><dd>{document.contactResearch.email||'Unknown'}</dd></div><div><dt>Source</dt><dd>{document.contactResearch.sourceUrl||'Unknown'}</dd></div><div><dt>Confidence</dt><dd>{document.contactResearch.confidence}</dd></div></dl>{document.fieldSources.map(s=><section key={s.fieldKey}><h3>{PROSPECT_FIELDS[s.fieldKey].label}</h3><p>{s.sourceUrl||'Source unknown'}</p><p>Confidence: {s.confidence}</p><p>{s.note}</p></section>)}</details>
 <details className="bo-prospect-evidence"><summary>Offer suggestion</summary><p className="bo-result-prose">{document.offer.suggestion||'No offer suggested.'}</p><p>No approved price or claims supplied.</p></details>
 {document.followUps.length>0&&<details className="bo-prospect-evidence"><summary>Follow-up suggestions</summary><p>Saved suggestions. Nothing is approved, sent or scheduled.</p>{document.followUps.map(s=><section key={s.sequence}><h3>Follow-up {s.sequence-1}</h3><p className="bo-result-prose">{s.body}</p></section>)}</details>}
 </div>;
}
