'use client';
import {useEffect,useRef,useState} from 'react';
import {createSheetDraftStore,pendingSheetDraft} from '@/lib/bloomops/sheet-drafts.mjs';
import {DRAFT_CONTEXT_KEY} from '@/lib/bloomops/draft-context.mjs';
import {Button,PageHeader,Field} from './Primitives';
import {Icon} from './Icons';
import ProspectAvatar from './ProspectAvatar';
import ProspectPlatform,{PlatformIcon,PlatformOptions} from './ProspectPlatform';
import {SHEET_VIEWS,SHEET_COLUMNS,SHEET_DEFAULT_COLUMNS,SHEET_DATES,SHEET_FIT,SHEET_EDITABLE,sheetQuery,sheetPreferences,sheetDate} from '@/lib/bloomops/prospect-sheet-values.mjs';
import {normalizeProspectFields,safeProspectUrl} from '@/lib/bloomops/prospect-values.mjs';
const download=(data,name,type='application/json')=>{const url=URL.createObjectURL(new Blob([typeof data==='string'?data:JSON.stringify(data,null,2)],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
const columnWeight=(widths,k)=>widths?.[k]||({businessName:320,website:240,platform:240,personName:170,fit:220,outreach:220,nextAction:190}[k]||160);
const fieldLabel=(key,value)=>key==='fit'?(SHEET_FIT[value]||'Unknown'):(value||'Unknown');
const scopeOf=q=>JSON.stringify({...q,page:1});
export function SheetSkeleton(){return <div className="bo-sheet-skeleton" aria-label="Loading prospect sheet" role="status">{Array.from({length:8},(_,i)=><div key={i}>{Array.from({length:7},(_,j)=><span key={j}/>)}</div>)}</div>;}
export default function ProspectSheet({workspaceId,userId,workspaceName,initialQuery}){
 const key='bloomsi.sheet.'+userId+'.'+workspaceId,[prefs,setPrefs]=useState(null),[data,setData]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState({}),[edit,setEdit]=useState(null),[draft,setDraft]=useState(''),[panel,setPanel]=useState(''),[viewName,setViewName]=useState(''),[changes,setChanges]=useState(null),[undo,setUndo]=useState([]),[operation,setOperation]=useState(''),[bulkField,setBulkField]=useState('fit'),[bulkValue,setBulkValue]=useState('strong'),[search,setSearch]=useState(''),[notice,setNotice]=useState(''),[refresh,setRefresh]=useState(0);
 const [inline,setInline]=useState(null),[cellStatus,setCellStatus]=useState(null);
 const review=useRef(null),reviewOrigin=useRef(null),[reviewRequest,setReviewRequest]=useState(0);
 useEffect(()=>{if(reviewRequest&&review.current){review.current.focus({preventScroll:true});review.current.scrollIntoView({block:'center',behavior:'instant'});}},[reviewRequest]);
 const scroll=useRef(null),restore=useRef(null),counter=useRef(0),selectionAnchor=useRef(null),cellAnchor=useRef(null),[range,setRange]=useState(null),saving=useRef(false),selectedRef=useRef(selected);selectedRef.current=selected;
 const recoveredSource=useRef(null),draftStore=useRef(null),draftLatest=useRef(null),mounted=useRef(false),[copies,setCopies]=useState([]),[storageError,setStorageError]=useState(''),[recovering,setRecovering]=useState(false),[accessLost,setAccessLost]=useState(false);
 draftLatest.current=pendingSheetDraft(prefs?.query||sheetQuery(),edit,draft,changes);
 function active(){try{return mounted.current&&(!draftStore.current||draftStore.current.valid());}catch{return false;}}
 function listCopies(){try{setCopies((draftStore.current?.list()||[]).filter(c=>c.key!==draftStore.current.own).map(c=>({key:c.key,at:c.value.updatedAt,count:c.value.fields.length})));}catch{setStorageError('This browser could not read recovery copies.');}}
 function keepDraft(){if(!active())return;try{draftStore.current?.write(draftLatest.current);setStorageError(draftStore.current?'':'This browser could not keep a recovery copy. Keep this tab open until saved.');}catch{setStorageError('This browser could not keep a recovery copy. Keep this tab open until saved, or discard an old copy.');}}
 function retireSource(){const source=recoveredSource.current;if(!source)return;try{draftStore.current?.remove(source.key,source.raw);recoveredSource.current=null;listCopies();}catch{setStorageError('This recovery copy could not be removed.');}}
 function invalidate(clear=false){recoveredSource.current=null;if(clear)try{draftStore.current?.clearScope();}catch{}draftStore.current?.dispose();mounted.current=false;setAccessLost(true);setInline(null);setCellStatus(null);setChanges(null);setEdit(null);setDraft('');setCopies([]);setData(null);}
 useEffect(()=>{
  mounted.current=true;
  try{draftStore.current=createSheetDraftStore(localStorage,{userId,workspaceId},crypto.randomUUID());listCopies();}catch{setStorageError('This browser could not keep a recovery copy. Keep this tab open until saved.');}
  const context=()=>invalidate(),storage=e=>{if(e.key===DRAFT_CONTEXT_KEY||e.key===null)invalidate();else listCopies();},hide=()=>keepDraft();
  let channel;try{channel=new BroadcastChannel(DRAFT_CONTEXT_KEY);channel.onmessage=context;}catch{}
  window.addEventListener(DRAFT_CONTEXT_KEY,context);window.addEventListener('storage',storage);window.addEventListener('pagehide',hide);window.addEventListener('popstate',hide);
  return()=>{channel?.close();keepDraft();mounted.current=false;draftStore.current?.dispose();window.removeEventListener(DRAFT_CONTEXT_KEY,context);window.removeEventListener('storage',storage);window.removeEventListener('pagehide',hide);window.removeEventListener('popstate',hide);};
 },[key]);
 useEffect(()=>{keepDraft();},[edit,draft,changes,prefs?.query]);
 async function recoverCopy(copy){
  if(!active()||recovering)return;
  if((edit||changes?.length)&&!window.confirm('Replace the current unsaved fields with this recovery copy?'))return;
  setRecovering(true);setError('');
  try{
   const snapshot=draftStore.current.snapshot(copy.key),saved=snapshot?.value;if(!saved)throw Error('This recovery copy is no longer available.');
   const res=await fetch('/api/bloomops/prospecting/sheet-draft',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({userId,workspaceId,ids:[...new Set(saved.fields.map(f=>f.id))]})});
   if([401,403].includes(res.status)){invalidate(true);return;}
   if(!res.ok)throw Error('The records could not be checked. The recovery copy is still kept.');
   const body=await res.json();if(!active())return;
   if(body.userId!==userId||body.workspaceId!==workspaceId){invalidate();return;}
   if(draftStore.current.snapshot(copy.key)?.raw!==snapshot.raw)throw Error('The recovery copy changed. Review it again.');
   const records=new Map(body.rows.map(r=>[r.id,r]));
   const restored=saved.fields.map(f=>{const row=records.get(f.id);if(!row)throw Error('A record is no longer available.');return {row:{...row,[f.key]:f.before},key:f.key,value:f.value,recovered:true,...(row[f.key]!==f.before&&row[f.key]!==f.value?{error:'This field changed. Review the latest record before saving.'}:{})};});
   // Write this mount's independent copy before retiring the old snapshot.
   recoveredSource.current={key:copy.key,raw:snapshot.raw};
   try{if(draftStore.current.write({query:saved.query,fields:saved.fields}))retireSource();}catch{setStorageError('This browser could not update the recovery copy. Keep this tab open until saved.');}
   setEdit(null);setDraft('');setChanges(restored);setReviewRequest(n=>n+1);setSelected({});setRange(null);setPrefs(p=>({...p,viewId:saved.query.view,query:saved.query}));setSearch(saved.query.q);setNotice('Recovered fields are ready for review. Nothing has been submitted.');listCopies();
  }catch(e){setError(e.message);}finally{setRecovering(false);}
 }
 useEffect(()=>{let v;try{v=sheetPreferences(JSON.parse(localStorage.getItem(key)));const session=JSON.parse(sessionStorage.getItem(key)||'null');if(session&&session.scope===scopeOf(v.query)){setSelected(session.selected||{});restore.current=session.scroll;}}catch{v=sheetPreferences(null);}if(Object.keys(initialQuery||{}).length){v.query=sheetQuery({...v.query,...initialQuery,page:1})||sheetQuery();v.viewId='all';setSelected({});window.history.replaceState(window.history.state,'','/prospecting');}setPrefs(v);setSearch(v.query.q);},[key]);
 useEffect(()=>{if(prefs)try{localStorage.setItem(key,JSON.stringify(prefs));}catch{}},[prefs,key]);
 useEffect(()=>{if(!prefs)return;const seq=++counter.current,abort=new AbortController();setBusy(true);fetch('/api/bloomops/prospecting/sheet?'+new URLSearchParams(prefs.query),{signal:abort.signal}).then(async res=>{const d=await res.json();if(!res.ok){if([401,403].includes(res.status))invalidate(true);throw Error(d.error||'Could not load prospects.');}if(seq!==counter.current||!active())return;if(d.context?.userId!==userId||d.context?.workspaceId!==workspaceId){invalidate();return;}setData(d);if(d.rows.length===0&&d.total>0&&prefs.query.page>1){setPrefs(v=>({...v,query:{...v.query,page:Math.ceil(d.total/v.query.size)}}));return;}setSelected(s=>Object.fromEntries(Object.entries(s).filter(([id,row])=>!d.rows.some(r=>r.id===id&&r.revision!==row.revision))));requestAnimationFrame(()=>{if(restore.current&&scroll.current){scroll.current.scrollLeft=restore.current.left||0;scroll.current.scrollTop=restore.current.top||0;window.scrollTo(0,restore.current.window||0);restore.current=null;}});}).catch(e=>{if(e.name!=='AbortError'&&seq===counter.current)setError(e.message);}).finally(()=>{if(seq===counter.current)setBusy(false);});return()=>abort.abort();},[prefs?.query,refresh]);
 useEffect(()=>{if(!prefs)return;const save=()=>{try{sessionStorage.setItem(key,JSON.stringify({scope:scopeOf(prefs.query),selected:selectedRef.current,scroll:{left:scroll.current?.scrollLeft||0,top:scroll.current?.scrollTop||0,window:window.scrollY}}));}catch{}};window.addEventListener('pagehide',save);return()=>{save();window.removeEventListener('pagehide',save);};},[key,prefs?.query,selected]);
 useEffect(()=>{
  if(accessLost||!changes?.length&&!edit&&!operation)return;
  const beforeUnload=e=>{keepDraft();e.preventDefault();e.returnValue='';};
  const leave=e=>{const a=e.target.closest?.('a[href]');if(!a||a.target==='_blank'||a.hasAttribute('download')||e.button!==0||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;const url=new URL(a.href,location.href);if(url.href===location.href||url.origin===location.origin&&url.pathname===location.pathname&&url.search===location.search)return;if(!window.confirm('Leave this sheet? Unsaved fields will need recovery and review before saving.')){e.preventDefault();e.stopPropagation();}};
  window.addEventListener('beforeunload',beforeUnload);document.addEventListener('click',leave,true);
  return()=>{window.removeEventListener('beforeunload',beforeUnload);document.removeEventListener('click',leave,true);};
 },[changes,edit,operation,accessLost]);
 const rows=data?.rows||[],columns=prefs?.columns||SHEET_DEFAULT_COLUMNS,query=prefs?.query||sheetQuery(),count=Object.keys(selected).length,disabled=busy||!!operation||recovering||accessLost,view=SHEET_VIEWS[prefs?.viewId]||{label:prefs?.views.find(v=>v.id===prefs.viewId)?.name||'All prospects',icon:'table',color:'mauve'};
 function discardReview(){const discard=!(changes?.length||edit&&draft!==(edit.row[edit.key]??''))||window.confirm("Discard the field changes still waiting to be saved?");if(discard)retireSource();return discard;}
 function changeQuery(patch){if(saving.current||!active()||!discardReview())return;setBusy(true);setError('');setPrefs(v=>{const q={...v.query,...patch,...(!Object.hasOwn(patch,'page')?{page:1}:{})};if(scopeOf(q)!==scopeOf(v.query)){setSelected({});setRange(null);selectionAnchor.current=null;}return {...v,query:q};});setChanges(null);setEdit(null);}
 function selectView(id){if(!discardReview())return;setChanges(null);setEdit(null);setBusy(true);setError('');const custom=prefs.views.find(v=>v.id===id);setPrefs(v=>({...v,viewId:id,query:custom?{...custom.query,page:1}:{...sheetQuery(),view:id},columns:custom?.columns||SHEET_DEFAULT_COLUMNS}));setSearch(custom?.query.q||'');setSelected({});setPanel('');}
 function deleteView(id){
  if(prefs.viewId===id){if(!discardReview())return;setChanges(null);setEdit(null);setBusy(true);setError('');setSearch('');setSelected({});setRange(null);selectionAnchor.current=null;setPanel('');}
  setPrefs(p=>({...p,views:p.views.filter(v=>v.id!==id),...(p.viewId===id?{viewId:'all',query:sheetQuery()}: {})}));
 }
 function toggle(row,index,checked,shift){const start=shift&&selectionAnchor.current!==null?Math.min(selectionAnchor.current,index):index,end=shift&&selectionAnchor.current!==null?Math.max(selectionAnchor.current,index):index;selectionAnchor.current=index;setSelected(s=>{const next={...s};for(const r of rows.slice(start,end+1))if(checked)next[r.id]=r;else delete next[r.id];return next;});}
 async function selectFiltered(){setOperation('Selecting filtered records');setError('');try{const res=await fetch('/api/bloomops/prospecting/sheet?'+new URLSearchParams({...query,page:1,size:200}));const d=await res.json();if(!res.ok)throw Error(d.error||'Could not select records.');if(d.total>200)throw Error('This selection is larger than 200. Narrow the filters before selecting every result.');setSelected(Object.fromEntries(d.rows.map(r=>[r.id,r])));}catch(e){setError(e.message);}finally{setOperation('');}}
 function startEdit(row,k,custom=false){if(disabled||!SHEET_EDITABLE.includes(k)||!discardReview())return;setChanges(null);setEdit({row,key:k,custom});setDraft(row[k]??'');setError('');}
 function propose(list){const currentEdit=edit&&list.length===1&&list[0].row.id===edit.row.id&&list[0].key===edit.key&&list[0].value===draft;if(!currentEdit&&!discardReview())return;const out=[];for(const c of list){const v=normalizeProspectFields({[c.key]:c.value});if(!v.ok){setError(Object.values(v.errors).join(' '));return;}if(c.row[c.key]!==v.fields[c.key])out.push({...c,value:v.fields[c.key]});}reviewOrigin.current=document.activeElement;setChanges(out.length?out:null);if(out.length)setReviewRequest(n=>n+1);setEdit(null);setPanel('');}
 async function saveCell(row,key,input){
  if(disabled||saving.current||!active())return;
  const normalized=normalizeProspectFields({[key]:input});
  if(!normalized.ok){setError(Object.values(normalized.errors).join(' '));return;}
  const value=normalized.fields[key],ownEditor=edit?.row.id===row.id&&edit.key===key;
  if(!ownEditor&&!discardReview())return;
  setEdit(null);setDraft('');setError('');
  if(value===row[key]){setChanges(null);return;}
  const change={row,key,value};setInline(change);setChanges([change]);setCellStatus({key,state:'saving'});
  await apply([change],false,true);
 }
 async function apply(list,isUndo=false,direct=false){
  if(saving.current||disabled||!active())return;
  saving.current=true;if(!direct)setCellStatus(null);setOperation((isUndo?'Undoing':'Saving')+' 0 of '+list.length);setError('');setNotice('');
  const complete=[],failed=[];let alreadySaved=0;
  try{
   for(let i=0;i<list.length;i++){
    if(!active())break;const c=list[i];setOperation((isUndo?'Undoing':'Saving')+' '+(i+1)+' of '+list.length);
    try{
     if(isUndo){
      const res=await fetch('/api/bloomops/prospecting/sheet-edit',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({userId,id:c.row.id,undoEventId:c.undoEventId})}),body=await res.json();
      if(!res.ok){if([401,403].includes(res.status))invalidate(true);throw Error(body.error||'Could not undo this edit');}
      complete.push(c);continue;
     }
     const read=await fetch('/api/bloomops/prospecting/'+c.row.id);
     if(!read.ok){if([401,403].includes(read.status))invalidate(true);throw Error('Access unavailable');}
     const current=(await read.json()).profile;if(!active())break;
     const normalized=normalizeProspectFields({[c.key]:c.value});if(!normalized.ok)throw Error(Object.values(normalized.errors).join(' '));const value=normalized.fields[c.key];
     if(current[c.key]===value){alreadySaved++;if(direct&&active())setData(d=>({...d,rows:d.rows.map(r=>r.id===c.row.id?{...r,[c.key]:value,revision:current.revision}:r)}));continue;}
     if(current[c.key]!==c.row[c.key])throw Error('Field changed since preview. Cancel this edit and review the latest value.');
     const res=await fetch('/api/bloomops/prospecting/sheet-edit',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({userId,id:c.row.id,query,patch:{workspaceId,expectedRevision:current.revision,fields:{[c.key]:value}}})});
     const body=await res.json();
     if(!res.ok){if([401,403].includes(res.status))invalidate(true);throw Error(Object.values(body.errors||{}).join(' ')||body.error||'Could not confirm save');}
     if(direct&&active())setData(d=>({...d,rows:d.rows.map(r=>r.id===c.row.id?{...r,[c.key]:value,revision:body.revision}:r)}));
     complete.push({undoEventId:body.undoEventId,row:{...c.row,[c.key]:value},key:c.key,value:c.row[c.key]??null});
     if(active()&&!direct)setChanges([...failed,...list.slice(i+1)]);
    }catch(e){failed.push({...c,error:e.message});}
   }
   if(!active())return;
   setUndo(previous=>isUndo?failed:[...complete.reverse(),...previous]);
   if(!isUndo){if(!failed.length)retireSource();setChanges(failed.length?failed:null);}
   if(direct){setInline(null);setCellStatus({key:list[0].key,state:failed.length?'error':'saved'});if(failed.length)setReviewRequest(n=>n+1);}
   setSelected({});
   setNotice(direct&&!failed.length?'':isUndo?complete.length+' field changes undone.':complete.length+' field changes saved.'+(alreadySaved?' '+alreadySaved+' already saved; no additional write.':''));
   if(failed.length)setError(isUndo?'Some changes could not be undone. Retry Undo edits.':'Save failed for '+failed.length+' field changes. Your values are kept below for review and retry.');
   setRefresh(v=>v+1);
  }finally{saving.current=false;setOperation('');}
 }
 async function exportSelected(audit=false){setOperation(audit?'Preparing manual audit batch':'Exporting selected records');setError('');try{const res=await fetch('/api/bloomops/prospecting/sheet-export',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({workspaceId,kind:audit?'audit':'records',query,rows:Object.values(selected).map(r=>({id:r.id,revision:r.revision}))})});const data=await res.json();if(!res.ok)throw Error(data.error||'Could not prepare export.');download(data,audit?'bloomsi-manual-audit-batch.json':'bloomsi-prospects.json');setNotice(audit?'Batch downloaded. Run each task manually in ChatGPT, then review the returned results.':'Selected records exported.');}catch(e){setError(e.message);}finally{setOperation('');}}
 function focusCell(r,c){scroll.current?.querySelector(`[data-row="${r}"][data-col="${c}"]`)?.focus();}
 function keyboard(e,r,c,row,k){if(e.target!==e.currentTarget)return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const nr=Math.max(0,Math.min(rows.length-1,r+(e.key==='ArrowDown'?1:e.key==='ArrowUp'?-1:0))),nc=Math.max(0,Math.min(columns.length-1,c+(e.key==='ArrowRight'?1:e.key==='ArrowLeft'?-1:0)));if(e.shiftKey){cellAnchor.current??={r,c};setRange({start:cellAnchor.current,end:{r:nr,c:nc}});}else{cellAnchor.current={r:nr,c:nc};setRange(null);}focusCell(nr,nc);}if(e.key==='F2'||e.key==='Enter'){e.preventDefault();startEdit(row,k);}}
 function paste(e,r,c){if(e.target!==e.currentTarget||disabled)return;const text=e.clipboardData.getData('text/plain');if(text.length>100000){e.preventDefault();setError('Paste up to 200 cells.');return;}const grid=text.replace(/\r/g,'').replace(/\n$/,'').split('\n').map(x=>x.split('\t'));if(grid.flat().length>200){e.preventDefault();setError('Paste up to 200 cells.');return;}const list=[];for(let i=0;i<grid.length;i++)for(let j=0;j<grid[i].length;j++){const row=rows[r+i],k=columns[c+j];if(!row||!SHEET_EDITABLE.includes(k)){e.preventDefault();setError('Paste only into editable fields within the current page.');return;}let value=grid[i][j];if(k==='fit')value=Object.keys(SHEET_FIT).find(x=>SHEET_FIT[x].toLowerCase()===value.toLowerCase())||value;list.push({row,key:k,value});}e.preventDefault();propose(list);}
 function copy(e,r,c){if(e.target!==e.currentTarget)return;const area=range||{start:{r,c},end:{r,c}};const values=rows.slice(Math.min(area.start.r,area.end.r),Math.max(area.start.r,area.end.r)+1).map(row=>columns.slice(Math.min(area.start.c,area.end.c),Math.max(area.start.c,area.end.c)+1).map(k=>String(row[k]??'').replace(/[\t\r\n]/g,' ')).join('\t')).join('\n');e.clipboardData.setData('text/plain',values);e.preventDefault();}
 function resize(e,k){e.preventDefault();const start=e.clientX,width=columnWeight(prefs.widths,k),move=event=>setPrefs(v=>({...v,widths:{...v.widths,[k]:Math.round(Math.max(160,Math.min(480,width+event.clientX-start)))}})),up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true});}
 function value(row,k){if(inline?.row.id===row.id&&inline.key===k)row={...row,[k]:inline.value};if(Object.hasOwn(SHEET_DATES,k))return sheetDate(row[k],k==='lastContacted'?'Never':'—');if(k==='platform'||k==='fit')return <div className={'bo-sheet-choice '+(k==='fit'?'fit-'+row.fit:'')}>
  {k==='platform'?<PlatformIcon value={row.platform}/>:<Icon name={row.fit==='strong'?'check':row.fit==='hold'?'history':row.fit==='skip'?'close':'eye'}/>}<span aria-hidden="true">{k==='platform'?(row.platform||'Unknown'):SHEET_FIT[row.fit]}</span><Icon name="chevron-down"/>
  <select aria-label={'Change '+SHEET_COLUMNS[k]+' for '+row.businessName} value={row[k]??''} disabled={disabled} onDoubleClick={e=>e.stopPropagation()} onChange={e=>{if(disabled||!active())return;if(k==='platform'&&e.target.selectedOptions[0].dataset.custom)startEdit(row,k,true);else saveCell(row,k,e.target.value);}}>
   {k==='platform'?<PlatformOptions value={row.platform??''}/>:Object.entries(SHEET_FIT).map(([value,label])=><option key={value} value={value}>{label}</option>)}
  </select>
 </div>;if(k==='outreach')return <div className={'bo-sheet-choice bo-sheet-stage stage-'+row.outreach.toLowerCase().replaceAll(' ','-')} title={row.closedReason||undefined}><Icon name={row.outreach==='Won'?'check':row.outreach==='Replied'?'message':'mail'}/><span aria-hidden="true">{row.outreach}</span><Icon name="chevron-down"/>
  <select aria-label={'Outreach actions for '+row.businessName} value="" disabled={disabled} onDoubleClick={e=>e.stopPropagation()} onChange={e=>{const action=e.target.value;if(!action||disabled||!active())return;const path='/prospecting/'+row.id;window.location.assign(['contact','interest','resolved'].includes(action)?path+'?contactEvent='+action+'#conversation-records':path+(action==='conversion'?'/conversion':'/outreach'));}}>
   <option value="" disabled>{row.outreach}</option><option value="contact">Log contact…</option><option value="interest">Record interest…</option><option value="resolved">Mark reply handled…</option><option value="outreach">Review outreach…</option><option value="conversion">Review client handoff…</option>
  </select>
 </div>;if(k==='nextAction')return <a className="bo-sheet-next-action" href={'/prospecting/'+row.id}><span>{row.nextAction}</span><Icon name="chevron-right"/></a>;if(k==='importBatch')return row[k]?<a href={'/prospecting?batch='+row[k]}>View batch</a>:'—';return row[k]||<span className="bo-sheet-muted">Unknown</span>;}
 if(accessLost)return <div className="bo-prospect-page"><PageHeader title="Prospects"/><p role="alert">Your account or workspace access changed. Reload to continue.</p><Button onClick={()=>window.location.reload()}>Reload</Button></div>;
 return <div className="bo-prospect-page bo-sheet-page"><PageHeader title="Prospects" subtitle={workspaceName} actions={<><a className="bo-sheet-download" href="/api/bloomops/prospecting/sample-csv" download><Icon name="download"/>Sample CSV</a><Button href="/prospecting/new" icon="plus">Add prospect</Button><Button href="/prospecting/import/csv" variant="primary" icon="upload">Import prospects</Button></>}/>
 {storageError&&<p role="alert" className="bo-prospect-notice">{storageError}</p>}
 {data&&copies.length>0&&<section className="bo-sheet-recovery" aria-label="Recovery copies"><h2>Unsaved fields from an earlier visit</h2>{copies.map(c=><div key={c.key}><span>{c.count} fields <time dateTime={new Date(c.at).toISOString()}>{new Date(c.at).toLocaleString()}</time></span><Button disabled={disabled} onClick={()=>recoverCopy(c)}>Review recovered fields</Button><Button disabled={disabled} onClick={()=>{if(window.confirm('Discard this recovery copy?')){try{draftStore.current.remove(c.key);listCopies();}catch{setStorageError('This recovery copy could not be removed.');}}}}>Discard copy</Button></div>)}<p>Copies stay in this browser for seven days. Sign out clears them.</p></section>}
 {recovering&&<p role="status">Checking current record access…</p>}
 <section className="bo-sheet" aria-label="Prospect sheet"><div className="bo-sheet-toolbar"><div className="bo-sheet-menu-anchor"><Button disabled={!prefs||disabled} onClick={()=>setPanel(panel==='views'?'':'views')} aria-expanded={panel==='views'}><span className={'bo-sheet-view-icon '+view.color}><Icon name={view.icon}/></span>{view.label}<Icon name="chevron-down"/></Button>{panel==='views'&&<div className="bo-sheet-menu"><nav aria-label="Saved views">{Object.entries(SHEET_VIEWS).map(([id,v])=><button key={id} onClick={()=>selectView(id)} aria-current={prefs.viewId===id?'true':undefined}><span className={'bo-sheet-view-icon '+v.color}><Icon name={v.icon}/></span>{v.label}{prefs.viewId===id&&<Icon name="check"/>}</button>)}</nav><h3>My views</h3>{prefs.views.map(v=><div className="bo-sheet-custom-view" key={v.id}><button onClick={()=>selectView(v.id)}><span className="bo-sheet-view-icon mauve"><Icon name="table"/></span>{v.name}</button><button aria-label={'Delete view '+v.name} onClick={()=>deleteView(v.id)}><Icon name="close"/></button></div>)}<form onSubmit={e=>{e.preventDefault();if(!viewName.trim())return;const id=crypto.randomUUID();setPrefs(p=>({...p,viewId:id,views:[...p.views,{id,name:viewName.trim(),query:{...p.query,page:1},columns:p.columns}]}));setViewName('');setPanel('');}}><Field id="sheet-view-name" label="Name this view"><input id="sheet-view-name" className="bo-control" maxLength={60} value={viewName} onChange={e=>setViewName(e.target.value)} required/></Field><Button type="submit" disabled={prefs.views.length>=30}>Save current view</Button></form></div>}</div>
 {cellStatus&&<span className={'bo-sheet-save-status '+cellStatus.state} role="status"><Icon name={cellStatus.state==='saved'?'check':cellStatus.state==='error'?'close':'history'}/>{SHEET_COLUMNS[cellStatus.key]} {cellStatus.state==='saving'?'saving…':cellStatus.state==='saved'?'saved':'not saved'}</span>}
 <span className="bo-sheet-count" role="status">{data?data.total.toLocaleString()+(data.total===1?' record':' records'):'Loading records'}</span><form role="search" onSubmit={e=>{e.preventDefault();changeQuery({q:search});}} className="bo-sheet-search"><label className="bo-sr-only" htmlFor="sheet-search">Search prospects</label><Icon name="search"/><input id="sheet-search" type="search" value={search} maxLength={160} placeholder="Search prospects" disabled={!prefs||!!operation} onChange={e=>setSearch(e.target.value)}/><button type="submit" aria-label="Search prospects"><Icon name="chevron-right"/></button></form>
 {['filter','sort','columns'].map(name=><div className="bo-sheet-menu-anchor" key={name}><Button disabled={!prefs||disabled} onClick={()=>setPanel(panel===name?'':name)} aria-expanded={panel===name} icon={name==='filter'?'filter':name==='sort'?'sort':'table'}>{name[0].toUpperCase()+name.slice(1)}</Button>{panel===name&&<div className="bo-sheet-menu">
 {name==='filter'&&<><Field id="sheet-fit" label="Fit"><select className="bo-control" id="sheet-fit" value={query.fit} onChange={e=>changeQuery({fit:e.target.value})}><option value="">Any fit</option>{Object.entries(SHEET_FIT).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field>{[['region','Region'],['platform','Platform'],['batch','Import batch']].map(([k,label])=><Field id={'sheet-'+k} label={label} key={k}>{k==='platform'?<ProspectPlatform id={'sheet-'+k} label={label} value={query[k]} emptyLabel="Any platform" onChange={value=>changeQuery({[k]:value})}/>:<input className="bo-control" id={'sheet-'+k} value={query[k]} onChange={e=>changeQuery({[k]:e.target.value})} maxLength={160}/>}</Field>)}<label><input type="checkbox" checked={query.never==='1'} onChange={e=>changeQuery({never:e.target.checked?'1':''})}/>Never contacted</label></>}
 {name==='sort'&&<><Field id="sheet-sort" label="Sort by"><select id="sheet-sort" className="bo-control" value={query.sort} onChange={e=>changeQuery({sort:e.target.value})}>{Object.entries(SHEET_DATES).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field><Field id="sheet-direction" label="Order"><select id="sheet-direction" className="bo-control" value={query.direction} onChange={e=>changeQuery({direction:e.target.value})}><option value="desc">Newest first</option><option value="asc">Oldest first</option></select></Field></>}
 {name==='columns'&&Object.entries(SHEET_COLUMNS).map(([k,v])=><label key={k}><input type="checkbox" checked={columns.includes(k)} disabled={k==='businessName'} onChange={e=>{setPrefs(p=>({...p,columns:e.target.checked?[...p.columns,k]:p.columns.filter(x=>x!==k)}));setRange(null);}}/>{v}</label>)}<Button onClick={()=>setPanel('')}>Done</Button></div>}</div>)}<Button icon="refresh" aria-label="Refresh prospects" disabled={!prefs||disabled} onClick={()=>{setError('');setRefresh(v=>v+1);}}/></div>
 {prefs&&(query.view!=='all'||['q','fit','region','platform','batch','never'].some(k=>query[k]))&&<div className="bo-sheet-active-filters"><span>Filtered: {[query.view!=='all'?SHEET_VIEWS[query.view].label:null,query.q?'Search: '+query.q:null,query.fit?'Fit: '+SHEET_FIT[query.fit]:null,query.region?'Region: '+query.region:null,query.platform?'Platform: '+query.platform:null,query.batch?'Import batch selected':null,query.never?'Never contacted':null].filter(Boolean).map((label,i)=><span className="bo-sheet-filter-value" key={i}>{label}</span>)}</span><Button onClick={()=>{changeQuery({view:'all',q:'',fit:'',region:'',platform:'',batch:'',never:''});setSearch('');}}>Clear filters</Button></div>}
 {error&&<p role="alert" className="bo-prospect-notice">{error}<Button disabled={!!operation} onClick={()=>{setError('');setRefresh(v=>v+1);}}>Refresh</Button></p>}{(notice||operation||busy&&data)&&<p className="bo-sheet-progress" role="status">{operation||busy?'Updating… '+operation:notice}</p>}
 {!data?<SheetSkeleton/>:<div className={'bo-sheet-scroll'+(columns.length>8?' bo-sheet-wrap-fields':'')} ref={scroll} aria-label="Prospect records" tabIndex={0} aria-busy={busy}><table className="bo-sheet-table" role="table"><colgroup><col style={{width:48}}/>{columns.map(k=><col key={k} style={{width:`${95*columnWeight(prefs.widths,k)/columns.reduce((sum,key)=>sum+columnWeight(prefs.widths,key),0)}%`}}/>)}</colgroup><thead role="rowgroup"><tr role="row"><th className="bo-sheet-check" role="columnheader"><input type="checkbox" aria-label="Select current page" disabled={disabled||!rows.length} checked={!!rows.length&&rows.every(r=>selected[r.id])} ref={n=>{if(n)n.indeterminate=rows.some(r=>selected[r.id])&&!rows.every(r=>selected[r.id]);}} onChange={e=>setSelected(s=>{const v={...s};for(const r of rows)if(e.target.checked)v[r.id]=r;else delete v[r.id];return v;})}/><span className="bo-sheet-select-label">Select page</span></th>{columns.map(k=><th key={k} role="columnheader" scope="col" className={k==='businessName'?'bo-sheet-business':''}>{SHEET_COLUMNS[k]}<span className="bo-sheet-resize" role="separator" aria-label={'Resize '+SHEET_COLUMNS[k]} aria-orientation="vertical" aria-valuenow={columnWeight(prefs.widths,k)} aria-valuemin={160} aria-valuemax={480} tabIndex={0} onPointerDown={e=>resize(e,k)} onKeyDown={e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();setPrefs(v=>({...v,widths:{...v.widths,[k]:Math.min(480,Math.max(160,(columnWeight(v.widths,k))+(e.key==='ArrowRight'?20:-20)))}}));}}}/></th>)}</tr></thead><tbody role="rowgroup">{rows.map((row,r)=><tr role="row" key={row.id} className={selected[row.id]?'is-selected':''}><td role="cell" className="bo-sheet-check"><input type="checkbox" aria-label={'Select '+row.businessName} disabled={disabled} checked={!!selected[row.id]} onChange={e=>toggle(row,r,e.target.checked,e.nativeEvent.shiftKey)}/></td>{columns.map((k,c)=><td role="cell" key={k} className={(k==='businessName'?'bo-sheet-business ':'')+(range&&r>=Math.min(range.start.r,range.end.r)&&r<=Math.max(range.start.r,range.end.r)&&c>=Math.min(range.start.c,range.end.c)&&c<=Math.max(range.start.c,range.end.c)?'is-range':'')} tabIndex={0} data-row={r} data-col={c} aria-label={SHEET_COLUMNS[k]+' for '+row.businessName} onKeyDown={e=>keyboard(e,r,c,row,k)} onPaste={e=>paste(e,r,c)} onCopy={e=>copy(e,r,c)} onDoubleClick={()=>startEdit(row,k)}>
 <span className="bo-sheet-field-label" aria-hidden="true">{SHEET_COLUMNS[k]}</span>{edit?.row.id===row.id&&edit.key===k?<form className="bo-sheet-cell-editor" onKeyDown={e=>{if(e.key==='Escape'){e.stopPropagation();setEdit(null);}}} onSubmit={e=>{e.preventDefault();saveCell(row,k,draft);}}>{k==='platform'?<ProspectPlatform label="Edit Platform" initialCustom={edit.custom} autoFocus value={draft} onChange={setDraft}/>:k==='fit'?<select aria-label={'Edit '+SHEET_COLUMNS[k]} autoFocus value={draft} onChange={e=>setDraft(e.target.value)}>{Object.entries(SHEET_FIT).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>:<input aria-label={'Edit '+SHEET_COLUMNS[k]} autoFocus value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Escape')setEdit(null);}}/>}<button type="submit" aria-label="Save field"><Icon name="check"/></button><button type="button" aria-label="Cancel edit" onClick={()=>setEdit(null)}><Icon name="close"/></button></form>:<div className="bo-sheet-cell-content">{k==='businessName'?<><ProspectAvatar id={row.id} website={row.website} size="list"/><a href={'/prospecting/'+row.id}>{row.businessName}</a></>:k==='personName'&&row.personName?<a href={'/prospecting/'+row.id}>{row.personName}</a>:k==='website'&&safeProspectUrl(row.website)?<a className="bo-sheet-website" href={safeProspectUrl(row.website)} target="_blank" rel="noreferrer"><span>{new URL(row.website).hostname}</span><Icon name="external-link"/></a>:value(row,k)}{SHEET_EDITABLE.includes(k)&&!['platform','fit'].includes(k)&&<button className="bo-sheet-edit" aria-label={'Edit '+SHEET_COLUMNS[k]+' for '+row.businessName} disabled={disabled} onClick={()=>startEdit(row,k)}><Icon name="edit"/></button>}</div>}
 </td>)}</tr>)}</tbody></table>{!rows.length&&!busy&&<div className="bo-sheet-empty"><h2>{data.total?'No rows on this page':'No matching prospects'}</h2><p>Add a prospect or adjust the filters.</p><Button href="/prospecting/new">Add prospect</Button></div>}</div>}
 {!!count&&<div className="bo-sheet-selection" aria-label="Selected prospect actions"><strong>{count} selected</strong><Button disabled={disabled} variant="primary" icon="skills" onClick={()=>exportSelected(true)}>Prepare audit batch</Button><Button disabled={disabled} icon="edit" onClick={()=>setPanel('bulk')}>Edit fields</Button><Button disabled={disabled} icon="download" onClick={()=>exportSelected(false)}>Export</Button><Button disabled={disabled} onClick={selectFiltered}>Select every filtered result</Button><Button disabled={disabled} onClick={()=>setSelected({})}>Clear selection</Button><a href="/prospecting/skills/batch">Review returned audits</a></div>}
 {panel==='bulk'&&<form className="bo-sheet-bulk" onSubmit={e=>{e.preventDefault();propose(Object.values(selected).map(row=>({row,key:bulkField,value:bulkValue})));}}><h2>Edit selected records</h2><Field id="bulk-field" label="Field"><select className="bo-control" id="bulk-field" value={bulkField} onChange={e=>{setBulkField(e.target.value);setBulkValue('');}}>{SHEET_EDITABLE.filter(k=>!['businessName','personName'].includes(k)).map(k=><option key={k} value={k}>{SHEET_COLUMNS[k]}</option>)}</select></Field><Field id="bulk-value" label="New value">{bulkField==='platform'?<ProspectPlatform id="bulk-value" label="New platform" value={bulkValue} onChange={setBulkValue}/>:bulkField==='fit'?<select id="bulk-value" className="bo-control" value={bulkValue} onChange={e=>setBulkValue(e.target.value)}>{Object.entries(SHEET_FIT).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select>:<input className="bo-control" id="bulk-value" value={bulkValue} onChange={e=>setBulkValue(e.target.value)}/>}</Field><Button type="submit">Preview changes</Button><Button onClick={()=>setPanel('')}>Cancel</Button></form>}
 {changes&&!inline&&<section ref={review} tabIndex={-1} className="bo-sheet-bulk bo-sheet-review" aria-label="Preview field changes"><h2>{changes.length===1?'Review change':'Review '+changes.length+' changes'}</h2><p className="bo-sheet-review-hint">Not saved yet. Review and save below.</p><div className="bo-sheet-change-list">{changes.map((c,i)=><p key={i}><strong>{c.row.businessName}</strong><br/>{SHEET_COLUMNS[c.key]}: {fieldLabel(c.key,c.row[c.key])} → {c.recovered?<label className="bo-sheet-recovered-value">Your value<input aria-label={'Recovered '+SHEET_COLUMNS[c.key]+' for '+c.row.businessName} className="bo-control" disabled={disabled} value={c.value??''} onChange={e=>setChanges(list=>list.map((x,n)=>n===i?{...x,value:e.target.value,error:undefined}:x))}/></label>:fieldLabel(c.key,c.value)}{c.error&&<span className="bo-sheet-save-error">{c.error}</span>}</p>)}</div><Button variant="primary" disabled={disabled||!changes.length} onClick={()=>apply(changes)}>{changes.some(c=>c.error)?'Retry failed changes':'Save changes'}</Button><Button disabled={disabled} onClick={()=>{retireSource();setChanges(null);setCellStatus(null);reviewOrigin.current?.isConnected&&reviewOrigin.current.focus();}}>Cancel</Button></section>}
 {!!undo.length&&<div className="bo-sheet-undo"><span>{undo.length} saved changes can be undone.</span><Button disabled={disabled} onClick={()=>apply(undo,true)}>Undo edits</Button></div>}
 <footer className="bo-sheet-footer"><label>Rows per page <select aria-label="Rows per page" value={query.size} disabled={!prefs||disabled} onChange={e=>changeQuery({size:Number(e.target.value)})}>{[25,50,100,200].map(n=><option key={n} value={n}>{n}</option>)}</select></label><span>{data?.total?(query.page-1)*query.size+1:0}–{data?Math.min(query.page*query.size,data.total):0} of {data?.total??'…'}</span><Button icon="chevron-left" aria-label="Previous page" disabled={!prefs||disabled||query.page<=1} onClick={()=>changeQuery({page:query.page-1})}/><span>Page {query.page}</span><Button icon="chevron-right" aria-label="Next page" disabled={!prefs||disabled||!data||query.page*query.size>=data.total} onClick={()=>changeQuery({page:query.page+1})}/></footer></section></div>;
}
