'use client';
import {useEffect,useRef,useState} from 'react';
import {Button,PageHeader} from './Primitives';
import {validateWorkSetup,WORK_SETUP_LIMITS} from '@/lib/bloomops/work-setup-values.mjs';
const empty=()=>({schemaVersion:1,name:'',description:'',project:{startOffset:null,targetOffset:null},milestones:[],actions:[{key:'action_1',title:'',instructions:'',milestoneKey:null,dueOffset:null,dependsOn:[]}],deliverables:[]});
const date=value=>value||'Undated';
function Offset({label,value,onChange}){return <label>{label}<input type="number" min="-3660" max="3660" step="1" value={value??''} onChange={e=>onChange(e.target.value===''?null:Number(e.target.value))}/></label>;}
export default function WorkSetup({initial=null,scope,options=null}){
 const [definition,setDefinition]=useState(()=>initial?.definition||empty()),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[denied,setDenied]=useState(false),[conflict,setConflict]=useState(false);
 const [selection,setSelection]=useState({clientId:'',serviceEngagementId:'',eventName:'',eventDate:''}),[preview,setPreview]=useState(null),[previewBusy,setPreviewBusy]=useState(false),[projectId,setProjectId]=useState(null);
 const [ready,setReady]=useState(false);
 const live=useRef(true),readGeneration=useRef(0),writeGeneration=useRef(0),previewGeneration=useRef(0),dirtyRef=useRef(false),pending=useRef(null),writing=useRef(false);
 const canEdit=initial?initial.canEdit:true,locked=!ready||busy||!!pending.current||conflict||!canEdit;
 const endpoint=initial?`/api/bloomops/work-setups/${initial.id}`:'/api/bloomops/work-setups';
 function revoke(){writeGeneration.current++;previewGeneration.current++;writing.current=false;pending.current=null;dirtyRef.current=false;setBusy(false);setPreviewBusy(false);setPreview(null);setDenied(true);setError('Your workspace or setup access changed. Reopen Work in the correct workspace.');}
 const sameScope=b=>b.scope?.userId===scope.userId&&b.scope?.workspaceId===scope.workspaceId;
 useEffect(()=>{live.current=true;setReady(true);const leave=e=>{if(dirtyRef.current||pending.current){e.preventDefault();e.returnValue='';}};
  const link=e=>{if(e.target.closest('a[href]')&&(dirtyRef.current||pending.current)&&!window.confirm('Leave this setup with unsaved changes or an unresolved request?'))e.preventDefault();};
  async function refresh(){const generation=++readGeneration.current;try{const r=await fetch(endpoint,{cache:'no-store'}),b=await r.json();if(!live.current||generation!==readGeneration.current)return;
   if([401,403,404].includes(r.status)||r.ok&&!sameScope(b)||r.ok&&canEdit&&(initial?!b.setup?.canEdit:!b.canEdit)){revoke();return;}
   if(r.ok&&initial&&b.setup?.revision!==initial.revision&&!writing.current){setConflict(true);setPreview(null);setMessage('A newer saved version is available. Your unsaved edits remain here.');}
  }catch{/* Mutations independently recheck authority. Network errors retain edits. */}}
  document.addEventListener('click',link);window.addEventListener('beforeunload',leave);window.addEventListener('focus',refresh);window.addEventListener('pageshow',refresh);const timer=setInterval(refresh,30000);
  return()=>{live.current=false;readGeneration.current++;writeGeneration.current++;previewGeneration.current++;clearInterval(timer);document.removeEventListener('click',link);window.removeEventListener('beforeunload',leave);window.removeEventListener('focus',refresh);window.removeEventListener('pageshow',refresh);};
 },[endpoint,scope.userId,scope.workspaceId]);
 function change(update){dirtyRef.current=true;setDirty(true);setDefinition(update);setMessage('');setPreview(null);previewGeneration.current++;setPreviewBusy(false);}
 function rowChange(kind,key,patch){change(d=>({...d,[kind]:d[kind].map(r=>r.key===key?{...r,...patch}:r)}));}
 function add(kind){const key='item_'+crypto.randomUUID().replaceAll('-','');const row=kind==='milestones'?{key,name:'',startOffset:null,targetOffset:null}:kind==='actions'?{key,title:'',instructions:'',milestoneKey:null,dueOffset:null,dependsOn:[]}:{key,title:'',instructions:'',targetOffset:null};change(d=>({...d,[kind]:[...d[kind],row]}));}
 function remove(kind,key){change(d=>({...d,[kind]:d[kind].filter(r=>r.key!==key),...(kind==='milestones'?{actions:d.actions.map(r=>({...r,milestoneKey:r.milestoneKey===key?null:r.milestoneKey}))}:kind==='actions'?{actions:d.actions.filter(r=>r.key!==key).map(r=>({...r,dependsOn:r.dependsOn.filter(k=>k!==key)}))}:{})}));}
 function choose(patch){previewGeneration.current++;setPreviewBusy(false);setPreview(null);setSelection(s=>({...s,...patch}));setError('');}
 const selectionBody=()=>({...scope,templateId:initial.id,versionId:initial.versionId,expectedRevision:initial.revision,...selection,serviceEngagementId:selection.serviceEngagementId||null});
 async function propose(e){e.preventDefault();if(previewBusy||writing.current||dirty||conflict||denied)return;const generation=++previewGeneration.current;setPreviewBusy(true);setError('');try{
  const r=await fetch('/api/bloomops/work-setups/preview',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(selectionBody())}),b=await r.json();if(!live.current||generation!==previewGeneration.current)return;
  if([401,403,404].includes(r.status)||r.ok&&!sameScope(b)){revoke();return;}if(!r.ok)throw Error(b.error||'Could not preview this job.');setPreview(b);setMessage('Review the complete proposed job before creating it.');
 }catch(e){if(live.current&&generation===previewGeneration.current)setError(e.message);}finally{if(live.current&&generation===previewGeneration.current)setPreviewBusy(false);}}
 async function mutate(operation){if(!ready||writing.current||denied||conflict)return;let command=pending.current;
  if(!command){if(operation==='save'){let validated;try{validated=validateWorkSetup(definition);}catch(e){setError(e.message);return;}command={operation,url:'/api/bloomops/work-setups',method:'POST',body:{...scope,requestId:crypto.randomUUID(),templateId:initial?.id||null,expectedRevision:initial?.revision||0,definition:validated}};}
   else if(operation==='generate'){if(!preview||dirty)return;command={operation,url:'/api/bloomops/work-setups/generate',method:'POST',body:{...selectionBody(),requestId:crypto.randomUUID(),planHash:preview.planHash}};}
   else{if(dirty)return;command={operation,url:endpoint,method:'PATCH',body:{...scope,requestId:crypto.randomUUID(),expectedRevision:initial.revision,active:!initial.active}};}}
  pending.current=command;writing.current=true;const generation=++writeGeneration.current;setBusy(true);setError('');setMessage('');
  try{const r=await fetch(command.url,{method:command.method,headers:{'content-type':'application/json'},body:JSON.stringify(command.body)}),b=await r.json();if(!live.current||generation!==writeGeneration.current)return;
   if([401,403,404].includes(r.status)||r.ok&&!sameScope(b)){revoke();return;}if(!r.ok){if(r.status<500)pending.current=null;if(r.status===409){setConflict(true);setPreview(null);}throw Error(b.error||'Request failed. Retry the same request.');}
   pending.current=null;dirtyRef.current=false;setDirty(false);if(command.operation==='generate'){setProjectId(b.projectId);setPreview(null);setMessage('Job created. Open its Work records below.');}else window.location.assign(`/work/setups/${b.id}`);
  }catch(e){if(live.current&&generation===writeGeneration.current)setError(e.message);}finally{if(live.current&&generation===writeGeneration.current){writing.current=false;setBusy(false);}}
 }
 if(denied)return <p role="alert">{error}</p>;
 return <div className="bo-work-setup"><Button href="/work/setups" variant="ghost">Back to setups</Button><PageHeader title={initial?definition.name:'New Work setup'} subtitle="Reusable structure and instructions. Every generated job starts fresh."/>
 {error&&<p role="alert">{error}</p>}<p role="status">{message||(dirty?'Unsaved setup changes.':initial?`Saved version ${initial.version}${initial.active?'':' (retired)'}.`:'Not saved yet.')}</p>
 {conflict&&<Button href={initial?`/work/setups/${initial.id}`:'/work/setups'}>Reopen saved setup</Button>}
 {pending.current&&!busy&&<Button onClick={()=>mutate(pending.current.operation)}>Retry request</Button>}
 {projectId&&<Button href={`/work/projects/${projectId}`} variant="primary">Open generated project</Button>}
 <form onSubmit={e=>{e.preventDefault();mutate('save');}}><fieldset disabled={locked}><legend>Setup definition</legend><div className="bo-work-setup-grid">
 <label>Setup name<input required maxLength={120} value={definition.name} onChange={e=>change(d=>({...d,name:e.target.value}))}/></label><label>Description<textarea maxLength={2000} value={definition.description} onChange={e=>change(d=>({...d,description:e.target.value}))}/></label>
 <Offset label="Project start offset" value={definition.project.startOffset} onChange={value=>change(d=>({...d,project:{...d.project,startOffset:value}}))}/><Offset label="Project target offset" value={definition.project.targetOffset} onChange={value=>change(d=>({...d,project:{...d.project,targetOffset:value}}))}/></div>
 <p>Dates use calendar days from the event date. Negative numbers are before it, zero is the event day, and blank is undated. Use {'{{event}}'} in names or instructions for the event name.</p>
 <h2>Milestones</h2>{definition.milestones.map((row,i)=><fieldset className="bo-work-setup-row" key={row.key}><legend>Milestone {i+1}</legend><div className="bo-work-setup-grid"><label>Milestone name<input required maxLength={120} value={row.name} onChange={e=>rowChange('milestones',row.key,{name:e.target.value})}/></label><Offset label="Milestone start offset" value={row.startOffset} onChange={startOffset=>rowChange('milestones',row.key,{startOffset})}/><Offset label="Milestone target offset" value={row.targetOffset} onChange={targetOffset=>rowChange('milestones',row.key,{targetOffset})}/></div><Button onClick={()=>remove('milestones',row.key)}>Remove milestone {i+1}</Button></fieldset>)}<Button disabled={definition.milestones.length>=WORK_SETUP_LIMITS.milestones} onClick={()=>add('milestones')}>Add milestone</Button>
 <h2>Actions</h2>{definition.actions.map((row,i)=><fieldset className="bo-work-setup-row" key={row.key}><legend>Action {i+1}</legend><div className="bo-work-setup-grid"><label>Action title<input required maxLength={120} value={row.title} onChange={e=>rowChange('actions',row.key,{title:e.target.value})}/></label><label>Action instructions<textarea maxLength={5000} value={row.instructions} onChange={e=>rowChange('actions',row.key,{instructions:e.target.value})}/></label><Offset label="Action due offset" value={row.dueOffset} onChange={dueOffset=>rowChange('actions',row.key,{dueOffset})}/><label>Milestone<select value={row.milestoneKey||''} onChange={e=>rowChange('actions',row.key,{milestoneKey:e.target.value||null})}><option value="">No milestone</option>{definition.milestones.map(m=><option key={m.key} value={m.key}>{m.name||'Unnamed milestone'}</option>)}</select></label></div>
 <details><summary>Dependencies for Action {i+1}</summary><p>This Action waits for the selected Actions to finish.</p>{definition.actions.filter(a=>a.key!==row.key).map(a=><label className="bo-work-setup-check" key={a.key}><input type="checkbox" checked={row.dependsOn.includes(a.key)} onChange={e=>rowChange('actions',row.key,{dependsOn:e.target.checked?[...row.dependsOn,a.key]:row.dependsOn.filter(k=>k!==a.key)})}/>{a.title||'Unnamed action'}</label>)}</details><Button onClick={()=>remove('actions',row.key)}>Remove action {i+1}</Button></fieldset>)}<Button disabled={definition.actions.length>=WORK_SETUP_LIMITS.actions} onClick={()=>add('actions')}>Add action</Button>
 <h2>Deliverables</h2>{definition.deliverables.map((row,i)=><fieldset className="bo-work-setup-row" key={row.key}><legend>Deliverable {i+1}</legend><div className="bo-work-setup-grid"><label>Deliverable title<input required maxLength={120} value={row.title} onChange={e=>rowChange('deliverables',row.key,{title:e.target.value})}/></label><label>Deliverable instructions<textarea maxLength={5000} value={row.instructions} onChange={e=>rowChange('deliverables',row.key,{instructions:e.target.value})}/></label><Offset label="Deliverable target offset" value={row.targetOffset} onChange={targetOffset=>rowChange('deliverables',row.key,{targetOffset})}/></div><Button onClick={()=>remove('deliverables',row.key)}>Remove deliverable {i+1}</Button></fieldset>)}<Button disabled={definition.deliverables.length>=WORK_SETUP_LIMITS.deliverables} onClick={()=>add('deliverables')}>Add deliverable</Button>
 </fieldset>{canEdit&&<div className="bo-form-actions"><Button type="submit" variant="primary" disabled={locked}>{busy?'Saving…':'Save setup version'}</Button>{initial&&<Button disabled={locked||dirty} onClick={()=>mutate('active')}>{initial.active?'Retire setup':'Restore setup'}</Button>}</div>}</form>
 {initial&&options&&initial.active&&!projectId&&<section><h2>Start a new job</h2><p>Use the saved version. Work starts internal and unassigned, without copied approvals, completion or sending state.</p>{dirty&&<p>Save your setup changes before generating work.</p>}
 <form onSubmit={propose}><fieldset disabled={!ready||busy||!!pending.current||dirty||conflict||previewBusy}><legend>Client and event</legend><div className="bo-work-setup-grid"><label>Client<select required value={selection.clientId} onChange={e=>choose({clientId:e.target.value,serviceEngagementId:''})}><option value="">Choose a Client</option>{options.clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Purchased Service<select value={selection.serviceEngagementId} onChange={e=>choose({serviceEngagementId:e.target.value})}><option value="">No purchased Service</option>{options.services.filter(s=>s.clientId===selection.clientId).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Event name<input required maxLength={120} value={selection.eventName} onChange={e=>choose({eventName:e.target.value})}/></label><label>Event date<input required type="date" min="0100-01-01" max="9999-12-31" value={selection.eventDate} onChange={e=>choose({eventDate:e.target.value})}/></label></div><Button type="submit">{previewBusy?'Preparing preview…':'Preview new job'}</Button></fieldset></form>
 {preview&&<section aria-label="New job preview"><h3>{preview.plan.project.name}</h3><p>Project: {date(preview.plan.project.startDate)} to {date(preview.plan.project.targetDate)}. Planned and on track.</p>
 <h4>Milestones</h4>{!preview.plan.milestones.length&&<p>No milestones.</p>}<ul>{preview.plan.milestones.map(m=><li key={m.key}><strong>{m.name}</strong><p>{date(m.startDate)} to {date(m.targetDate)}</p></li>)}</ul>
 <h4>Actions</h4>{!preview.plan.actions.length&&<p>No actions.</p>}<ul>{preview.plan.actions.map(a=><li key={a.key}><strong>{a.title}</strong><p>{a.description}</p><p>Due: {date(a.dueDate)}. Milestone: {preview.plan.milestones.find(m=>m.key===a.milestoneKey)?.name||'None'}.</p>{preview.plan.dependencies.filter(e=>e.actionKey===a.key).map(e=><p key={e.dependsOnKey}>Depends on: {preview.plan.actions.find(x=>x.key===e.dependsOnKey)?.title}</p>)}</li>)}</ul>
 <h4>Deliverables</h4>{!preview.plan.deliverables.length&&<p>No deliverables.</p>}<ul>{preview.plan.deliverables.map(d=><li key={d.key}><strong>{d.title}</strong><p>{d.description}</p><p>Target: {date(d.targetDate)}</p></li>)}</ul><Button variant="primary" disabled={busy||!!pending.current||dirty||conflict} onClick={()=>mutate('generate')}>{busy?'Creating…':'Create this job'}</Button></section>}
 </section>}</div>;
}
