// Turning stored embed blocks into iframes for a public page.
//
// This is the security boundary. A page body persists an inert div and a plain
// link; nothing on the public path renders a frame unless this function puts
// one there, and it only does that for allowlisted providers whose URL still
// parses as that provider.
//
// The direction matters. We ADD capability rather than stripping it, so every
// failure mode — a provider we don't allow, a URL that no longer matches, this
// module never being called — leaves the page showing the link that was
// already in the body. Fail-safe, not fail-open.
//
// Deliberately plain JS rather than HTMLRewriter. HTMLRewriter is a workerd
// global: it does not exist in `next dev`, and the old Pages adapter could not
// run on the Windows box this was developed on. Depending on it meant the one function
// deciding what a client may load could not be exercised until it was already
// deployed. This version runs in Node, so tests/public-embeds.test.mjs covers
// it like anything else.
//
// Regex over arbitrary HTML would be a bad idea. This is not that: the shape
// is machine-generated by the Embed node's renderHTML, the node is an atom so
// nothing nests inside it, and the replacement is rebuilt entirely from
// registry values with every interpolation escaped. No part of the stored
// document is ever copied through as markup.

import { isPublicSafe, embedUrlFor, embedLabel, getProvider } from './embeds.mjs';

// Kept identical to the editor's sandbox (components/EmbedView.jsx). See the
// note there for why allow-same-origin is sound: matchEmbed refuses our own
// host, so a framed page is always a third party isolated from us anyway.
export const SANDBOX =
  'allow-scripts allow-same-origin allow-popups allow-popups-to-escape-sandbox allow-forms allow-presentation';

// An embed block as this app writes it: no nested elements beyond the
// fallback anchor, so the first closing tag is always the right one.
const EMBED_BLOCK = /<div\b([^>]*\bdata-embed\b[^>]*)>([\s\S]*?)<\/div>/gi;

function esc(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function attrFrom(tagAttrs, name) {
  const m = tagAttrs.match(new RegExp(`\\b${name}\\s*=\\s*"([^"]*)"`, 'i'));
  return m ? m[1] : '';
}

// Entities have to come back off before the URL is re-validated, or a stored
// &amp; would fail the provider match that the same URL passed on the way in.
function unesc(s) {
  return String(s)
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&amp;/g, '&');
}

function frameHtml(provider, url, src) {
  const meta = getProvider(provider);
  const label = embedLabel(url);
  const style = meta?.height
    ? `height:${Number(meta.height)}px`
    : `aspect-ratio:${esc(meta?.aspect || '16/9')}`;
  const fs = meta?.allowFullscreen ? ' allowfullscreen' : '';
  return (
    `<div class="ltb-embed-frame" style="${style}">` +
    `<iframe src="${esc(src)}" title="${esc((meta?.label || 'Embed') + ': ' + label)}" ` +
    `sandbox="${SANDBOX}" referrerpolicy="no-referrer" loading="lazy"${fs}></iframe>` +
    `</div>` +
    `<a class="ltb-embed-caption" href="${esc(url)}" target="_blank" rel="noopener nofollow">${esc(label)}</a>`
  );
}

export function upgradeEmbedsForPublic(bodyHtml, selfHost) {
  const html = String(bodyHtml || '');
  if (!html.includes('data-embed')) return html;

  return html.replace(EMBED_BLOCK, (whole, tagAttrs) => {
    const provider = unesc(attrFrom(tagAttrs, 'data-provider'));
    const url = unesc(attrFrom(tagAttrs, 'data-url'));

    // Not allowed in public — leave the block exactly as stored, which is
    // already a working link.
    if (!isPublicSafe(provider)) return whole;

    // Rebuilt from the registry, never read from the document, so a
    // hand-edited body cannot choose its own src.
    const src = embedUrlFor(provider, url, selfHost);
    if (!src) return whole;

    return (
      `<div class="ltb-embed" data-embed data-provider="${esc(provider)}" data-url="${esc(url)}">` +
      frameHtml(provider, url, src) +
      `</div>`
    );
  });
}
