// Append-only operational history. One helper so every writer records the
// same shape, and so metadata is always JSON the reader can rely on.
import { sql } from 'drizzle-orm';
import { schema } from './db.mjs';

export const ACTIVITY = {
  PROSPECT_CONVERTED:'PROSPECT_CONVERTED',
  PAGE_COMMENT_ADDED:'PAGE_COMMENT_ADDED',
  PAGE_DISCUSSION_RESOLVED:'PAGE_DISCUSSION_RESOLVED',
  PAGE_DISCUSSION_REOPENED:'PAGE_DISCUSSION_REOPENED',
  PAGE_CREATED:'PAGE_CREATED',
  PAGE_SAVED:'PAGE_SAVED',
  PAGE_ACCESS_CHANGED:'PAGE_ACCESS_CHANGED',
  PAGE_ICON_CHANGED:'PAGE_ICON_CHANGED',
  PAGE_MOVED:'PAGE_MOVED',
  PROSPECT_MONITORING_CHECKPOINT:'PROSPECT_MONITORING_CHECKPOINT',
  PROSPECT_REPORT_STARTED:'PROSPECT_REPORT_STARTED',
  PROSPECT_REPORT_CHECKED:'PROSPECT_REPORT_CHECKED',
  PROSPECT_RECOVERY_COLLECTED:'PROSPECT_RECOVERY_COLLECTED',
  PROSPECT_DISCOVERY_STARTED:'PROSPECT_DISCOVERY_STARTED',
  PROSPECT_DISCOVERY_CHECKED:'PROSPECT_DISCOVERY_CHECKED',
  PROSPECT_DISCOVERY_HELD:'PROSPECT_DISCOVERY_HELD',
  PROSPECT_REPLY_CHECK_STARTED:'PROSPECT_REPLY_CHECK_STARTED',
  PROSPECT_DELIVERY_IDENTITY_VERIFIED:'PROSPECT_DELIVERY_IDENTITY_VERIFIED',
  PROSPECT_REPLY_CHECKED:'PROSPECT_REPLY_CHECKED',
  PROSPECT_REPLY_OBSERVED:'PROSPECT_REPLY_OBSERVED',
  PROSPECT_OUTREACH_STOPPED:'PROSPECT_OUTREACH_STOPPED',
  PROSPECT_DELIVERY_PREPARED:'PROSPECT_DELIVERY_PREPARED',
  PROSPECT_DELIVERY_CANCELLED:'PROSPECT_DELIVERY_CANCELLED',
  PROSPECT_DELIVERY_ATTEMPTED:'PROSPECT_DELIVERY_ATTEMPTED',
  PROSPECT_DELIVERY_UNCERTAIN:'PROSPECT_DELIVERY_UNCERTAIN',
  PROSPECT_DELIVERY_ACCEPTED:'PROSPECT_DELIVERY_ACCEPTED',
  PROSPECT_GOOGLE_CONNECTED:'PROSPECT_GOOGLE_CONNECTED',
  PROSPECT_GOOGLE_DISCONNECTED:'PROSPECT_GOOGLE_DISCONNECTED',
  PROSPECT_GOOGLE_CHECKED:'PROSPECT_GOOGLE_CHECKED',
  PROSPECT_SENDER_UPDATED:'PROSPECT_SENDER_UPDATED',
  PROSPECT_DRAFT_SAVED:'PROSPECT_DRAFT_SAVED',
  PROSPECT_DRAFT_APPROVED:'PROSPECT_DRAFT_APPROVED',
  PROSPECT_CREATED: 'PROSPECT_CREATED',
  PROSPECT_UPDATED: 'PROSPECT_UPDATED',
  PROSPECT_SKILL_RESULT_SAVED: 'PROSPECT_SKILL_RESULT_SAVED',
  ONBOARDING_GUIDANCE_UPDATED: 'ONBOARDING_GUIDANCE_UPDATED',
  CONTENT_APPROVAL_REQUESTED: 'CONTENT_APPROVAL_REQUESTED',
  CONTENT_APPROVAL_APPROVED: 'CONTENT_APPROVAL_APPROVED',
  CONTENT_APPROVAL_CHANGES_REQUESTED: 'CONTENT_APPROVAL_CHANGES_REQUESTED',
  CONTENT_APPROVAL_WITHDRAWN: 'CONTENT_APPROVAL_WITHDRAWN',
  CONTENT_PLATFORMS_CHANGED: 'CONTENT_PLATFORMS_CHANGED',
  CONTENT_STAGE_CHANGED: 'CONTENT_STAGE_CHANGED',
  CONTENT_CREATED: 'CONTENT_CREATED',
  CONTENT_DETAILS_UPDATED: 'CONTENT_DETAILS_UPDATED',
  WORKSPACE_CREATED: 'WORKSPACE_CREATED',
  MEMBERSHIP_CREATED: 'MEMBERSHIP_CREATED',
  MEMBERSHIP_ACTIVATED: 'MEMBERSHIP_ACTIVATED',
  MEMBERSHIP_SUSPENDED: 'MEMBERSHIP_SUSPENDED',
  MEMBERSHIP_REINSTATED: 'MEMBERSHIP_REINSTATED',
  MEMBERSHIP_REMOVED: 'MEMBERSHIP_REMOVED',
  INVITATION_SENT: 'INVITATION_SENT',
  INVITATION_RESENT: 'INVITATION_RESENT',
  INVITATION_REVOKED: 'INVITATION_REVOKED',
  INVITATION_EXPIRED: 'INVITATION_EXPIRED',
  INVITATION_ACCEPTED: 'INVITATION_ACCEPTED',
  CAPABILITY_GRANTED: 'CAPABILITY_GRANTED',
  CAPABILITY_REVOKED: 'CAPABILITY_REVOKED',
  // Clients (A6). One event per significant fact that changed: a validation
  // failure, a refused request, and a no-op write none of them record
  // anything, and one request never records the same fact twice.
  CLIENT_ACTIVATED: 'CLIENT_ACTIVATED',
  ONBOARDING_STARTED: 'ONBOARDING_STARTED',
  ONBOARDING_ITEM_SUBMITTED: 'ONBOARDING_ITEM_SUBMITTED',
  ONBOARDING_ITEM_COMPLETED: 'ONBOARDING_ITEM_COMPLETED',
  ONBOARDING_ITEM_VERIFIED: 'ONBOARDING_ITEM_VERIFIED',
  ONBOARDING_ITEM_WAIVED: 'ONBOARDING_ITEM_WAIVED',
  ONBOARDING_ITEM_NOT_APPLICABLE: 'ONBOARDING_ITEM_NOT_APPLICABLE',
  ONBOARDING_COMPLETED: 'ONBOARDING_COMPLETED',
  CLIENT_ONBOARDING_COMPLETED: 'CLIENT_ONBOARDING_COMPLETED',
  CLIENT_INVITED: 'CLIENT_INVITED',
  CLIENT_CREATED: 'CLIENT_CREATED',
  CLIENT_DETAILS_UPDATED: 'CLIENT_DETAILS_UPDATED',
  CLIENT_OWNER_CHANGED: 'CLIENT_OWNER_CHANGED',
  CLIENT_HEALTH_CHANGED: 'CLIENT_HEALTH_CHANGED',
  CLIENT_CONTACT_ADDED: 'CLIENT_CONTACT_ADDED',
  CLIENT_CONTACT_UPDATED: 'CLIENT_CONTACT_UPDATED',
  CLIENT_CONTACT_REMOVED: 'CLIENT_CONTACT_REMOVED',
  CLIENT_PRIMARY_CONTACT_CHANGED: 'CLIENT_PRIMARY_CONTACT_CHANGED',
  // Services and scoped team assignment (A7). Same rules: one event per
  // fact that actually changed, none on a refusal, none on a no-op, and
  // never the same fact twice. A service event carries both the client and
  // the engagement, so one client's history reads as one story.
  SERVICE_ENGAGEMENT_CREATED: 'SERVICE_ENGAGEMENT_CREATED',
  SERVICE_DETAILS_UPDATED: 'SERVICE_DETAILS_UPDATED',
  SERVICE_STATUS_CHANGED: 'SERVICE_STATUS_CHANGED',
  CLIENT_ASSIGNMENT_ADDED: 'CLIENT_ASSIGNMENT_ADDED',
  CLIENT_ASSIGNMENT_UPDATED: 'CLIENT_ASSIGNMENT_UPDATED',
  CLIENT_ASSIGNMENT_REMOVED: 'CLIENT_ASSIGNMENT_REMOVED',
  SERVICE_ASSIGNMENT_ADDED: 'SERVICE_ASSIGNMENT_ADDED',
  SERVICE_ASSIGNMENT_UPDATED: 'SERVICE_ASSIGNMENT_UPDATED',
  SERVICE_ASSIGNMENT_REMOVED: 'SERVICE_ASSIGNMENT_REMOVED',
  PROJECT_CREATED: 'PROJECT_CREATED',
  PROJECT_BLUEPRINT_GENERATED: 'PROJECT_BLUEPRINT_GENERATED',
  PROJECT_DETAILS_UPDATED: 'PROJECT_DETAILS_UPDATED',
  PROJECT_OWNER_CHANGED: 'PROJECT_OWNER_CHANGED',
  PROJECT_STATUS_CHANGED: 'PROJECT_STATUS_CHANGED',
  PROJECT_HEALTH_CHANGED: 'PROJECT_HEALTH_CHANGED',
  PROJECT_ASSIGNMENT_ADDED: 'PROJECT_ASSIGNMENT_ADDED',
  PROJECT_ASSIGNMENT_UPDATED: 'PROJECT_ASSIGNMENT_UPDATED',
  PROJECT_ASSIGNMENT_REMOVED: 'PROJECT_ASSIGNMENT_REMOVED',
  MILESTONE_CREATED: 'MILESTONE_CREATED',
  MILESTONE_DETAILS_UPDATED: 'MILESTONE_DETAILS_UPDATED',
  MILESTONE_STATUS_CHANGED: 'MILESTONE_STATUS_CHANGED',
  MILESTONE_ORDER_CHANGED: 'MILESTONE_ORDER_CHANGED',
  ACTION_CREATED: 'ACTION_CREATED',
  ACTION_DETAILS_UPDATED: 'ACTION_DETAILS_UPDATED',
  ACTION_ASSIGNEE_CHANGED: 'ACTION_ASSIGNEE_CHANGED',
  ACTION_STATUS_CHANGED: 'ACTION_STATUS_CHANGED',
  ACTION_DEPENDENCY_ADDED: 'ACTION_DEPENDENCY_ADDED',
  ACTION_DEPENDENCY_REMOVED: 'ACTION_DEPENDENCY_REMOVED',
  DELIVERABLE_CREATED: 'DELIVERABLE_CREATED',
  FILE_UPLOADED: 'FILE_UPLOADED',
  FILE_ARCHIVED: 'FILE_ARCHIVED',
  FILE_VISIBILITY_CHANGED: 'FILE_VISIBILITY_CHANGED',
  DELIVERABLE_DETAILS_UPDATED: 'DELIVERABLE_DETAILS_UPDATED',
  DELIVERABLE_STATUS_CHANGED: 'DELIVERABLE_STATUS_CHANGED',
};

// The row an event becomes, without writing it. Callers that must record an
// event in the same atomic write as the change it describes (client
// creation, say) put `db.insert(schema.activityEvents).values(activityValues(...))`
// into their batch instead of calling recordActivity afterwards.
export function activityValues({ workspaceId, eventType, subjectType, subjectId, actorMembershipId = null, actorUserId = null, clientId = null, serviceEngagementId = null, metadata = null, occurredAt = null }) {
  if (!ACTIVITY[eventType]) throw new Error(`Unknown activity event type ${eventType}`);
  const values = {
    workspaceId,
    eventType,
    subjectType,
    subjectId,
    actorMembershipId,
    actorUserId,
    clientId,
    serviceEngagementId,
    metadataJson: metadata ? JSON.stringify(metadata) : null,
  };
  if (occurredAt) values.occurredAt = occurredAt;
  return values;
}

export async function recordActivity(db, event) {
  await db.insert(schema.activityEvents).values(activityValues(event));
}

// Place immediately BEFORE the matching conditional update/delete in one
// batch. The event and mutation see the same row under D1's write lock; a
// stale predicate inserts neither, and a later failure rolls both back.
export function activityForMutation(db, table, condition, event) {
  const now = event.occurredAt || new Date().toISOString();
  const values = { id: crypto.randomUUID(), ...activityValues(event), occurredAt: now, createdAt: now };
  return db.insert(schema.activityEvents).select(db.select(Object.fromEntries(
    Object.entries(values).map(([key, value]) => [key, sql`${value}`.as(key)]),
  )).from(table).where(condition));
}
