import {notFound} from 'next/navigation';
import {requireShell} from '@/lib/bloomops/shell-server.mjs';
import {getProspectGoogle} from '@/lib/bloomops/prospect-google.mjs';
import {prospectOutreachOverview} from '@/lib/bloomops/prospect-outreach.mjs';
import {prospectReplyOverview} from '@/lib/bloomops/prospect-replies.mjs';
import {prospectAutomationOverview,prospectCoverageCopy,prospectCoverageOverview,prospectExceptionCopy} from '@/lib/bloomops/prospect-overview.mjs';
import {Button,PageHeader,Status} from '@/components/bloomops/Primitives';
import {Icon} from '@/components/bloomops/Icons';
import ProspectAvatar from '@/components/bloomops/ProspectAvatar';
export const dynamic='force-dynamic';
export const metadata={title:'Prospecting Overview'};
export default async function OverviewPage({searchParams}){
 const {access,actor}=await requireShell('internal'),query=await searchParams,draftPage=Number(query.page??1),exceptionPage=Number(query.exceptionsPage??1),handledPage=Number(query.handledPage??1);
 const data=await prospectOutreachOverview(access.db,actor,draftPage);if(!data)notFound();const connection=await getProspectGoogle(access.db,actor,access.env);if(!connection)notFound();
 const replies=await prospectReplyOverview(access.db,actor,exceptionPage,handledPage);if(!replies)notFound();const coverage=await prospectCoverageOverview(access.db,actor,connection.accountEmail);if(!coverage)notFound();
 const automation=await prospectAutomationOverview(access.db,actor,access.env,{sender:data.sender,connection}),coverageCopy=prospectCoverageCopy(coverage),queryLink=values=>'?'+new URLSearchParams({page:String(data.page),exceptionsPage:String(replies.page),handledPage:String(replies.handledPage),...values}).toString();
 return <div className="bo-prospect-page"><PageHeader title="Overview" subtitle="Human decisions first, with saved work and automation state kept separate." actions={<Button href="/prospecting/mailbox" icon="history" variant="ghost">Mailbox review</Button>}/>
 <section className={'bo-overview-automation bo-overview-automation-'+automation.state}><span className="bo-outreach-mark"><Icon name="settings" size={20}/></span><div className="bo-overview-automation-copy"><div className="bo-overview-heading"><h2>{automation.label}</h2><Status tone={['unconfigured','failed','held'].includes(automation.state)?'warning':automation.state==='running'?'success':'neutral'} glyph={automation.state==='unconfigured'?'alert':automation.state==='running'?'check':'dash'} label={automation.state[0].toUpperCase()+automation.state.slice(1)}/></div><p>{automation.state==='unconfigured'?'Set up a sender and verified mailbox connection before any outreach can be considered.':automation.state==='running'?`${automation.counts.running} approved ${automation.counts.running===1?'sequence is':'sequences are'} scheduled. Each due message remains subject to a fresh metadata and stop check.`:automation.state==='inactive'&&automation.counts?.running?`${automation.counts.running} approved ${automation.counts.running===1?'sequence is saved':'sequences are saved'}, but the server-side executor is disabled.`:automation.state==='failed'?'An ambiguous provider outcome is locked against resending and needs receipt reconciliation.':automation.state==='held'?'Recorded evidence or configuration is preventing the next message. Review the affected delivery safely.':automation.state==='stopped'?'Recorded stops or conversions prevent further cold outreach.':'A mailbox connection is saved, but no monitoring or sending job is recorded as running.'}</p><p className="bo-hint">{connection.connected?'Google is connected. That connection alone does not activate monitoring or sending.':connection.hasStoredGrant?'The saved Google connection is not currently usable.':'No Google mailbox is connected.'}</p></div><Button href="/prospecting/sender" icon="settings">Sender setup</Button></section>
 <section className="bo-overview-decisions" aria-labelledby="overview-decisions"><div className="bo-overview-section-heading"><div><h2 id="overview-decisions">Needs a human decision</h2><p>{replies.total?`${replies.total} ${replies.total===1?'conversation needs':'conversations need'} review.`:'No recorded conversation holds or stops need review.'}</p></div>{replies.total>0&&<Status tone="warning" glyph="alert" label={`${replies.total} affected`}/>}</div>
 {replies.groups.length>0?<ul className="bo-overview-groups">{replies.groups.map(group=>{const copy=prospectExceptionCopy(group);return <li key={copy.key}><span>{copy.label}</span><strong>{group.count}</strong></li>})}</ul>:<div className="bo-overview-clear"><Icon name="check" size={20}/><p>There are no recorded conversation exceptions. Untouched prospects and saved drafts are not treated as urgent.</p></div>}
 {replies.rows.length>0&&<ul className="bo-overview-exceptions">{replies.rows.map(row=>{const copy=prospectExceptionCopy(row);return <li key={row.id}><div className="bo-outreach-prospect"><ProspectAvatar id={row.id} website={row.website}/><div><h3>{row.businessName}</h3><p className="bo-overview-reason"><strong>{copy.label}.</strong> {copy.detail}</p></div></div><Status tone={row.holdState==='stopped'?'error':'warning'} glyph={row.holdState==='stopped'?'cross':'dash'} label={row.holdState==='stopped'?'Stopped':'Held'}/><Button href={'/prospecting/'+row.id+'/replies'} icon="history">Review conversation</Button></li>})}</ul>}
 <nav className="bo-prospect-pagination" aria-label="Conversation exception pages">{replies.page>1&&<Button href={queryLink({exceptionsPage:String(replies.page-1)})}>Previous exceptions</Button>}{replies.more&&<Button href={queryLink({exceptionsPage:String(replies.page+1)})}>Next exceptions</Button>}</nav></section>
 {replies.handledTotal>0&&<section className="bo-overview-handled" aria-labelledby="overview-handled"><div className="bo-overview-section-heading"><div><h2 id="overview-handled">Handled, protection retained</h2><p>{replies.handledTotal} {replies.handledTotal===1?'decision is':'decisions are'} recorded. Outreach remains held unless a separately supported future action changes that protection.</p></div><Status tone="success" glyph="check" label={`${replies.handledTotal} handled`}/></div><ul className="bo-overview-exceptions">{replies.handledRows.map(row=><li key={row.id}><div className="bo-outreach-prospect"><ProspectAvatar id={row.id} website={row.website}/><div><h3>{row.businessName}</h3><p className="bo-overview-reason"><strong>Reply handled.</strong> {row.resolutionNote}</p></div></div><Status tone="warning" glyph="dash" label="Outreach held"/><Button href={'/prospecting/'+row.id+'/replies'} icon="history">Review conversation</Button></li>)}</ul><nav className="bo-prospect-pagination" aria-label="Handled conversation pages">{replies.handledPage>1&&<Button href={queryLink({handledPage:String(replies.handledPage-1)})}>Previous handled</Button>}{replies.handledMore&&<Button href={queryLink({handledPage:String(replies.handledPage+1)})}>Next handled</Button>}</nav></section>}
 <section className="bo-overview-coverage"><div><h2>{coverageCopy.label}</h2><p>{coverageCopy.detail}</p></div><Button href="/prospecting/mailbox" icon="history">Review mailbox coverage</Button></section>
 <section className="bo-outreach-overview bo-overview-prepared"><div className="bo-overview-section-heading"><div><h2>Prepared work</h2><p>Saved drafts are available when you choose to review them. They are not urgent exceptions.</p></div></div>{data.rows.length?<ul className="bo-outreach-drafts">{data.rows.map(row=><li key={row.id}><div className="bo-outreach-prospect"><ProspectAvatar id={row.id} website={row.website}/><h3>{row.businessName}</h3></div><Status tone={row.approved?'success':'neutral'} label={row.approved?'Content approved':row.profileRevision!==row.sourceProfileRevision?'Profile changed':'Needs review'}/><Button href={'/prospecting/'+row.id+'/outreach'} icon="chevron-right">Review draft</Button></li>)}</ul>:<div className="bo-outreach-empty"><Icon name="pages" size={28}/><h3>{data.page===1?'No saved outreach drafts':'No more drafts'}</h3><p>Open a prospect to prepare an introduction and two follow-ups.</p><Button href="/prospecting" icon="prospecting">Browse prospects</Button></div>}</section>
 <nav className="bo-prospect-pagination" aria-label="Draft pages">{data.page>1&&<Button href={queryLink({page:String(data.page-1)})}>Previous drafts</Button>}{data.more&&<Button href={queryLink({page:String(data.page+1)})}>Next drafts</Button>}</nav>
 </div>;
}
