import {requireShell} from '@/lib/bloomops/shell-server.mjs';
import {listFinanceRecords,financePermission} from '@/lib/bloomops/finance.mjs';
import {FINANCE_STATUSES,financeLabel} from '@/lib/bloomops/finance-values.mjs';
import {PageHeader,Button,Surface,Status} from '@/components/bloomops/Primitives';
export const dynamic='force-dynamic';
export const metadata={title:'Finance'};
export default async function FinancePage({searchParams}){
 const {access,actor}=await requireShell('internal'),q=await searchParams,result=await listFinanceRecords(access.db,actor,q),manage=await financePermission(access.db,actor,'capabilities.manage');
 const href=page=>'/finance?'+new URLSearchParams({...q,page:String(page)});
 return <><PageHeader title="Finance" subtitle="Manual invoices and payments. No money is sent or collected here." actions={<>{manage&&<Button href="/team/finance-access">Manage Finance access</Button>}{result.canEdit&&<Button href="/finance/new" variant="primary">New finance record</Button>}</>}/>
 {!result.ok?<Surface padding="lg"><p>{result.reason==='invalid'?'These Finance filters are invalid.':'Finance is private. Ask a workspace administrator to configure your access.'}</p>{result.reason==='invalid'&&<Button href="/finance">Reset filters</Button>}</Surface>:<>
 <form className="bo-finance-filters" action="/finance"><label>Record type<select aria-label="Record type" name="kind" defaultValue={q.kind||''}><option value="">All types</option><option value="invoice">Invoices</option><option value="payment">Payments</option></select></label><label>Status<select aria-label="Status" name="status" defaultValue={q.status||''}><option value="">All statuses</option>{Object.values(FINANCE_STATUSES).flat().map(s=><option key={s} value={s}>{financeLabel(s)}</option>)}</select></label><label>History<select aria-label="History" name="archived" defaultValue={q.archived||''}><option value="">Active records</option><option value="true">Archived records</option></select></label><label>Due view<select aria-label="Due view" name="overdue" defaultValue={q.overdue||''}><option value="">All dates</option><option value="true">Overdue invoices</option></select></label>{q.clientId&&<input type="hidden" name="clientId" value={q.clientId}/>} {q.serviceEngagementId&&<input type="hidden" name="serviceEngagementId" value={q.serviceEngagementId}/>}<div className="bo-action-filter-buttons"><Button type="submit">Apply filters</Button><Button href="/finance" variant="ghost">Reset</Button></div></form>
 <details className="bo-finance-scope"><summary>Dates and calculation scope</summary><p className="bo-small">Overdue uses the UTC calendar day ({result.today}). Totals cover all filtered, authorized records; invoice and payment totals are separate.</p></details>
 {result.totals.length>0&&<section aria-label="Finance totals" className="bo-finance-totals">{result.totals.map(t=><div key={[t.currency,t.digits,t.kind,t.status].join('-')}><h2 className="bo-h3">{financeLabel(t.kind)}: {financeLabel(t.status)}</h2><p>{t.currency} {t.amount}</p><span>{t.count} {t.count===1?'record':'records'}</span></div>)}</section>}
 <section aria-label="Finance records">{!result.items.length?<Surface padding="lg"><h2 className="bo-h2">No finance records in this view</h2><p>Create a manual record or change the filters.</p></Surface>:<div className="bo-finance-table-wrap"><table className="bo-finance-table"><thead><tr><th scope="col">Record / Client</th><th scope="col">Type / Status</th><th scope="col">Amount</th><th scope="col">Dates</th></tr></thead><tbody>{result.items.map(r=><tr key={r.id}><td><a className="bo-finance-title" href={'/finance/'+r.id}>{r.title}</a><dl className="bo-record-context"><div><dt>Client</dt><dd><a href={'/finance?clientId='+encodeURIComponent(r.clientId)}>{r.clientName}</a></dd></div><div><dt>Service</dt><dd>{r.serviceEngagementId?<a href={'/finance?serviceEngagementId='+encodeURIComponent(r.serviceEngagementId)}>{r.serviceName}{r.packageName&&<span className="bo-finance-package">{r.packageName}</span>}</a>:'Client-level'}</dd></div></dl></td><td><span className="bo-finance-kind">{financeLabel(r.kind)}</span><Status label={financeLabel(r.status)}/></td><td className="bo-finance-amount"><span className="bo-sr-only">Amount </span>{r.currency} {r.amount}</td><td><dl className="bo-finance-dates"><div><dt>Due</dt><dd>{r.dueDate||'Not set'}</dd></div>{r.paidDate&&<div><dt>Paid</dt><dd>{r.paidDate}</dd></div>}{r.renewalDate&&<div><dt>Renewal</dt><dd>{r.renewalDate}</dd></div>}</dl></td></tr>)}</tbody></table></div>}</section>
 <nav aria-label="Finance pages" className="bo-form-actions">{result.page>1&&<Button href={href(result.page-1)}>Previous page</Button>}{result.more&&<Button href={href(result.page+1)}>Next page</Button>}</nav></>}
 </>;
}
